### ISSUE TITLE
[BUG]: Code versioning, cache invalidation, and git sha commit

### ISSUE THREAD

**Issue by ghpu** [zenml-io/zenml#1011]
### System Information

ZenML version: 0.20.5
Install path: /opt/anaconda3/lib/python3.9/site-packages/zenml
Python version: 3.9.7
Platform information: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '22.10'}
Environment: native
Integrations: ['github', 'huggingface', 'pillow', 'plotly', 'pytorch', 'pytorch_lightning', 'scipy', 'sklearn']

### What happened?

I have a (simplified) step function like this :
```python
@step
def json_file_loader() -> Output(corpus=dict):
    return toto
    
def toto():
    with open(params.filename,"r", encoding="utf-8") as f:
        return {"corpus":json.load(f)[0,10]}
```

If I change in the toto function 10 to 20, the pipeline cache is not invalidated.

It works if I the complete code is in the step function : 

```python
@step
def json_file_loader() -> Output(corpus=dict):
    with open(params.filename,"r", encoding="utf-8") as f:
        return {"corpus":json.load(f)[0,10]}
```

Moreover, If I then commit the code to git, the pipeline cache is still not invalidated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghpu** [comment]
As a work-around, I could extract git commit, and push it into a BaseParameter class.

**Comment by schustmi** [comment]
Correct, ZenML caching currently works by inspecting the parameters of the step as well as the source code of the step function. Detecting and inspecting all the functions that a step calls as shown in your example is not implemented as that would be quite complicated and require parsing of the AST.

We've considered using the git sha as the caching indicator as well, but it comes with its own limitations:
- If we simply use the HEAD commit hash, then modifying a single unrelated file will disable caching for all your steps
- If we use the commit hash that last modified the file which contains the step, we will have a similar issue that you described above (I just separated the step definition and helper function into separate files):
```python
# my_step.py
from .utils import helper_function

@step
def my_step() -> None:
    helper_function()

# utils.py
def helper_function() -> None:
    # if we modify this, how to disable caching?
    ...
```

Do you have any concrete suggestions how we could improve the cache detection?

**Comment by ghpu** [comment]
You are right that AST parsing is probably not the solution, especially with sadists like me who fancy having dynamic calls (through getattr ), and dynamically tracing the code is no solution either.

I woud like the git commit hash approach, if I could define which folders to watch (maybe pipelines and steps by default).

**Comment by ghpu** [comment]
An alternative could be to declaratively specify dependency functions to checksum and track in a new step parameter)

**Comment by schustmi** [comment]
I agree, no matter if we go with git sha or the source code to check if code has changed, we could definitely make it customizable as you described. I'll discuss this internally if the rest of the team agrees and when we can get to it.

**Comment by htahir1** [comment]
@ghpu Perhaps we can shift these ideas to this issue on the roadmap made by @jsuchome https://zenml.hellonext.co/p/configure-caching-behavior-based-on-step-input-output

Maybe  we can combine and consolidate it there and close this issue?
