### ISSUE TITLE
[FEATURE]: Update Evidently integration to include `TestSuite`

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#1013]
ZenML currently offers a [built-in integration](https://zenml.io/integrations/evidently) with [Evidently's monitoring tool](https://github.com/evidentlyai/evidently/). The integration is currently pinned to version 0.1.52dev0, so this ticket would include

- updating the pinned version to the most recent in `src/zenml/integrations/evidently/__init__.py`
- adding in relevant functionality to enable use of [Evidently's 'Test Suite'](https://docs.evidentlyai.com/tests/overview) from within ZenML
- add unit tests to cover the new code that's added
- (stretch goal): update [the ZenML-Evidently example](https://github.com/zenml-io/zenml/tree/main/examples/evidently_drift_detection) to include the new functionality

**Comment by stefannica** [comment]
Covered in https://github.com/zenml-io/zenml/pull/1283
