### ISSUE TITLE
[FEATURE]: Validate slack alerter credentials on registration

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#1014]
We currently allow the registration of the slack alerter (via the CLI) but we don’t validate that the credentials are sound at that exact moment. If someone uses the wrong credentials, they will get an error message when using the alerter (e.g. when running [the Slack Alerter example](https://github.com/zenml-io/zenml/tree/develop/examples/slack_alert)).

The experience would be cleaner if the user knew at component registration that the credentials supplied were invalid. This issue therefore includes making the relevant checks for credentials at registration time.

**Comment by bhatt-priyadutt** [comment]
@strickvl at the registration time, I see we will have to get these validation checks in the stack_components.py register logic for specifically alerter - slack. below is the suspected place where this logic likely to be placed if I understood correctly. But this will be like adding logic in a common register logic for a very specific alerter integration.

https://github.com/zenml-io/zenml/blob/e055d318b326cdc305301d5130b2f2fa46d613e0/src/zenml/cli/stack_components.py#LL243C1-L243C1
