### ISSUE TITLE
[FEATURE]: Enable recursive deletion of a stack including all stack components

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#1015]
ZenML's `zenml stack delete ...` CLI command will currently delete your stack, but any stack components that were part of it aren't deleted.

This feature would enable this functionality such that when you delete a stack, all the stack components that are part of it would be deleted as well. Included as part of the work:

- full unit testing for this new functionality
- adding a new flag for the `zenml stack delete` subcommand to denote that you also want the components deleting as well
- handling the common case of 'default' local components which might be treated differently depending on the implementation and what makes sense.

**Comment by KenmogneThimotee** [comment]
Hello, I am new to open source I have used zenml for personal project and I want to take this to start contributing.
Are you ok with that ?

**Comment by strickvl** [comment]
Yes we'd love to receive a contribution on this issue. I checked with the team and it's still open.

The tricky thing will be not only handling the 'default' components (which shouldn't be deleted), but also making sure not to delete components associated with one stack if they are still being used / present in another stack. I imagine there might need to be some kind of user confirmation there. e.g. "Components X and Y cannot be deleted because they are part of other stacks. do you still want to delete the remaining components of the stacks (A, B, C)?"

Feel free to use this issue thread as a place to discuss the implementation, or to flesh out how you feel like you'd approach it, and of course please do check out our guide for contributors which includes a lot of useful information on how to submit so that your work passes the various linters etc.

Thanks for reaching out!

**Comment by KenmogneThimotee** [comment]
I am trying to install all integrations from the [https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md](documentation), which shows me an error that label-studio, kserve, and sagemaker have conflicting dependencies.
I need to install those integrations to run a test.

**Comment by strickvl** [comment]
I think you can probably ignore that step for the purposes of this issue / PR, since this is mainly work for the core repository (i.e. not touching integrations). If `mypy` gives errors for the integrations code, you can ignore it therefore.

**Comment by schustmi** [comment]
Implemented in version 0.37.0.
