### ISSUE TITLE
[BUG]: Parameter content incorrectly coerced

### ISSUE THREAD

**Issue by ghpu** [zenml-io/zenml#1065]
### System Information

ZenML version: 0.21.1
Install path: /opt/anaconda3/lib/python3.9/site-packages/zenml
Python version: 3.9.7
Platform information: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '22.10'}
Environment: native
Integrations: ['github', 'huggingface', 'pillow', 'plotly', 'pytorch', 'pytorch_lightning', 's3', 'scipy', 'sklearn']

### What happened?

In my BaseParameters derived class , I have a parameter containing tuples.
```
class MetricsParams(BaseParameters):
metrics_mapping = "precision" : {"metrics": "Precision", "args": {"exact":True}, "mapping":
                           {"gold": ("gold.annotations", [{"from":"from", "to":"to", "class":"class", "polarity":"polarity"}]),
                            "prediction": ("prediction.annotations", [{"from":"from", "to":"to", "class":"class", "polarity":"polarity"}])
                            }
                           },
```

But when I got this parameter in my step function, the tuplues have been incorrectly changed to lists .
This is cause by the following code in steps/base_step.py
```
 # Convert execution parameter values to strings
        try:
            execution_parameters = {
                k: json.dumps(v) for k, v in execution_parameters.items()
            }
        except TypeError as e:
            raise StepInterfaceError(
                f"Failed to serialize execution parameters for step "
                f"'{self.name}'. Please make sure to only use "
                f"json serializable parameter values."
            ) from e
```
Here, I am in the special case where json.dumps succeeds but silently converts my tuple into a list.

In my context, I need to preserve the tuple information, therefore json.dumps cannot be used. A simple work-around might be to use ```k: repr(v)``` instead, but this would not be very safe.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schustmi** [comment]
As you said yourself, calling `repr(...)` and `eval(...)` to store and reconstruct these parameters is unsafe and not something we're willing to add.

Let me instead give you an alternate approaches which should work to reconstruct your tuples. This relies on the fact that ZenML `BaseParameters` are subclassing [pydantics](https://pydantic-docs.helpmanual.io/) `BaseModel`. Pydantic is used for validating data but also takes care of casting the data according to the type hints that users specify.

To correctly reconstruct your `MetricsParams`, you can improve the type hints of your class. E.g.
```python
class MetricsParams(BaseParameters):
    metrics_mapping: Dict[str, Tuple[str, int]]   # instead of Dict[str, Any]
```
The above approach might not work in your case if the dict contains different types for different keys (in theory still possible using `Union[...]`). You could also split the dict and create attributes for each key. Or go the cleanest route IMO and create different `pydantic.BaseModel` classes that accurately represent your data:

```python
class Metric(BaseModel):
    metrics: str
    args: Dict[str, Any]
    ...
 
class MetricsParams(BaseParameters):
    metrics_mapping: Dict[str, Metric]
```

**Comment by ghpu** [comment]
For ZenML, I would be mainly concerned about the json.dumps inducing automatic tuple to list  conversion, even if pydantic can then coerce them back, given the right schema. As a user, I have no means to detect that some information might be lost during parameter serialisation.

It doesn't feel like JSON is required anywhere in handling parameters (it supports numbers and string anyways), so I'd rather having a laxer serialisation than JSON.

If JSON is however mandatory somewhere (because it gets interpreted for nested parameter analysis), maybe it would be wise to enforce that BaseParameter are only of type JSON (and don't support direct strings and number values).

**Comment by schustmi** [comment]
If we don't use json to serialize these more complex parameter types (e.g. tuples or dicts containing arbitrary data), we'd need to replace it with a different approach.

Enforcing just a single type on `BaseParameter` seems really bad from a user experience perspective.

The `json.dumps()` line that you highlighted that is used to convert each parameter separately will be removed in our ongoing MLMD removal, but we'll still using `params.json()` for serializing the parameters. But I think we can make it clearer in the docs that the serializing and deserializing of the parameters is handled by pydantic and therefore random data in a dict without clear type annotations is not covered.

**Comment by htahir1** [comment]
Closing after this discussion - perhaps we can reopen if someone has more ideas how to move forward
