### ISSUE TITLE
[BUG]: DataFrame index date won't be materialized correct

### ISSUE THREAD

**Issue by comnGuy** [zenml-io/zenml#1182]
### System Information

ZenML version: 0.30.0
Install path: D:\Git\create-videos\venv\Lib\site-packages\zenml
Python version: 3.9.13
Platform information: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.22621', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 'Multiprocessor Free'}
Environment: native
Integrations: ['pillow']

### What happened?

I currently testing ZENML steps. I wanted to give my dataframe from step_1 to step_2, which is working. But when I have a 

```
@step
def step_1(data: pd.DataFrame) -> Output(data=pd.DataFrame):
    ...
    pd.index = pd.to_datetime(pd.index, format='%Y-%m-%d')
    print(pd.index)
    return data
```

```
@step
def step_2(data: pd.DataFrame) -> Output(data=pd.DataFrame):
    ...
    print(data.index)
    return data
```
Solution: I have to install the following packages, which is suggested by zenml `pip install pyarrow`. Is that how it should be?

### Relevant log output

```shell
DatetimeIndex(['2016-10-01', ... '2022-09-01'],
              dtype='datetime64[ns]', name='date', freq=None)
RangeIndex(start=0, stop=75, step=1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by safoinme** [comment]
@comnGuy Thank you for letting us know about a potential bug in the Dataframe materializer, can you please provide more details about the bug, as I couldn't figure out what error exactly you were having with this? is it related to `pyarrow` not being installed?

**Comment by comnGuy** [comment]
@safoinme, there was not really an error in the code. Look at step_1, there I created a pandas dataframe with an date as index, then the dataframe will be returned. After that the step_2 function get the previous defined dataframe and then the index got somehow converted into RangeIndex.
At this situation my expectation would be that I got the identical dataframe, even with index. Maybe my expectation/assumption is wrong?

**Comment by htahir1** [comment]
@comnGuy I think this is due to the fact that [here](https://github.com/zenml-io/zenml/blob/62220959ec752156ab89f1ff1c7f54c161390ed7/src/zenml/materializers/pandas_materializer.py#L141) the index is set to False so its dropped. We should remedy this asap and get it fixed in the next release.

For now, please install pyarrow and it will then be materialized correctly

**Comment by comnGuy** [comment]
Perfect! Glad that I was able to help. <3

**Comment by AlexejPenner** [comment]
@comnGuy I believe we fixed this in this [PR](https://github.com/zenml-io/zenml/pull/1193). I would close this Issue with the assumption that it is fixed for you as well. Feel free to reopen if this is not the case.
