### ISSUE TITLE
[BUG]: UnicodeEncodeError: 'charmap' codec can't encode character '\u280f' in position 0: character maps to <undefined>

### ISSUE THREAD

**Issue by Rishav-hub** [zenml-io/zenml#1248]
### Contact Details [Optional]

9930046@gmail.com

### System Information

Install path: C:\Users\paulb\anaconda3\envs\zenml\Lib\site-packages\zenml
Python version: 3.8.16
Platform information: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.22000', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 'Multiprocessor Free'}
Environment: native
Integrations: ['evidently', 'mlflow', 'plotly', 'scipy', 'sklearn']

### What happened?

I am running the quickstart notebook mentioned [here](https://github.com/zenml-io/zenml/tree/main/examples/quickstart).

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav-hub** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/57321948/213978203-676e949f-081e-496e-b9ce-fc69e880ab72.png">

**Comment by htahir1** [comment]
@Rishav-hub Thanks for reporting the issue. I am unable to replicate it. Maybe you can try to delete that IPyton.Application.instance() line from the code? That line simply restarts the Kernel, so you can do that manually
