### ISSUE TITLE
[BUG]: zenML does not deploy on a given ip address

### ISSUE THREAD

**Issue by mushfiqulIslam** [zenml-io/zenml#1281]
### System Information

ZenML version: 0.31.0
Install path: /home/mushfiq/Projects/zenml-test/venv/lib/python3.8/site-packages/zenml
Python version: 3.8.13
Platform information: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '22.04'}
Environment: native
Integrations: ['mlflow', 'plotly', 'scipy', 'sklearn', 'tensorboard', 'tensorflow']

### What happened?

Command: zenml up --ip-address 192.168.0.1

### Reproduction steps

1. zenml up --ip-address zenml 192.168.0.1

### Relevant log output

```shell
Deploying a local ZenML server with name 'local'.
Connecting ZenML to the 'local' local ZenML server (http://127.0.0.1:8237).
Updated the global store configuration.
Connected ZenML to the 'local' local ZenML server (http://127.0.0.1:8237).
The local ZenML dashboard is available at 'http://127.0.0.1:8237'. You can connect to it using the 'default' username and an empty password. To open the dashboard in a browser automatically, set the env variable 
AUTO_OPEN_DASHBOARD=true.
Automatically opening the dashboard in your browser. To disable this, set the env variable AUTO_OPEN_DASHBOARD=false.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
Thank you for filing this issue @mushfiqulIslam ! I can confirm your findings, this is indeed a regression bug that needs fixing.

**Comment by stefannica** [comment]
Should be fixed in the next release.
