### ISSUE TITLE
[BUG]: ZenML Quickstart.ipynb, "'model_deployer': list index out of range"

### ISSUE THREAD

**Issue by ImmanuelXIV** [zenml-io/zenml#1295]
### System Information

When following the Google Colab "ZenML Quickstart.ipynb" tutorial step-by-step, in the part "Run ZenML Pipelines" I get the following error. My system information shouldn't matter because of colab environment.

The cell that's not executing properly:

`training_pipeline(
    training_data_loader=training_data_loader(),
    trainer=svc_trainer_mlflow(),
    evaluator=evaluator(),
    deployment_trigger=deployment_trigger(),
    model_deployer=mlflow_model_deployer_step(),
).run()`
  

Error:

`Running pipeline training_pipeline on stack quickstart_stack (caching disabled)
Step training_data_loader has started.
Step training_data_loader has finished in 0.780s.
Step trainer has started.
Train accuracy: 0.925
Step trainer has finished in 3.379s.
Step evaluator has started.
2023/02/07 10:49:08 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: Run '003bce5728a44d94ae786ed7d2dd8ed5' not found
Test accuracy: 0.9666666666666667
Step evaluator has finished in 0.156s.
Step deployment_trigger has started.
Step deployment_trigger has finished in 0.117s.
Step model_deployer has started.
Extracting step run metadata failed for component 'mlflow_deployer' of type 'model_deployer': list index out of range
Failed to run step model_deployer.
Pipeline run training_pipeline-2023_02_07-10_49_03_506170 failed.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-15-3f489153a840>:1 in <module>                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/pipelines/base_pipeline.py:586 in run               │
│                                                                                                  │
│   583 │   │   │   # unexpected behavior                                                          │
│   584 │   │   │   constants.SHOULD_PREVENT_PIPELINE_EXECUTION = True                             │
│   585 │   │   │   try:                                                                           │
│ ❱ 586 │   │   │   │   return_value = stack.deploy_pipeline(pipeline_deployment)                  │
│   587 │   │   │   finally:                                                                       │
│   588 │   │   │   │   constants.SHOULD_PREVENT_PIPELINE_EXECUTION = False                        │
│   589                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/stack/stack.py:793 in deploy_pipeline               │
│                                                                                                  │
│   790 │   │   Returns:                                                                           │
│   791 │   │   │   The return value of the call to `orchestrator.run_pipeline(...)`.              │
│   792 │   │   """                                                                                │
│ ❱ 793 │   │   return self.orchestrator.run(deployment=deployment, stack=self)                    │
│   794 │                                                                                          │
│   795 │   def _get_active_components_for_step(                                                   │
│   796 │   │   self, step_config: "StepConfiguration"                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/base_orchestrator.py:154 in run       │
│                                                                                                  │
│   151 │   │   """                                                                                │
│   152 │   │   self._prepare_run(deployment=deployment)                                           │
│   153 │   │   try:                                                                               │
│ ❱ 154 │   │   │   result = self.prepare_or_run_pipeline(                                         │
│   155 │   │   │   │   deployment=deployment, stack=stack                                         │
│   156 │   │   │   )                                                                              │
│   157 │   │   finally:                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/local/local_orchestrator.py:77 in     │
│ prepare_or_run_pipeline                                                                          │
│                                                                                                  │
│    74 │   │   │   │   │   step.config.name,                                                      │
│    75 │   │   │   │   )                                                                          │
│    76 │   │   │                                                                                  │
│ ❱  77 │   │   │   self.run_step(                                                                 │
│    78 │   │   │   │   step=step,                                                                 │
│    79 │   │   │   )                                                                              │
│    80                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/base_orchestrator.py:174 in run_step  │
│                                                                                                  │
│   171 │   │   │   step=step,                                                                     │
│   172 │   │   │   orchestrator_run_id=self.get_orchestrator_run_id(),                            │
│   173 │   │   )                                                                                  │
│ ❱ 174 │   │   launcher.launch()                                                                  │
│   175 │                                                                                          │
│   176 │   @staticmethod                                                                          │
│   177 │   def requires_resources_in_orchestration_environment(                                   │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/step_launcher.py:186 in launch        │
│                                                                                                  │
│   183 │   │   │                                                                                  │
│   184 │   │   │   if execution_needed:                                                           │
│   185 │   │   │   │   try:                                                                       │
│ ❱ 186 │   │   │   │   │   self._run_step(                                                        │
│   187 │   │   │   │   │   │   pipeline_run=pipeline_run,                                         │
│   188 │   │   │   │   │   │   step_run=step_run_response,                                        │
│   189 │   │   │   │   │   )                                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/step_launcher.py:355 in _run_step     │
│                                                                                                  │
│   352 │   │   │   │   │   step_run_info=step_run_info,                                           │
│   353 │   │   │   │   )                                                                          │
│   354 │   │   │   else:                                                                          │
│ ❱ 355 │   │   │   │   self._run_step_without_step_operator(                                      │
│   356 │   │   │   │   │   step_run_info=step_run_info,                                           │
│   357 │   │   │   │   │   input_artifacts=step_run.input_artifacts,                              │
│   358 │   │   │   │   │   output_artifact_uris=output_artifact_uris,                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/step_launcher.py:422 in               │
│ _run_step_without_step_operator                                                                  │
│                                                                                                  │
│   419 │   │   │   output_artifact_uris: The output artifact URIs of the current step.            │
│   420 │   │   """                                                                                │
│   421 │   │   runner = StepRunner(step=self._step, stack=self._stack)                            │
│ ❱ 422 │   │   runner.run(                                                                        │
│   423 │   │   │   input_artifacts=input_artifacts,                                               │
│   424 │   │   │   output_artifact_uris=output_artifact_uris,                                     │
│   425 │   │   │   step_run_info=step_run_info,                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/orchestrators/step_runner.py:120 in run             │
│                                                                                                  │
│   117 │   │   │   self._stack.prepare_step_run(info=step_run_info)                               │
│   118 │   │   │   step_failed = False                                                            │
│   119 │   │   │   try:                                                                           │
│ ❱ 120 │   │   │   │   return_values = step_entrypoint(**function_params)                         │
│   121 │   │   │   except:  # noqa: E722                                                          │
│   122 │   │   │   │   step_failed = True                                                         │
│   123 │   │   │   │   raise                                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/integrations/mlflow/steps/mlflow_deployer.py:193 in │
│ mlflow_model_deployer_step                                                                       │
│                                                                                                  │
│   190 │   # create a new model deployment and replace an old one if it exists                    │
│   191 │   new_service = cast(                                                                    │
│   192 │   │   MLFlowDeploymentService,                                                           │
│ ❱ 193 │   │   model_deployer.deploy_model(                                                       │
│   194 │   │   │   replace=True,                                                                  │
│   195 │   │   │   config=predictor_cfg,                                                          │
│   196 │   │   │   timeout=params.timeout,                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/integrations/mlflow/model_deployers/mlflow_model_de │
│ ployer.py:189 in deploy_model                                                                    │
│                                                                                                  │
│   186 │   │   │   │   try:                                                                       │
│   187 │   │   │   │   │   # delete the older services and don't wait for them to                 │
│   188 │   │   │   │   │   # be deprovisioned                                                     │
│ ❱ 189 │   │   │   │   │   self._clean_up_existing_service(                                       │
│   190 │   │   │   │   │   │   existing_service=cast(                                             │
│   191 │   │   │   │   │   │   │   MLFlowDeploymentService, existing_service                      │
│   192 │   │   │   │   │   │   ),                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/integrations/mlflow/model_deployers/mlflow_model_de │
│ ployer.py:223 in _clean_up_existing_service                                                      │
│                                                                                                  │
│   220 │   │   existing_service: MLFlowDeploymentService,                                         │
│   221 │   ) -> None:                                                                             │
│   222 │   │   # stop the older service                                                           │
│ ❱ 223 │   │   existing_service.stop(timeout=timeout, force=force)                                │
│   224 │   │                                                                                      │
│   225 │   │   # delete the old configuration file                                                │
│   226 │   │   if existing_service.status.runtime_path:                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/service.py:414 in stop                     │
│                                                                                                  │
│   411 │   │   │   self.admin_state = ServiceState.INACTIVE                                       │
│   412 │   │   │   self.deprovision(force)                                                        │
│   413 │   │   │   if timeout > 0:                                                                │
│ ❱ 414 │   │   │   │   self.poll_service_status(timeout)                                          │
│   415 │   │   │   │   if not self.is_stopped:                                                    │
│   416 │   │   │   │   │   raise RuntimeError(                                                    │
│   417 │   │   │   │   │   │   f"Failed to stop service {self}. Last state: "                     │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/service.py:283 in poll_service_status      │
│                                                                                                  │
│   280 │   │   while True:                                                                        │
│   281 │   │   │   if self.admin_state == ServiceState.ACTIVE and self.is_running:                │
│   282 │   │   │   │   return True                                                                │
│ ❱ 283 │   │   │   if self.admin_state == ServiceState.INACTIVE and self.is_stopped:              │
│   284 │   │   │   │   return True                                                                │
│   285 │   │   │   if self.is_failed:                                                             │
│   286 │   │   │   │   return False                                                               │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/service.py:327 in is_stopped               │
│                                                                                                  │
│   324 │   │   Returns:                                                                           │
│   325 │   │   │   True if the service is stopped, otherwise False.                               │
│   326 │   │   """                                                                                │
│ ❱ 327 │   │   self.update_status()                                                               │
│   328 │   │   return self.status.state == ServiceState.INACTIVE                                  │
│   329 │                                                                                          │
│   330 │   @property                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/service.py:235 in update_status            │
│                                                                                                  │
│   232 │   │   │   "Running status check for service '%s' ...",                                   │
│   233 │   │   │   self,                                                                          │
│   234 │   │   )                                                                                  │
│ ❱ 235 │   │   state, err = self.check_status()                                                   │
│   236 │   │   logger.debug(                                                                      │
│   237 │   │   │   "Status check results for service '%s': %s [%s]",                              │
│   238 │   │   │   self,                                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/local/local_service.py:273 in check_status │
│                                                                                                  │
│   270 │   │   │   providing additional information about that state (e.g. a                      │
│   271 │   │   │   description of the error, if one is encountered).                              │
│   272 │   │   """                                                                                │
│ ❱ 273 │   │   if not self.status.pid:                                                            │
│   274 │   │   │   return ServiceState.INACTIVE, "service daemon is not running"                  │
│   275 │   │                                                                                      │
│   276 │   │   # the daemon is running                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/zenml/services/local/local_service.py:170 in pid          │
│                                                                                                  │
│   167 │   │   │   │   │   daemon_entrypoint.__name__ not in cmd_line                             │
│   168 │   │   │   │   │   or config_file not in cmd_line                                         │
│   169 │   │   │   │   ) and (                                                                    │
│ ❱ 170 │   │   │   │   │   daemon_entrypoint.__name__ not in cmd_line[0]                          │
│   171 │   │   │   │   │   or config_file not in cmd_line[0]                                      │
│   172 │   │   │   │   ):                                                                         │
│   173 │   │   │   │   │   logger.debug(                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range`

### What happened?

I'd expect the Quickstart.ipynb to run smoothly through the tutorial.

### Reproduction steps

1. Click on this [link](https://colab.research.google.com/github/zenml-io/zenml/blob/main/examples/quickstart/notebooks/quickstart.ipynb)
2. Follow the tutorial step-by-step
3. It'll likely throw an error as described above
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Thanks for the report. The trouble was causes with  the timeout (10 secs is too low apparently). We now increased to 60 seconds in #1296 and it should work!
