### ISSUE TITLE
[DOC] Mistake in centralized secrets management documentation

### ISSUE THREAD

**Issue by vidarrio** [zenml-io/zenml#1354]
## Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General

The centralized secrets management documentation for creating / registering a new secret is wrong. The command that works is `zenml secret create` but the one shown in the documentation is `zenml secret register`. 

The documentation refers to it as registering a secret throughout, so it's probably a good idea to either change the command to `zenml secret register`, or to change the documentation to bring it in line with the command and refer to it as _creating_ a secret instead.

**Comment by strickvl** [comment]
Thanks for this, @luckri13. I've made a fix for the docs as you rightly note that the command mentioned is the wrong one.
