### ISSUE TITLE
[BUG]: Unable to setup kubeflow example

### ISSUE THREAD

**Issue by niccle27** [zenml-io/zenml#1433]
### Contact Details [Optional]

nicolas@multitel.be

### System Information

zenml version: 0.36.0
k3d version v5.4.8
k3s version v1.25.6-k3s1 (default)
ubuntu 20.04 with kernel 5.14
Docker version 20.10.17
kubectl v1.26.2

### What happened?

This is tricky to explain as i am just not getting much logs. While given the update on the recipe readme i manage to execute the k3d-modular successfully. Using k9s, i realized that pods are getting in error state after a few minutes. It made it impossible to run the example `run-kubeflow.py` written in the walkthrough notebook example.

I am using k9s in order to monitor them.

![2023-03-22-11:44:27_crashing](https://user-images.githubusercontent.com/28828886/226882407-31a78a57-6bff-449c-b458-428ebb74acb3.png)
![2023-03-22-11:45:54_EOF](https://user-images.githubusercontent.com/28828886/226882418-97c4fde2-decb-4ac3-a591-250e73916500.png)

As shown in the screenshot, most of the pods aren't giving me any logs. i still managed to get this from the proxy agent
``` +++ dirname /opt/proxy/attempt-register-vm-on-proxy.sh                                                                                                                    │
│ ++ cd /opt/proxy                                                                                                                                                          │
│ ++ pwd                                                                                                                                                                    │
│ + DIR=/opt/proxy                                                                                                                                                          │
│ ++ kubectl get configmap inverse-proxy-config -o json                                                                                                                     │
│ ++ jq -r '.data.Hostname // empty'                                                                                                                                        │
│ + HOSTNAME=                                                                                                                                                               │
│ + [[ -n '' ]]                                                                                                                                                             │
│ + [[ ! -z '' ]]                                                                                                                                                           │
│ ++ curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google'                                                                     │
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                           │
│                                  Dload  Upload   Total   Spent    Left  Speed                                                                                             │
│   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0     │
│ + INSTANCE_ZONE=/                                                                                                                                                         │
│ Stream closed EOF for kubeflow/proxy-agent-7fd694f7c5-wcdgq (proxy-agent) 
```

### Reproduction steps

1. Ensuring clean basis
    ``` bash
    # Ensuring a clean environment
    k3d cluster list # return empty
    zenml clean
    zenml example pull kubeflow_pipelines_orchestration
    cd zenml_examples/kubeflow_pipelines_orchestration 
    zenml stack recipe pull k3d-modular
    # stopping any remaining docker registry running on port 5001
    ```

2. I updated the zenml version in `k3d-modular/variables.tf`
``` hcl
variable "zenml-version" {
	description = "The version of ZenML being used"
	default = "0.36.0"
	type = string
}
```
3. Running deploy command:
```
zenml stack recipe deploy k3d-modular -i kubeflow -i minio --no-server

The procedure finish successfuly with:
``` text
A stack configuration YAML file has been generated as part of the deployment of the k3d-modular recipe. Find it at /home/imagedpt/Documents/Projects/4@Projects/TEF/Experiments/ZenML/Kubeflow_zenml_036/zenml_examples/kubeflow_pipelines_orchestration/zenml_stack_recipes/k3d-modular/k3d_stack_2023-03-22T10_21.yaml.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by safoinme** [comment]
Hey, @niccle27 is the only pod failing to start the `proxy-agent-... because screenshots show them as running?

**Comment by niccle27** [comment]
Eventually they all fail, here is a screenshot while i left the cluster running for some time.
![2023-03-22-13:11:59_all_fail](https://user-images.githubusercontent.com/28828886/226901768-fcb9b876-74b7-4f52-85ea-1fb168797864.png)

**Comment by safoinme** [comment]
May I ask you to check how much memory and storage is left on your machine? I used to have the same problem due to not having enough space.

**Comment by niccle27** [comment]
In order to close door, i decided to start fresh on ubuntu 22 and fully reset my laptop. After running over the different steps i manage do get the cluster running. I suppose we can consider that this could be linked to the storage not being sufficient. The `run-kubeflow.py` still do not work though. I am getting the following error. 
![2023-03-23-09:59:44_failed_establish](https://user-images.githubusercontent.com/28828886/227154586-223c5058-5054-4b04-8b94-5a7f87348b34.png)

I have tried the following fix:
 - ran zenml up --ip 0.0.0.0
 - ran zenml disconnect then zenml up
 - 
Issue seem to remain the same. Do you have any idea where it comes from ? Thank you a lot in advance !
