### ISSUE TITLE
Is there any way to add auth0 authentication provider in Zenml Helm Chart.

### ISSUE THREAD

**Issue by Sarvjeet-Jain** [zenml-io/zenml#1436]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General

If applicable, please enter the output of `python -c "import zenml.environment; print(zenml.environment.get_system_details())"`:
```
...
```

```py
import zenml

...
```

**Comment by htahir1** [comment]
This is quite a big feature that we don't plan to work on any time soon unfortuantely. If you require OAuth then consider the ZenML enterprise version (I know it isnt the best answer but we have to prioritize): https://zenml.io/enterprise
