### ISSUE TITLE
[DISCUSSION] How to perform a join of multiple dataframes (variable length)

### ISSUE THREAD

**Issue by chris-fj** [zenml-io/zenml#1440]
## Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://docs.zenml.io/) ~and still think this is a bug~ (not a bug)

Discussion thread because I don't have slack and the roadmap boards don't seem a good fit for this. In my data processing pipelines I often run into the need of joining dataframes. Every pipeline has a distinct number of dataframes, so I can't hardcode the input dataframes as input arguments.

## What I have tried:
- Create a list of `DataFrame`s to pass them as the input of the join step and iterate through them with `reduce`: doesn't work because the inputs of a step must be the outputs of previous steps. Since this list is not the output of any step, this fails
- Create the list in runtime and add it as a parameter of a single Join step: doesn't work because the `__call__` method returns `_OutputParameters` instead of `DataFrame` (and `_OutputParameters` class does not have the same methods as `DataFrame`, neither the actual `DataFrame`)
- Retrieve the outputs inside the Join Step and join them: I haven't found a way of getting the output of a pipeline step within said pipeline. 
- Reuse the step: ZenML currently forbids calling a step more than once 
- Create the Join steps inside the `reduce` (one for each iteration): Doesn't work because the newly created steps do not belong to the pipeline
- Clone the step already inside the pipeline: This option was recently deleted

Ideally, I would have a reusable step across all my pipelines that takes a list and joins them via `reduce`. Initially assume that all `DataFrame`s are to be joined on the same `on` columns and with the same `how` method and this is for `Spark` `DataFrames`, though I think a solution can be easily extrapolated to ~pandas~. 

**How can achieve something similar in an elegant manner within the limitations of ZenML (steps can't be reused, inputs of a step must be outputs of another step, ...)?**

**Comment by htahir1** [comment]
@schustmi It looks like your new pipeline API might help here. I can definitely see that with the current limitations this is hard

**Comment by chris-fj** [comment]
Hello, @schustmi, thank for your reply and sorry for replying late. Let me check the example of gathering multiple steps into another, that seems to be what I want to do and I'll let you know. Thank you both for your insights!
