### ISSUE TITLE
[BUG]: 404 Not Found when trying to register stack components via UI

### ISSUE THREAD

**Issue by christianversloot** [zenml-io/zenml#1475]
### System Information

(Sharing the relevant aspects only because the command provides info about our setup)

ZENML_LOCAL_VERSION: 0.37.0
ZENML_SERVER_VERSION: 0.37.0

### What happened?

I am trying to add MLFlow visually via the components screen in the ZenML UI. Note that it was deployed locally. It's throwing a 404 however:

![image](https://user-images.githubusercontent.com/6450612/230438809-ed3018ca-3c05-40dc-a1f9-cba744c3e04d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexejPenner** [comment]
Thank you so much for raising this issue - this was caused due to some issues in our last release where the API docs did not build properly. We have fixed this issue - this should no longer happen in the dashboard. I would close it, but feel free to reopen if there are still issues around this.

**Comment by christianversloot** [comment]
Docs are working again - thanks for the quick response!
