### ISSUE TITLE
[BUG]: Error when executing pipeline steps in Jupyter Notebooks

### ISSUE THREAD

**Issue by juanjucm** [zenml-io/zenml#1479]
### Contact Details [Optional]

jjceamoran@gmail.com

### System Information

Running without an active repository root.
ZENML_LOCAL_VERSION: 0.37.0
ZENML_SERVER_VERSION: 0.37.0
ZENML_SERVER_DATABASE: sqlite
ZENML_SERVER_DEPLOYMENT_TYPE: local
ZENML_CONFIG_DIR: /Users/jceamoran/Library/Application Support/zenml
ZENML_LOCAL_STORE_DIR: /Users/jceamoran/Library/Application Support/zenml/local_stores
ZENML_SERVER_URL: http://127.0.0.1:8237
ZENML_ACTIVE_REPOSITORY_ROOT: None
PYTHON_VERSION: 3.9.6
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'mac', 'mac_version': '13.3'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: default
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: e467e1b5-f453-4d7f-a469-9d9a0935562b
ANALYTICS_USER_ID: 1717617a-9515-4a90-aec3-5a4e4f299871
ANALYTICS_SERVER_ID: e467e1b5-f453-4d7f-a469-9d9a0935562b
INTEGRATIONS: ['evidently', 'kaniko', 'mlflow', 'pillow', 'plotly', 'scipy', 'sklearn']
PACKAGES: {'zope.interface': '6.0', 'zope.event': '4.6', 'zipp': '3.15.0', 'zenml': 
'0.37.0', 'yarl': '1.8.2', 'widgetsnbextension': '3.6.4', 'werkzeug': '2.2.3', 'websockets':
'11.0.1', 'websocket-client': '1.5.1', 'webencodings': '0.5.1', 'webcolors': '1.13', 
'wcwidth': '0.2.6', 'watchgod': '0.8.2', 'validators': '0.18.2', 'uvloop': '0.17.0', 
'uvicorn': '0.17.6', 'urllib3': '1.26.15', 'uri-template': '1.2.0', 'tzdata': '2023.3', 
'typing-extensions': '4.5.0', 'tritonclient': '2.32.0', 'traitlets': '5.9.0', 'tqdm': 
'4.65.0', 'tornado': '6.2', 'tinycss2': '1.2.1', 'threadpoolctl': '3.1.0', 'terminado': 
'0.17.1', 'tenacity': '8.2.2', 'tabulate': '0.9.0', 'statsmodels': '0.13.5', 'starlette': 
'0.17.1', 'starlette-exporter': '0.15.1', 'stack-data': '0.6.2', 'sqlparse': '0.4.3', 
'sqlmodel': '0.0.8', 'sqlalchemy2-stubs': '0.0.2a33', 'sqlalchemy': '1.4.41', 
'sqlalchemy-utils': '0.38.3', 'soupsieve': '2.4', 'sniffio': '1.3.0', 'smmap': '5.0.0', 
'slicer': '0.0.7', 'six': '1.16.0', 'shap': '0.41.0', 'setuptools': '58.0.4', 'send2trash': 
'1.8.0', 'scipy': '1.10.1', 'scikit-learn': '1.2.2', 'rsa': '4.9', 'rich': '12.6.0', 
'rfc3986-validator': '0.1.1', 'rfc3339-validator': '0.1.4', 'requests': '2.28.2', 'regex': 
'2023.3.23', 'querystring-parser': '1.2.4', 'pyzmq': '25.0.2', 'pyyaml': '5.4.1', 'pytz': 
'2022.7.1', 'python-terraform': '0.10.1', 'python-rapidjson': '1.10', 'python-multipart': 
'0.0.6', 'python-json-logger': '2.0.7', 'python-jose': '3.3.0', 'python-dotenv': '1.0.0', 
'python-dateutil': '2.8.2', 'pyrsistent': '0.19.3', 'pyparsing': '2.4.2', 'pymysql': 
'1.0.3', 'pyjwt': '2.6.0', 'pygments': '2.14.0', 'pydantic': '1.10.7', 'pycparser': '2.21', 
'pyasn1': '0.4.8', 'pyarrow': '11.0.0', 'py-grpc-prometheus': '0.7.0', 'pure-eval': '0.2.2',
'ptyprocess': '0.7.0', 'psutil': '5.9.4', 'protobuf': '4.22.1', 'prompt-toolkit': '3.0.38', 
'prometheus-client': '0.16.0', 'plotly': '5.14.1', 'platformdirs': '3.2.0', 'pip': '21.2.4',
'pillow': '9.5.0', 'pickleshare': '0.7.5', 'pexpect': '4.8.0', 'patsy': '0.5.3', 'passlib': 
'1.7.4', 'parso': '0.8.3', 'pandocfilters': '1.5.0', 'pandas': '2.0.0', 'packaging': '23.0',
'orjson': '3.8.10', 'oauthlib': '3.2.2', 'numpy': '1.23.5', 'numba': '0.56.4', 'notebook': 
'6.5.4', 'notebook-shim': '0.2.2', 'nltk': '3.8.1', 'nest-asyncio': '1.5.6', 'nbformat': 
'5.8.0', 'nbconvert': '7.3.0', 'nbclient': '0.7.3', 'nbclassic': '0.5.5', 'multidict': 
'6.0.4', 'monotonic': '1.6', 'mlserver': '1.2.4', 'mlserver-mlflow': '1.2.4', 'mlflow': 
'2.2.2', 'mistune': '2.0.5', 'matplotlib': '3.7.1', 'matplotlib-inline': '0.1.6', 
'markupsafe': '2.1.2', 'markdown': '3.4.3', 'mako': '1.2.4', 'llvmlite': '0.39.1', 
'kiwisolver': '1.4.4', 'kafka-python': '2.0.2', 'jupyterlab-widgets': '1.1.4', 
'jupyterlab-pygments': '0.2.2', 'jupyter-server': '2.5.0', 'jupyter-server-terminals': 
'0.4.4', 'jupyter-events': '0.6.3', 'jupyter-core': '5.3.0', 'jupyter-client': '8.1.0', 
'jsonschema': '4.17.3', 'jsonpointer': '2.3', 'joblib': '1.2.0', 'jinja2': '3.1.2', 'jedi': 
'0.18.2', 'itsdangerous': '2.1.2', 'isoduration': '20.11.0', 'ipywidgets': '7.7.5', 
'ipython': '8.12.0', 'ipython-genutils': '0.2.0', 'ipykernel': '6.22.0', 
'importlib-resources': '5.12.0', 'importlib-metadata': '6.3.0', 'idna': '3.4', 'httptools': 
'0.5.0', 'httplib2': '0.19.1', 'h11': '0.14.0', 'gunicorn': '20.1.0', 'grpcio': '1.53.0', 
'greenlet': '2.0.2', 'gitpython': '3.1.31', 'gitdb': '4.0.10', 'geventhttpclient': '2.0.2', 
'gevent': '22.10.2', 'frozenlist': '1.3.3', 'fqdn': '1.5.1', 'fonttools': '4.39.3', 'flask':
'2.2.3', 'fastjsonschema': '2.16.3', 'fastapi': '0.75.2', 'fastapi-utils': '0.2.1', 
'executing': '1.2.0', 'evidently': '0.2.2', 'entrypoints': '0.4', 'ecdsa': '0.18.0', 
'docker': '6.0.1', 'distro': '1.8.0', 'defusedxml': '0.7.1', 'decorator': '5.1.1', 
'debugpy': '1.6.7', 'databricks-cli': '0.17.6', 'cycler': '0.11.0', 'cryptography': 
'40.0.1', 'contourpy': '1.0.7', 'commonmark': '0.9.1', 'comm': '0.1.3', 'cloudpickle': 
'2.2.1', 'click': '8.1.3', 'click-params': '0.3.0', 'charset-normalizer': '3.1.0', 'cffi': 
'1.15.1', 'certifi': '2022.12.7', 'brotli': '1.0.9', 'bleach': '6.0.0', 'beautifulsoup4': 
'4.12.2', 'bcrypt': '4.0.1', 'backoff': '1.10.0', 'backcall': '0.2.0', 'attrs': '22.2.0', 
'async-timeout': '4.0.2', 'asttokens': '2.2.1', 'asgiref': '3.6.0', 'arrow': '1.2.3', 
'argon2-cffi': '21.3.0', 'argon2-cffi-bindings': '21.2.0', 'appnope': '0.1.3', 'anyio': 
'3.6.2', 'analytics-python': '1.4.post1', 'alembic': '1.8.1', 'aiosignal': '1.3.1', 
'aiokafka': '0.8.0', 'aiohttp': '3.8.4', 'aiofiles': '23.1.0'}

CURRENT STACK

Name: default
ID: 63792284-0110-472e-ae11-d50ce66c5a2b
Shared: No
User: default / 1717617a-9515-4a90-aec3-5a4e4f299871
Workspace: default / 42349e18-1b72-4019-91b4-1a06b85c7626

ORCHESTRATOR: default

Name: default
ID: 2da80ea5-0c5a-4a6d-ab6c-8473d74a77a5
Type: orchestrator
Flavor: local
Configuration: {}
Shared: No
User: default / 1717617a-9515-4a90-aec3-5a4e4f299871
Workspace: default / 42349e18-1b72-4019-91b4-1a06b85c7626

ARTIFACT_STORE: default

Name: default
ID: 518e7acc-fc65-4f6e-b1bb-ef224dc1fc80
Type: artifact_store
Flavor: local
Configuration: {'path': ''}
Shared: No
User: default / 1717617a-9515-4a90-aec3-5a4e4f299871
Workspace: default / 42349e18-1b72-4019-91b4-1a06b85c7626

### What happened?

There is a error happening if you try to run a pipeline with a set of steps coded in a jupyter notebook. The pipeline doesn't run correctly unless you code the steps in a separate `.py` file. Due to this error, all jupyter notebook examples and tutorials fail when executing.

Error: **_Unable to resolve module `<module '__main__'>` because it was not loaded from a file._**

### Reproduction steps

This error has been caught when trying to run [quickstart](https://github.com/zenml-io/zenml/tree/main/examples/quickstart) notebooks (after executing `zenml go`). It also happens with [zenbytes](https://github.com/zenml-io/zenbytes) examples.

zenml and zenml-server installation process has been done as explained in the documenation.

### Relevant log output

```shell
/var/folders/pm/10vrlkjs7l7fc1m9zhbzcf6h0000gq/T/ipykernel_96532/86626121.py:1 in <module>       │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/var/folders/pm/10vrlkjs7l7fc1m9zhbzcf6h0000gq/T/ipykernel_96532/86626121.py'                   │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/pipelines/base_pi │
│ peline.py:472 in run                                                                             │
│                                                                                                  │
│    469 │   │   with event_handler(                                                               │
│    470 │   │   │   event=AnalyticsEvent.RUN_PIPELINE, v2=True                                    │
│    471 │   │   ) as analytics_handler:                                                           │
│ ❱  472 │   │   │   deployment, pipeline_spec, schedule, build = self._compile(                   │
│    473 │   │   │   │   config_path=config_path,                                                  │
│    474 │   │   │   │   run_name=run_name,                                                        │
│    475 │   │   │   │   enable_cache=enable_cache,                                                │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/pipelines/base_pi │
│ peline.py:1034 in _compile                                                                       │
│                                                                                                  │
│   1031 │   │   # Update with the values in code so they take precedence                          │
│   1032 │   │   run_config = pydantic_utils.update_model(run_config, update=update)               │
│   1033 │   │                                                                                     │
│ ❱ 1034 │   │   deployment, pipeline_spec = Compiler().compile(                                   │
│   1035 │   │   │   pipeline=self,                                                                │
│   1036 │   │   │   stack=Client().active_stack,                                                  │
│   1037 │   │   │   run_configuration=run_config,                                                 │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/config/compiler.p │
│ y:92 in compile                                                                                  │
│                                                                                                  │
│    89 │   │   │   if ConfigurationLevel.STEP in settings.LEVEL                                   │
│    90 │   │   }                                                                                  │
│    91 │   │                                                                                      │
│ ❱  92 │   │   steps = {                                                                          │
│    93 │   │   │   name: self._compile_step(                                                      │
│    94 │   │   │   │   pipeline_parameter_name=name,                                              │
│    95 │   │   │   │   step=step,                                                                 │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/config/compiler.p │
│ y:93 in <dictcomp>                                                                               │
│                                                                                                  │
│    90 │   │   }                                                                                  │
│    91 │   │                                                                                      │
│    92 │   │   steps = {                                                                          │
│ ❱  93 │   │   │   name: self._compile_step(                                                      │
│    94 │   │   │   │   pipeline_parameter_name=name,                                              │
│    95 │   │   │   │   step=step,                                                                 │
│    96 │   │   │   │   pipeline_settings=settings_to_passdown,                                    │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/config/compiler.p │
│ y:386 in _compile_step                                                                           │
│                                                                                                  │
│   383 │   │   Returns:                                                                           │
│   384 │   │   │   The compiled step.                                                             │
│   385 │   │   """                                                                                │
│ ❱ 386 │   │   step_spec = self._get_step_spec(                                                   │
│   387 │   │   │   pipeline_parameter_name=pipeline_parameter_name, step=step                     │
│   388 │   │   )                                                                                  │
│   389 │   │   step_settings = self._filter_and_validate_settings(                                │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/config/compiler.p │
│ y:355 in _get_step_spec                                                                          │
│                                                                                                  │
│   352 │   │   │   The step spec.                                                                 │
│   353 │   │   """                                                                                │
│   354 │   │   return StepSpec(                                                                   │
│ ❱ 355 │   │   │   source=source_utils.resolve(step.__class__),                                   │
│   356 │   │   │   upstream_steps=sorted(step.upstream_steps),                                    │
│   357 │   │   │   inputs=step.inputs,                                                            │
│   358 │   │   │   pipeline_parameter_name=pipeline_parameter_name,                               │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/utils/source_util │
│ s.py:137 in resolve                                                                              │
│                                                                                                  │
│   134 │                                                                                          │
│   135 │   module_name = module.__name__                                                          │
│   136 │   if module_name == "__main__":                                                          │
│ ❱ 137 │   │   module_name = _resolve_module(module)                                              │
│   138 │                                                                                          │
│   139 │   source_type = get_source_type(module=module)                                           │
│   140                                                                                            │
│                                                                                                  │
│ /Users/jceamoran/Desktop/projects/test/zenml/lib/python3.9/site-packages/zenml/utils/source_util │
│ s.py:518 in _resolve_module                                                                      │
│                                                                                                  │
│   515 │   """                                                                                    │
│   516 │   if not hasattr(module, "__file__") or not module.__file__:                             │
│   517 │   │   if module.__name__ == "__main__":                                                  │
│ ❱ 518 │   │   │   raise RuntimeError(                                                            │
│   519 │   │   │   │   f"Unable to resolve module `{module}` because it was "                     │
│   520 │   │   │   │   "not loaded from a file."                                                  │
│   521 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Unable to resolve module `<module '__main__'>` because it was not loaded from a file.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Fixed in latest release!
