### ISSUE TITLE
[BUG]: Add pessimistic MySQL disconnect handling

### ISSUE THREAD

**Issue by francoisserra** [zenml-io/zenml#1488]
### Contact Details [Optional]

francois.serra@adeo.com

### System Information

Zenml 0.36.1 + MySQL (remote)

### What happened?

After a period of inactivity, firewalls can close the network connection with the remote MySQL database (when using SQLZenStore).

SQLAlchemy offers a proper way to handle these disconnections :

https://docs.sqlalchemy.org/en/20/core/pooling.html#pool-disconnects-pessimistic

### Reproduction steps

1. Start a fresh MySQL server with docker  : `docker run --name zen-mysql -p3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:8`
2. (opt.) use a dedicated global Zebml config `export ZENML_CONFIG_PATH=~/.config/zenml-dev`
3. `export ZENML_STORE_URL=mysql://root:my-secret-pw@localhost:3306/defaultdb`
4. Start a ZenML server `zenml up`
5. Kill the MySQL connection : 
 - connect to Mysql e.g.  `mysql -h  127.0.0.1 -P 3306 -u root --password` (password is `my-secret-pw`)
 - search for the zenml connection in mysql : `SHOW PROCESSLIST;` (select the one connected to `defaultdb`)
 - kill the session using its `id` : `KILL xx ;`
6. Perform a http `GET` on the `/api/v1/info` endpoint e.g. `curl http://localhost:8237/api/v1/info`
you get an `Internal Server Error message`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
> Should be fixed by #1489

Many thanks for the fix @francoisserra !
