### ISSUE TITLE
[BUG]: SageMaker Step Operator - too long trainingJobNames

### ISSUE THREAD

**Issue by christianversloot** [zenml-io/zenml#1502]
### System Information

ZENML_LOCAL_VERSION: 0.38.0
ZENML_SERVER_VERSION: 0.38.0

### What happened?

In the case of long experiment names and step names, the `trainingJobName` as generated by ZenML when using the SageMaker Step Operator violates the <= 63 length requirement by the SageMaker Estimator:

```
ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 2 validation errors detected: Value 'basic-zenml-project-pipeline-2023-04-24-12-22-59-886794-step-show-sagemaker-s3-link' at
'trainingJobName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}; Value 'basic-zenml-project-pipeline-2023-04-24-12-22-59-886794-step-show-sagemaker-s3-link' at
'trainingJobName' failed to satisfy constraint: Member must have length less than or equal to 63
```

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christianversloot** [comment]
Multiple options:

* Remove the step name from the `trainingJobName`, so `basic-zenml-project-pipeline-2023-04-24-12-22-59-886794`.
* Cut everything at length 60, providing three dots as a suffix, so `basic-zenml-project-pipeline-2023-04-24-12-22-59-886794-step...`
* Maybe as an addition, allow people to override `info.run_name` with their custom name, combined with any of the two above. If people would get stuck by e.g. naming their pipelines wrongly, they could quickly get back to work by e.g. specifying a name themselves.

I can add this with a PR; would love to hear your thoughts re/preferred options :)

@htahir1 @schustmi @strickvl

**Comment by strickvl** [comment]
Thanks for the fix PR!
