### ISSUE TITLE
[BUG]: outdated dependency: analytics-python ^1.4.0

### ISSUE THREAD

**Issue by kler** [zenml-io/zenml#1597]
### Contact Details [Optional]

patrik.lermon@gmail.com

### System Information

zenml version 0.40.1

### What happened?

ZenML has a dependency to the stale package `analytics-python = "^1.4.0"` which seemingly is superseded by `segment-analytics-python`.

Unrolling the dependency graph eventually a hard dependency to the very old `backoff 1.10.0` is hit, and this happen to be where I run into trouble, as I want a later version of backoff.

## Summary
- The requirement is in the file https://github.com/zenml-io/zenml/blob/main/pyproject.toml
- The package `analytics-python` seems to be stale
- My impression is that it has been superseded by the package called `segment-analytics-python`

## Proof
- See https://pypi.org/project/analytics-python/ which points to https://github.com/segmentio/analytics-python
- See https://pypi.org/project/segment-analytics-python/ which points to the very same repo: https://github.com/segmentio/analytics-python
- Also compare: https://github.com/segmentio/analytics-python/tree/1.4.0 with https://github.com/segmentio/analytics-python/tree/master

## Suggested fix
Upgrade to the package called `segment-analytics-python`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@kler We will look into updating this dependency asap. Sorry for the trouble!
