### ISSUE TITLE
[BUG]: Error: no such command 'server'

### ISSUE THREAD

**Issue by lambdaofgod** [zenml-io/zenml#1646]
### System Information

ZENML_LOCAL_VERSION: 0.40.3
ZENML_SERVER_VERSION: 0.40.3
ZENML_SERVER_DATABASE: sqlite
ZENML_SERVER_DEPLOYMENT_TYPE: local
ZENML_CONFIG_DIR: <config dir>
ZENML_LOCAL_STORE_DIR: <local path>
ZENML_SERVER_URL: http://127.0.0.1:8237
ZENML_ACTIVE_REPOSITORY_ROOT: <project path>
PYTHON_VERSION: 3.10.9
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '20.04'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: default
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: 4da7e326-4e1f-466f-8b53-3ce36419e56c
ANALYTICS_USER_ID: 1f94c9b3-3ee6-47dc-95bb-7a08079c835e
ANALYTICS_SERVER_ID: 4da7e326-4e1f-466f-8b53-3ce36419e56c
INTEGRATIONS: ['kaniko']
PACKAGES: {'certifi': '2023.5.7', 'pytz': '2023.3', 'tzdata': '2023.3', 'setuptools': '65.6.3', 'cryptography': '41.0.1', 'pyzmq': '25.1.0', 'attrs': '23.1.0', 'packaging': 
'23.1', 'azure-mgmt-resource': '23.0.1', 'pip': '22.3.1', 'argon2-cffi': '21.3.0', 'argon2-cffi-bindings': '21.2.0', 'isoduration': '20.11.0', 'rich': '12.6.0', 
'websockets': '11.0.3', 'ipython': '8.14.0', 'jupyter-client': '8.2.0', 'click': '8.1.3', 'ipywidgets': '7.7.5', 'nbconvert': '7.6.0', 'overrides': '7.3.1', 'ipykernel': 
'6.23.2', 'notebook': '6.5.4', 'tornado': '6.3.2', 'docker': '6.0.1', 'bleach': '6.0.0', 'psutil': '5.9.5', 'traitlets': '5.9.0', 'nbformat': '5.9.0', 'pyyaml': '5.4.1', 
'jupyter-core': '5.3.1', 'decorator': '5.1.1', 'smmap': '5.0.0', 'jsonschema': '4.17.3', 'beautifulsoup4': '4.12.2', 'rsa': '4.9', 'pexpect': '4.8.0', 'typing-extensions': 
'4.6.3', 'gitdb': '4.0.10', 'bcrypt': '4.0.1', 'orjson': '3.8.14', 'asgiref': '3.7.2', 'platformdirs': '3.7.0', 'anyio': '3.7.0', 'widgetsnbextension': '3.6.4', 'idna': 
'3.4', 'python-jose': '3.3.0', 'gitpython': '3.1.31', 'jinja2': '3.1.2', 'charset-normalizer': '3.1.0', 'prompt-toolkit': '3.0.38', 'mistune': '3.0.1', 'requests': '2.31.0',
'pycparser': '2.21', 'fastjsonschema': '2.17.1', 'pygments': '2.15.1', 'python-dateutil': '2.8.2', 'jupyter-server': '2.6.0', 'pyparsing': '2.4.7', 'soupsieve': '2.4.1', 
'jsonpointer': '2.4', 'asttokens': '2.2.1', 'cloudpickle': '2.2.1', 'markupsafe': '2.1.3', 'python-json-logger': '2.0.7', 'urllib3': '2.0.3', 'greenlet': '2.0.2', 'pandas': 
'2.0.2', 'azure-core': '1.27.1', 'numpy': '1.25.0', 'six': '1.16.0', 'cffi': '1.15.1', 'webcolors': '1.13', 'pydantic': '1.10.9', 'backoff': '1.10.0', 'send2trash': '1.8.2',
'alembic': '1.8.1', 'distro': '1.8.0', 'passlib': '1.7.4', 'debugpy': '1.6.7', 'websocket-client': '1.6.0', 'monotonic': '1.6', 'nest-asyncio': '1.5.6', 'fqdn': '1.5.1', 
'pandocfilters': '1.5.0', 'sqlalchemy': '1.4.41', 'analytics-python': '1.4.post1', 'azure-mgmt-core': '1.4.0', 'uri-template': '1.3.0', 'sniffio': '1.3.0', 'mako': '1.2.4', 
'arrow': '1.2.3', 'tinycss2': '1.2.1', 'executing': '1.2.0', 'azure-common': '1.1.28', 'jupyterlab-widgets': '1.1.4', 'exceptiongroup': '1.1.1', 'pymysql': '1.0.3', 
'python-dotenv': '1.0.0', 'nbclassic': '1.0.0', 'fastapi': '0.75.2', 'zenml': '0.39.0', 'wheel': '0.38.4', 'sqlalchemy-utils': '0.38.3', 'pyrsistent': '0.19.3', 'httplib2': 
'0.19.1', 'jedi': '0.18.2', 'validators': '0.18.2', 'ecdsa': '0.18.0', 'uvicorn': '0.17.6', 'terminado': '0.17.1', 'starlette': '0.17.1', 'uvloop': '0.17.0', 
'prometheus-client': '0.17.0', 'h11': '0.14.0', 'python-terraform': '0.10.1', 'commonmark': '0.9.1', 'parso': '0.8.3', 'watchgod': '0.8.2', 'nbclient': '0.8.0', 
'pickleshare': '0.7.5', 'defusedxml': '0.7.1', 'ptyprocess': '0.7.0', 'jupyter-events': '0.6.3', 'stack-data': '0.6.2', 'isodate': '0.6.1', 'webencodings': '0.5.1', 
'httptools': '0.5.0', 'pyasn1': '0.5.0', 'jupyter-server-terminals': '0.4.4', 'click-params': '0.3.0', 'wcwidth': '0.2.6', 'notebook-shim': '0.2.3', 'pure-eval': '0.2.2', 
'jupyterlab-pygments': '0.2.2', 'fastapi-utils': '0.2.1', 'backcall': '0.2.0', 'ipython-genutils': '0.2.0', 'matplotlib-inline': '0.1.6', 'rfc3339-validator': '0.1.4', 
'comm': '0.1.3', 'rfc3986-validator': '0.1.1', 'sqlmodel': '0.0.8', 'python-multipart': '0.0.6', 'sqlalchemy2-stubs': '0.0.2a34'}

CURRENT STACK

Name: default
ID: 47b23749-e730-474d-bd07-929a0a185720
Shared: No
User: default / 1f94c9b3-3ee6-47dc-95bb-7a08079c835e
Workspace: default / 05cf50a0-6d85-4ccc-8002-2a26f2c3d20b

ORCHESTRATOR: default

Name: default
ID: 256e4ef8-f986-4f16-9678-52d94c15df61
Type: orchestrator
Flavor: local
Configuration: {}
Shared: No
User: default / 1f94c9b3-3ee6-47dc-95bb-7a08079c835e
Workspace: default / 05cf50a0-6d85-4ccc-8002-2a26f2c3d20b

ARTIFACT_STORE: default

Name: default
ID: 7cd3614e-dcac-4fd5-83ff-b3416bf8e3af
Type: artifact_store
Flavor: local
Configuration: {'path': ''}
Shared: No
User: default / 1f94c9b3-3ee6-47dc-95bb-7a08079c835e
Workspace: default / 05cf50a0-6d85-4ccc-8002-2a26f2c3d20b

### What happened?

`zenml server up`

gives:
```
Usage: zenml [OPTIONS] COMMAND [ARGS]...
Try 'zenml --help' for help.

Error: No such command 'server'.
```

### Reproduction steps

Installed zenml with pip

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
Hi thanks for this report. The error message is correct. There is no command `zenml server up`. If you want to launch a local version of the server you can just use `zenml up`.

For our own understanding, did you read somewhere in our docs (or elsewhere) that `zenml server up` is a command that should be used? We'd want to correct that if it is somewhere online. I see that you're using the latest version so it seems like you shouldn't have seen it in the most current version of our docs.

**Comment by lambdaofgod** [comment]
Oh I see the problem. Darn google directed me to old docs (v.0.13) ;)
