### ISSUE TITLE
[DOCS]: Outdated Documentation

### ISSUE THREAD

**Issue by dierop** [zenml-io/zenml#1655]
### Contact Details [Optional]

diegorospagan@gmail.com

### System Information

Zenml=0.43.0

### What happened?

After the update in the structure of the pipeline/steps in 0.40.0 I noticed there is outdated documentation in the components guide. Making reference to the old way to define/reference the steps.
I was using GreatExpectations validator Doc and noticed it was outdated.
But checking over other integrations seems to be outdated too, like evidently and deepcheckss.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schustmi** [comment]
Fixed in release 0.41.0
