### ISSUE TITLE
[DOCS]: Report: Broken Links and URLs in the Repo and A List of Which Ones Needs to Be Fixed

### ISSUE THREAD

**Issue by MarkusSagen** [zenml-io/zenml#1660]
### Contact Details [Optional]

markus.john.sagen@gmail.com

### System Information

---

### What happened?

Automated report identifying incorrect and failing URLs and Links in the repo and ZenML docs

## Report of broken URLs  

The following url and links appear broken in the repo:  

### README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml/deploying-zenml  
- [ ]  url: https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ]  url: https://docs.zenml.io/advanced-guide/stacks-components-flavors  
### CONTRIBUTING.md  
- [ ]  url: https://docs.zenml.io/component-gallery/integrations  
### RELEASE_NOTES.md  
- [ ]  url: https://docs.zenml.io/platform-guide/set-up-your-mlops-platform/connect-to-your-cloud-provider/azure-service-connector  
- [ ]  url: https://docs.zenml.io/starter-guide/production-fundamentals/code-repositories  
- [ ]  url: https://docs.zenml.io/starter-guide/production-fundamentals/secrets-management  
- [ ]  url: https://docs.zenml.io/component-gallery/image-builders/gcloud-build  
- [ ]  url: https://docs.zenml.io/component-gallery/annotators/label-studio  
- [ ]  url: https://docs.zenml.io/component-gallery/annotators/label-studio  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#zenml-takes-over-the-metadata-store-role  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty/getting-started/deploying-zenml/deploying-zenml.md  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#the-zenml-dashboard-is-now-available  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#removal-of-profiles-and-the-local-yaml-database  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#how-to-migrate-your-profiles  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#decoupling-stack-component-configuration-from-implementation  
- [ ]  url: https://docs.zenml.io/guidelines/migration-zero-twenty#shared-zenml-stacks-and-stack-components  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical/deploying-models  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/model-deployers  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/model-deployers  
- [ ]  url: https://docs.zenml.io/component-gallery/secrets-managers/secrets-managers  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/gcloud-vertexai  
- [ ]  url: https://docs.zenml.io/v/0.6.0/guides/index/custom-materializer  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines/pipelines  
- [ ]  url: https://docs.zenml.io/pipelines/materializers  
- [ ]  url: https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/orchestrators  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines/pipelines  
- [ ]  url: https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ]  url: https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ]  url: https://docs.zenml.io/core/stacks  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/orchestrators  
- [ ]  url: https://docs.zenml.io/misc/usage-analytics  
### examples/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
### examples/bentoml_deployment/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/bentoml  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/custom  
### examples/label_studio_annotation/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/annotators/annotators  
### examples/seldon_deployment/README.md  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/seldon  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/custom  
### examples/quickstart_py37/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/model-registries/mlflow  
- [ ]  url: https://docs.zenml.io/component-gallery/integrations  
### examples/mlflow_deployment/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/mlflow  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/custom  
### examples/slack_alert/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/alerters/alerters  
### examples/custom_code_deployment/README.md  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/seldon#custom-model-deployment  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/model-deployers#custom-pre-processing-and-post-processing  
- [ ]  url: https://docs.zenml.io/component-gallery/model-deployers/custom  
### examples/step_operator_remote_training/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/step-operators  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/amazon-sagemaker  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/azureml  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/gcloud-vertexai  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/step-operators  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/custom  
### examples/sagemaker_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/container-registries/amazon-ecr  
- [ ]  url: https://docs.zenml.io/component-gallery/artifact-stores/amazon-s3  
- [ ]  url: https://docs.zenml.io/component-gallery/container-registries/amazon-ecr#how-to-use-it  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/sagemaker  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/custom  
### examples/evidently_data_validation/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/data-validators/evidently#the-evidently-report-step  
- [ ]  url: https://docs.zenml.io/component-gallery/data-validators/evidently#the-evidently-test-step  
### examples/feast_feature_store/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/feature-stores/feast  
### examples/mlflow_tracking/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/mlflow  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/custom  
### examples/mlflow_registry/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/model-registries/mlflow  
- [ ]  url: https://docs.zenml.io/component-gallery/model-registries/custom  
### examples/kubernetes_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
### examples/quickstart/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/airflow  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/mlflow  
- [ ]  url: https://docs.zenml.io/component-gallery/data-validators/evidently  
- [ ]  url: https://docs.zenml.io/component-gallery/integrations  
### examples/code_repository/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/architecture-diagrams#the-code-repository  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml#deploying-zenml-in-the-cloud-remote-deployment-of-the-http-server-and-database  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/sagemaker  
- [ ]  url: https://docs.zenml.io/component-gallery/step-operators/vertex  
- [ ]  url: https://docs.zenml.io/starter-guide/production-fundamentals/code-repositories  
### examples/spark_distributed_programming/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
### examples/neptune_tracking/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/neptune  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/custom  
### examples/secrets_management/README.md  
- [ ]  url: https://docs.zenml.io/starter-guide/production-fundamentals/secrets-management  
### examples/airflow_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/airflow#how-to-deploy-it  
- [ ]  url: https://docs.zenml.io/component-gallery/artifact-stores  
- [ ]  url: https://docs.zenml.io/component-gallery/container-registries  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators  
### examples/kubeflow_pipelines_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/kubeflow  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/kubeflow  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/custom  
### examples/wandb_tracking/README.md  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/wandb  
- [ ]  url: https://docs.zenml.io/component-gallery/experiment-trackers/custom  
### examples/tekton_pipelines_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/tekton  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/custom  
### examples/vertex_ai_orchestration/README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/gcloud-vertexai  
- [ ]  url: https://docs.zenml.io/component-gallery/orchestrators/custom  

---  
## All URLs  
- [ ] https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes  
- [ ] https://docs.zenml.io/advanced-guide/practical-mlops/stack-recipes#deploying-stack-components-directly  
- [ ] https://docs.zenml.io/advanced-guide/practical/deploying-models  
- [ ] https://docs.zenml.io/component-gallery/alerters/alerters  
- [ ] https://docs.zenml.io/component-gallery/annotators/annotators  
- [ ] https://docs.zenml.io/component-gallery/annotators/label-studio  
- [ ] https://docs.zenml.io/component-gallery/artifact-stores  
- [ ] https://docs.zenml.io/component-gallery/artifact-stores/amazon-s3  
- [ ] https://docs.zenml.io/component-gallery/container-registries  
- [ ] https://docs.zenml.io/component-gallery/container-registries/amazon-ecr  
- [ ] https://docs.zenml.io/component-gallery/container-registries/amazon-ecr#how-to-use-it  
- [ ] https://docs.zenml.io/component-gallery/data-validators/evidently  
- [ ] https://docs.zenml.io/component-gallery/data-validators/evidently#the-evidently-report-step  
- [ ] https://docs.zenml.io/component-gallery/data-validators/evidently#the-evidently-test-step  
- [ ] https://docs.zenml.io/component-gallery/experiment-trackers/custom  
- [ ] https://docs.zenml.io/component-gallery/experiment-trackers/mlflow  
- [ ] https://docs.zenml.io/component-gallery/experiment-trackers/neptune  
- [ ] https://docs.zenml.io/component-gallery/experiment-trackers/wandb  
- [ ] https://docs.zenml.io/component-gallery/feature-stores/feast  
- [ ] https://docs.zenml.io/component-gallery/image-builders/gcloud-build  
- [ ] https://docs.zenml.io/component-gallery/integrations  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/bentoml  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/custom  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/mlflow  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/model-deployers  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/model-deployers#custom-pre-processing-and-post-processing  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/seldon  
- [ ] https://docs.zenml.io/component-gallery/model-deployers/seldon#custom-model-deployment  
- [ ] https://docs.zenml.io/component-gallery/model-registries/custom  
- [ ] https://docs.zenml.io/component-gallery/model-registries/mlflow  
- [ ] https://docs.zenml.io/component-gallery/orchestrators  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/airflow  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/airflow#how-to-deploy-it  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/custom  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/gcloud-vertexai  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/kubeflow  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/orchestrators  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/sagemaker  
- [ ] https://docs.zenml.io/component-gallery/orchestrators/tekton  
- [ ] https://docs.zenml.io/component-gallery/secrets-managers/secrets-managers  
- [ ] https://docs.zenml.io/component-gallery/step-operators/amazon-sagemaker  
- [ ] https://docs.zenml.io/component-gallery/step-operators/azureml  
- [ ] https://docs.zenml.io/component-gallery/step-operators/custom  
- [ ] https://docs.zenml.io/component-gallery/step-operators/gcloud-vertexai  
- [ ] https://docs.zenml.io/component-gallery/step-operators/step-operators  
- [ ] https://docs.zenml.io/component-gallery/step-operators/vertex  
- [ ] https://docs.zenml.io/core/stacks  
- [ ] https://docs.zenml.io/getting-started/architecture-diagrams#the-code-repository  
- [ ] https://docs.zenml.io/getting-started/deploying-zenml  
- [ ] https://docs.zenml.io/getting-started/deploying-zenml#deploying-zenml-in-the-cloud-remote-deployment-of-the-http-server-and-database  
- [ ] https://docs.zenml.io/getting-started/deploying-zenml/deploying-zenml  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#decoupling-stack-component-configuration-from-implementation  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#how-to-migrate-your-profiles  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#removal-of-profiles-and-the-local-yaml-database  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#shared-zenml-stacks-and-stack-components  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#the-zenml-dashboard-is-now-available  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty#zenml-takes-over-the-metadata-store-role  
- [ ] https://docs.zenml.io/guidelines/migration-zero-twenty/getting-started/deploying-zenml/deploying-zenml.md  
- [ ] https://docs.zenml.io/misc/usage-analytics  
- [ ] https://docs.zenml.io/pipelines/materializers  
- [ ] https://docs.zenml.io/platform-guide/set-up-your-mlops-platform/connect-to-your-cloud-provider/azure-service-connector  
- [ ] https://docs.zenml.io/starter-guide/pipelines/pipelines  
- [ ] https://docs.zenml.io/starter-guide/production-fundamentals/code-repositories  
- [ ] https://docs.zenml.io/starter-guide/production-fundamentals/secrets-management  
- [ ] https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ] https://docs.zenml.io/v/0.6.0/guides/index/custom-materializer  

### Relevant log output

```shell
---
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bcdurak** [comment]
Hello @MarkusSagen, thank you so much for reporting the broken links. I will try to fix them as quickly as possible and update the thread as I progress.

**Comment by MarkusSagen** [comment]
> Hello @MarkusSagen, thank you so much for reporting the broken links. I will try to fix them as quickly as possible and update the thread as I progress.

Fantastic! Happy to help

**Comment by bcdurak** [comment]
I have created this [PR](https://github.com/zenml-io/zenml/pull/1661) and once it is merged most of the broken links should be fixed. I will take another look at the RELEASE NOTES for the earlier versions and fix as many links as I can.

**Comment by bcdurak** [comment]
As the new version is out, all the links should be fixed now. Closing this issue along with the others.
