### ISSUE TITLE
[BUG]: Integration page ending into 404

### ISSUE THREAD

**Issue by MChorfa** [zenml-io/zenml#1684]
### System Information

chrome Version 114.0.5735.198 (Official Build) (x86_64)

### What happened?

the page is resulting into 404

https://www.zenml.io/features/integrations

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
https://www.zenml.io/integrations should work. If I might ask, where did you see that link?

**Comment by MChorfa** [comment]
I guess was during the upgrade from 0.40 to 0.41. I happened to visit that page then. Glad now it is working  👍🏼
