### ISSUE TITLE
[BUG]: CLI link to documentation is broken, and documentation indexing is broken

### ISSUE THREAD

**Issue by patricksavill** [zenml-io/zenml#1724]
### System Information

Zenml version 0.41.0

### What happened?

Running ZenML locally and got this warning message:
`
The ZenML global configuration version (0.42.1) is higher than the version of ZenML currently being used (0.41.0). Read more about this issue and how to solve it here: https://docs.zenml.io/user-guide/advanced-guide/global-settings-of-zenml#version-mismatch-downgrading
`

Following that link https://docs.zenml.io/user-guide/advanced-guide/global-settings-of-zenml#version-mismatch-downgrading gets the following
![image](https://github.com/zenml-io/zenml/assets/11937983/d454a548-109a-46a5-86ce-0db5a163ae47)

The CLI warning **isn't the bug**, the documentation online is.

### Reproduction steps

You can see the documentation search failure by going to `0.42.1` version online and trying to search for content:

![image](https://github.com/zenml-io/zenml/assets/11937983/66f1b21f-c581-47e2-92ae-e9fd4fa19308)

I think the CLI issue is tied to this, some automatic documentation update is breaking?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bcdurak** [comment]
Hello @patricksavill, thank you for reporting this issue. You are absolutely right, the link to the corresponding docs page seems to be broken. In case you need to take a look at the page, here is a working [link to the page in question](https://docs.zenml.io/user-guide/advanced-guide/environment-management/global-settings-of-zenml#version-mismatch-downgrading). We will fix the warning message with the next release.

Also, recently, we have had some issues regarding the search functionality of our documentation. We are currently investigating this issue and will try to fix it as soon as possible.

**Comment by bcdurak** [comment]
Hi @patricksavill, I have an update regarding this issue. Recently, we have refactored the `advanced guide` section of our docs and If you encounter this error with the latest release of ZenML, you should get the corrected link now. 

On the other hand, we are still investigating the error in the search functionality of our documentation.
