### ISSUE TITLE
[BUG]: Validation Error when trying to deploy a Vertex orchestrator on GCP

### ISSUE THREAD

**Issue by julesbertrand** [zenml-io/zenml#1812]
### Contact Details [Optional]

jules.bertrand@artefact.com

### System Information

ZENML_LOCAL_VERSION: 0.44.2
ZENML_SERVER_VERSION: 0.44.2
ZENML_SERVER_DATABASE: mysql
ZENML_SERVER_DEPLOYMENT_TYPE: gcp
ZENML_CONFIG_DIR: /Users/jules.bertrand/Library/Application Support/zenml
ZENML_LOCAL_STORE_DIR: /Users/jules.bertrand/Library/Application Support/zenml/local_stores
ZENML_SERVER_URL: https://zenml...
ZENML_ACTIVE_REPOSITORY_ROOT: /Users/jules.bertrand/Desktop/underground-disruptions
PYTHON_VERSION: 3.10.12
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'mac', 'mac_version': '10.16'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: admin
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: 4055097f-b298-4171-b3ce-dd27497415e7
ANALYTICS_USER_ID: 0bbcf7e1-4030-45ba-ac5c-a393c55c8931
ANALYTICS_SERVER_ID: f3da0b16-d59a-4e21-be1c-6e67957be586
INTEGRATIONS: ['gcp', 'github', 'kaniko', 'kubeflow', 'mlflow', 'pillow', 'scipy', 'seldon', 'sklearn']
PACKAGES: {'src': '0.0.1', 'babel': '2.12.1', 'brotli': '1.1.0', 'deprecated': '1.2.14', 'gitpython': '3.1.36', 'heapdict': '1.0.1', 'jinja2': '3.1.2', 'mako':
'1.2.4', 'markdown': '3.4.4', 'markupsafe': '2.1.3', 'pillow': '10.0.0', 'pygithub': '1.59.1', 'pyjwt': '2.8.0', 'pymysql': '1.0.3', 'pynacl': '1.5.0', 
'pysocks': '1.7.1', 'pyyaml': '6.0.1', 'pygments': '2.16.1', 'sqlalchemy': '1.4.41', 'sqlalchemy-utils': '0.38.3', 'send2trash': '1.8.2', 'shapely': 
'1.8.5.post1', 'absl-py': '1.4.0', 'aiofiles': '23.2.1', 'aiohttp': '3.8.5', 'aiokafka': '0.8.1', 'aiosignal': '1.3.1', 'alembic': '1.8.1', 'analytics-python':
'1.4.post1', 'anyio': '3.7.1', 'appnope': '0.1.3', 'argon2-cffi': '23.1.0', 'argon2-cffi-bindings': '21.2.0', 'arrow': '1.2.3', 'asgiref': '3.7.2', 
'asttokens': '2.4.0', 'async-lru': '2.0.4', 'async-timeout': '4.0.3', 'attrs': '23.1.0', 'azure-common': '1.1.28', 'azure-core': '1.29.4', 'azure-mgmt-core': 
'1.4.0', 'azure-mgmt-resource': '23.0.1', 'backcall': '0.2.0', 'backoff': '1.10.0', 'bcrypt': '4.0.1', 'beautifulsoup4': '4.12.2', 'black': '23.9.1', 'bleach':
'6.0.0', 'blinker': '1.6.2', 'blis': '0.7.10', 'bokeh': '2.4.3', 'build': '1.0.3', 'cachetools': '5.3.1', 'catalogue': '2.0.9', 'certifi': '2023.7.22', 'cffi':
'1.15.1', 'cfgv': '3.4.0', 'chardet': '5.2.0', 'charset-normalizer': '3.2.0', 'click': '8.1.3', 'click-params': '0.3.0', 'cloudpickle': '2.2.1', 'colorama': 
'0.4.6', 'comm': '0.1.4', 'commonmark': '0.9.1', 'confection': '0.1.3', 'contourpy': '1.0.7', 'coverage': '7.3.1', 'cramjam': '2.7.0', 'cryptography': 
'41.0.3', 'cycler': '0.11.0', 'cymem': '2.0.7', 'darglint': '1.8.1', 'dask': '2023.9.1', 'databricks-cli': '0.17.7', 'debugpy': '1.8.0', 'decorator': '5.1.1', 
'defusedxml': '0.7.1', 'distlib': '0.3.7', 'distributed': '2023.9.1', 'distro': '1.8.0', 'docker': '6.1.3', 'docopt': '0.6.2', 'docstring-parser': '0.15', 
'ecdsa': '0.18.0', 'emoji': '2.8.0', 'entrypoints': '0.4', 'exceptiongroup': '1.1.3', 'executing': '1.2.0', 'fastapi': '0.99.1', 'fastapi-utils': '0.2.1', 
'fastjsonschema': '2.18.0', 'fastparquet': '2023.8.0', 'filelock': '3.12.4', 'fire': '0.5.0', 'flake8': '6.1.0', 'flake8-to-ruff': '0.0.233', 'flashtext': 
'2.7', 'flask': '2.3.3', 'fonttools': '4.39.2', 'fqdn': '1.5.1', 'fr-core-news-sm': '3.6.0', 'frozenlist': '1.4.0', 'fsspec': '2023.9.0', 'ftfy': '6.1.1', 
'gcsfs': '2023.9.0', 'gdown': '4.7.1', 'gevent': '23.9.0.post1', 'geventhttpclient': '2.0.2', 'gitdb': '4.0.10', 'google-api-core': '2.11.1', 
'google-api-python-client': '1.12.11', 'google-auth': '2.17.3', 'google-auth-httplib2': '0.1.0', 'google-auth-oauthlib': '1.0.0', 'google-cloud-aiplatform': 
'1.32.0', 'google-cloud-bigquery': '3.11.4', 'google-cloud-build': '3.20.0', 'google-cloud-container': '2.31.0', 'google-cloud-core': '2.3.3', 
'google-cloud-functions': '1.13.2', 'google-cloud-resource-manager': '1.10.3', 'google-cloud-scheduler': '2.11.1', 'google-cloud-secret-manager': '2.16.3', 
'google-cloud-storage': '2.10.0', 'google-crc32c': '1.5.0', 'google-resumable-media': '2.6.0', 'googleapis-common-protos': '1.60.0', 'greenlet': '2.0.2', 
'grpc-google-iam-v1': '0.12.6', 'grpcio': '1.58.0', 'grpcio-status': '1.48.2', 'gunicorn': '20.1.0', 'h11': '0.14.0', 'httplib2': '0.19.1', 'httptools': 
'0.6.0', 'identify': '2.5.28', 'idna': '3.4', 'imbalanced-learn': '0.11.0', 'importlib-metadata': '6.8.0', 'importlib-resources': '6.0.1', 'iniconfig': 
'2.0.0', 'ipykernel': '6.25.2', 'ipython': '8.15.0', 'ipython-genutils': '0.2.0', 'ipywidgets': '7.8.1', 'isodate': '0.6.1', 'isoduration': '20.11.0', 'isort':
'5.12.0', 'itsdangerous': '2.1.2', 'jedi': '0.19.0', 'joblib': '1.3.2', 'json5': '0.9.14', 'jsonpointer': '2.4', 'jsonschema': '4.19.0', 
'jsonschema-specifications': '2023.7.1', 'jupyter-client': '8.3.1', 'jupyter-core': '5.3.1', 'jupyter-events': '0.7.0', 'jupyter-lsp': '2.2.0', 
'jupyter-server': '2.7.3', 'jupyter-server-terminals': '0.4.4', 'jupyterlab': '4.0.5', 'jupyterlab-pygments': '0.2.2', 'jupyterlab-server': '2.25.0', 
'jupyterlab-widgets': '1.1.7', 'kafka-python': '2.0.2', 'kfp': '1.8.22', 'kfp-pipeline-spec': '0.1.16', 'kfp-server-api': '1.8.5', 'kiwisolver': '1.4.4', 
'kubernetes': '18.20.0', 'langcodes': '3.3.0', 'llvmlite': '0.40.1', 'locket': '1.0.0', 'loguru': '0.7.2', 'lxml': '4.9.3', 'lz4': '4.3.2', 'matplotlib': 
'3.7.1', 'matplotlib-inline': '0.1.6', 'mccabe': '0.7.0', 'mistune': '3.0.1', 'mlflow': '2.2.2', 'mlserver': '1.3.5', 'mlserver-mlflow': '1.3.5', 'mlstacks': 
'0.7.3', 'monotonic': '1.6', 'mosestokenizer': '1.2.1', 'msgpack': '1.0.5', 'multidict': '6.0.4', 'murmurhash': '1.0.9', 'mypy-extensions': '1.0.0', 
'nbclassic': '0.5.3', 'nbclient': '0.8.0', 'nbconvert': '7.8.0', 'nbformat': '5.9.2', 'nest-asyncio': '1.5.7', 'nlpaug': '1.1.11', 'nlpretext': '1.2.1', 
'nltk': '3.8.1', 'nodeenv': '1.8.0', 'notebook': '7.0.3', 'notebook-shim': '0.2.3', 'numba': '0.57.1', 'numpy': '1.25.2', 'oauthlib': '3.2.2', 'openfile': 
'0.0.7', 'orjson': '3.8.14', 'overrides': '7.4.0', 'packaging': '23.1', 'pandas': '2.1.0', 'pandocfilters': '1.5.0', 'parso': '0.8.3', 'partd': '1.4.0', 
'passlib': '1.7.4', 'pathspec': '0.11.2', 'pathy': '0.10.2', 'pexpect': '4.8.0', 'phonenumbers': '8.13.20', 'pickleshare': '0.7.5', 'pip': '23.2.1', 
'pip-tools': '7.3.0', 'platformdirs': '3.10.0', 'plotly': '5.13.1', 'pluggy': '1.3.0', 'pre-commit': '3.4.0', 'preshed': '3.0.8', 'prometheus-client': 
'0.17.1', 'prompt-toolkit': '3.0.39', 'proto-plus': '1.22.3', 'protobuf': '3.20.3', 'psutil': '5.9.5', 'ptyprocess': '0.7.0', 'pure-eval': '0.2.2', 
'py-grpc-prometheus': '0.7.0', 'pyarrow': '13.0.0', 'pyasn1': '0.5.0', 'pyasn1-modules': '0.3.0', 'pycodestyle': '2.11.0', 'pycparser': '2.21', 'pydantic': 
'1.10.12', 'pyflakes': '3.1.0', 'pyparsing': '2.4.7', 'pyproject-hooks': '1.0.0', 'pyrsistent': '0.19.3', 'pytest': '7.4.2', 'pytest-cov': '4.1.0', 
'python-dateutil': '2.8.2', 'python-dotenv': '1.0.0', 'python-jose': '3.3.0', 'python-json-logger': '2.0.7', 'python-multipart': '0.0.6', 'python-rapidjson': 
'1.10', 'python-terraform': '0.10.1', 'pytz': '2023.3.post1', 'pyzmq': '25.1.1', 'querystring-parser': '1.2.4', 'referencing': '0.30.2', 'regex': '2023.8.8', 
'requests': '2.31.0', 'requests-oauthlib': '1.3.1', 'requests-toolbelt': '0.10.1', 'rfc3339-validator': '0.1.4', 'rfc3986-validator': '0.1.1', 'rich': 
'12.6.0', 'rpds-py': '0.10.3', 'rsa': '4.9', 'ruff': '0.0.288', 'sacremoses': '0.0.53', 'scikit-learn': '1.2.2', 'scipy': '1.11.2', 'setuptools': '68.2.2', 
'shap': '0.42.1', 'shellingham': '1.5.3', 'six': '1.16.0', 'slicer': '0.0.7', 'smart-open': '6.4.0', 'smmap': '5.0.0', 'sniffio': '1.3.0', 'snscrape': 
'0.7.0.20230622', 'sortedcontainers': '2.4.0', 'soupsieve': '2.5', 'spacy': '3.6.1', 'spacy-legacy': '3.0.12', 'spacy-loggers': '1.0.5', 'sqlalchemy2-stubs': 
'0.0.2a35', 'sqlmodel': '0.0.8', 'sqlparse': '0.4.4', 'srsly': '2.4.7', 'stack-data': '0.6.2', 'starlette': '0.27.0', 'starlette-exporter': '0.16.0', 
'stop-words': '2018.7.23', 'strip-hints': '0.1.10', 'tabulate': '0.9.0', 'tblib': '2.0.0', 'tenacity': '8.2.2', 'termcolor': '2.3.0', 'terminado': '0.17.1', 
'thinc': '8.1.12', 'threadpoolctl': '3.2.0', 'tinycss2': '1.2.1', 'tomli': '2.0.1', 'toolwrapper': '2.1.0', 'toolz': '0.12.0', 'tornado': '6.3.3', 'tqdm': 
'4.66.1', 'traitlets': '5.9.0', 'tritonclient': '2.36.0', 'typer': '0.9.0', 'typing-extensions': '4.7.1', 'tzdata': '2023.3', 'uctools': '1.3.0', 
'underground-disruptions': '0.1.0', 'uri-template': '1.3.0', 'uritemplate': '3.0.1', 'urllib3': '1.26.16', 'uvicorn': '0.17.6', 'uvloop': '0.17.0', 
'validators': '0.18.2', 'virtualenv': '20.24.5', 'wasabi': '1.1.2', 'watchgod': '0.8.2', 'wcwidth': '0.2.6', 'webcolors': '1.13', 'webencodings': '0.5.1', 
'websocket-client': '1.6.3', 'websockets': '11.0.3', 'werkzeug': '2.3.7', 'wheel': '0.41.2', 'widgetsnbextension': '3.6.6', 'wordcloud': '1.8.2.2', 'wrapt': 
'1.15.0', 'xyzservices': '2023.7.0', 'yarl': '1.9.2', 'zenml': '0.44.2', 'zict': '3.0.0', 'zipp': '3.16.2', 'zope.event': '5.0', 'zope.interface': '6.0'}

CURRENT STACK

Name: default
ID: d874d19e-67fb-4b79-8aff-b0f3e69ad10b
Shared: No
User: admin / 0bbcf7e1-4030-45ba-ac5c-a393c55c8931
Workspace: default / 3f558f6a-8951-4dcc-88a9-db29ab9c17d2

ORCHESTRATOR: default

Name: default
ID: 7d6cb841-4652-48ea-999e-07c4c7102ad6
Type: orchestrator
Flavor: local
Configuration: {}
Shared: No
User: admin / 0bbcf7e1-4030-45ba-ac5c-a393c55c8931
Workspace: default / 3f558f6a-8951-4dcc-88a9-db29ab9c17d2

ARTIFACT_STORE: default

Name: default
ID: 9f47e7e2-0ebd-40a8-9502-59b12a7496c5
Type: artifact_store
Flavor: local
Configuration: {'path': ''}
Shared: No
User: admin / 0bbcf7e1-4030-45ba-ac5c-a393c55c8931
Workspace: default / 3f558f6a-8951-4dcc-88a9-db29ab9c17d2

### What happened?

`zenml orchestrator deploy ... --flavor=vertex` raises  a Pydantic Validation Error.

I then tried using `gcp` as flavor (see traceback below), but as expected, it does not work because it's not a registered orchestrator flavor.

### Reproduction steps

1. Deploy ZenML server on GCp using the CLI
2. Connect to server
3. Deploy orchestrator with vertex flavor
```bash
zenml orchestrator deploy vertex-orchestrator \
    --flavor vertex \
    --provider gcp \
    --region europe-west1 \
    --extra-config project_id=<PROJECT_ID>
```

...

### Relevant log output

```shell
Checking prerequisites are installed...
The mlstacks tool/package is in alpha and actively being developed. Please avoid running mission-critical workloads on resources deployed through these 
commands. If you encounter any problems, create an issue on the repository https://github.com/zenml-io/mlops-stacks.git and we'll help you out!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/jules.bertrand/miniconda3/envs/zenml/bin/zenml:8 in <module>                              │
│                                                                                                  │
│   5 from zenml.cli.cli import cli                                                                │
│   6 if __name__ == "__main__":                                                                   │
│   7 │   sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:1130 in   │
│ __call__                                                                                         │
│                                                                                                  │
│   1127 │                                                                                         │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1129 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                 │
│   1131                                                                                           │
│   1132                                                                                           │
│   1133 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:1055 in   │
│ main                                                                                             │
│                                                                                                  │
│   1052 │   │   try:                                                                              │
│   1053 │   │   │   try:                                                                          │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1056 │   │   │   │   │   if not standalone_mode:                                               │
│   1057 │   │   │   │   │   │   return rv                                                         │
│   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:1657 in   │
│ invoke                                                                                           │
│                                                                                                  │
│   1654 │   │   │   │   super().invoke(ctx)                                                       │
│   1655 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1656 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1658 │   │                                                                                     │
│   1659 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1660 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:1657 in   │
│ invoke                                                                                           │
│                                                                                                  │
│   1654 │   │   │   │   super().invoke(ctx)                                                       │
│   1655 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1656 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1658 │   │                                                                                     │
│   1659 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1660 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:1404 in   │
│ invoke                                                                                           │
│                                                                                                  │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1402 │   │                                                                                     │
│   1403 │   │   if self.callback is not None:                                                     │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1405 │                                                                                         │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1407 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/click/core.py:760 in    │
│ invoke                                                                                           │
│                                                                                                  │
│    757 │   │                                                                                     │
│    758 │   │   with augment_usage_errors(__self):                                                │
│    759 │   │   │   with ctx:                                                                     │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    761 │                                                                                         │
│    762 │   def forward(                                                                          │
│    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/zenml/cli/stack_compone │
│ nts.py:1285 in deploy_stack_component_command                                                    │
│                                                                                                  │
│   1282 │   │   │   }                                                                             │
│   1283 │   │   │   if component_type == StackComponentType.ARTIFACT_STORE:                       │
│   1284 │   │   │   │   cli_params["extra_config"].append(f"bucket_name={name}")  # type: ignore  │
│ ❱ 1285 │   │   │   stack, components = convert_click_params_to_mlstacks_primitives(              │
│   1286 │   │   │   │   cli_params, zenml_component_deploy=True                                   │
│   1287 │   │   │   )                                                                             │
│   1288                                                                                           │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/zenml/utils/mlstacks_ut │
│ ils.py:368 in convert_click_params_to_mlstacks_primitives                                        │
│                                                                                                  │
│   365 │   from mlstacks.models import Component, Stack                                           │
│   366 │                                                                                          │
│   367 │   stack: Stack = _construct_base_stack(params)                                           │
│ ❱ 368 │   components: List[Component] = _construct_components(                                   │
│   369 │   │   params, zenml_component_deploy                                                     │
│   370 │   )                                                                                      │
│   371                                                                                            │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/zenml/utils/mlstacks_ut │
│ ils.py:279 in _construct_components                                                              │
│                                                                                                  │
│   276 │   │   else {}                                                                            │
│   277 │   )                                                                                      │
│   278 │   if zenml_component_deploy:                                                             │
│ ❱ 279 │   │   components = [                                                                     │
│   280 │   │   │   Component(                                                                     │
│   281 │   │   │   │   name=params[key],                                                          │
│   282 │   │   │   │   component_type=key,                                                        │
│                                                                                                  │
│ /Users/jules.bertrand/miniconda3/envs/zenml/lib/python3.10/site-packages/zenml/utils/mlstacks_ut │
│ ils.py:280 in <listcomp>                                                                         │
│                                                                                                  │
│   277 │   )                                                                                      │
│   278 │   if zenml_component_deploy:                                                             │
│   279 │   │   components = [                                                                     │
│ ❱ 280 │   │   │   Component(                                                                     │
│   281 │   │   │   │   name=params[key],                                                          │
│   282 │   │   │   │   component_type=key,                                                        │
│   283 │   │   │   │   component_flavor=_get_component_flavor(key, value, provider),              │
│                                                                                                  │
│ /Users/jules.bertrand/Desktop/underground-disruptions/pydantic/main.py:341 in                    │
│ pydantic.main.BaseModel.__init__                                                                 │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/Users/jules.bertrand/Desktop/underground-disruptions/pydantic/main.py'                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for Component
component_flavor
  value is not a valid enumeration member; permitted: 'zenml', 'mlflow', 'kubeflow', 'kserve', 'kubernetes', 's3', 'sagemaker', 'seldon', 'tekton', 'minio', 
'gcp', 'aws' (type=type_error.enum; enum_values=[<ComponentFlavorEnum.ZENML: 'zenml'>, <ComponentFlavorEnum.MLFLOW: 'mlflow'>, <ComponentFlavorEnum.KUBEFLOW: 
'kubeflow'>, <ComponentFlavorEnum.KSERVE: 'kserve'>, <ComponentFlavorEnum.KUBERNETES: 'kubernetes'>, <ComponentFlavorEnum.S3: 's3'>, 
<ComponentFlavorEnum.SAGEMAKER: 'sagemaker'>, <ComponentFlavorEnum.SELDON: 'seldon'>, <ComponentFlavorEnum.TEKTON: 'tekton'>, <ComponentFlavorEnum.MINIO: 
'minio'>, <ComponentFlavorEnum.GCP: 'gcp'>, <ComponentFlavorEnum.AWS: 'aws'>])
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
Thanks for the report @julesbertrand. Fix for this is done [here](https://github.com/zenml-io/mlstacks/pull/94) and will make a release today so you aren't blocked by this.

**Comment by strickvl** [comment]
`mlstacks` 0.7.5 is now out, addressing this issue amongst other fixes.
