### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by psmoros** [zenml-io/zenml#1823]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@andy53) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by strickvl** [comment]
https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-reporting-a-vulnerability explains our vulnerability reporting process and lists an email. Thanks for the pointer to the Github recommendation, too. We'll look into that.

**Comment by strickvl** [comment]
Closing this following the PR listed above. I trust @Andy53 will be in touch.
