### ISSUE TITLE
[BUG]: Variable naming for `generative-chat` example

### ISSUE THREAD

**Issue by bhatt-priyadutt** [zenml-io/zenml#1834]
### System Information

NA

### What happened?

In generative-chat example, the readme docs contains instructions specifying slack token as env variable, shouldnt the env var name be `SLACK_BOT_TOKEN` instead of `SLACK_API_TOKEN` as in the code that is what is used. 

https://github.com/zenml-io/zenml/blob/df95a26558622de294bd4ea6cc74808e3e10633a/examples/generative_chat/steps/slack_loader.py#L51

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
I think a lot of that code was taken from Slack docs, but we'd take a PR on that, for sure!

**Comment by strickvl** [comment]
This has now been merged. Thanks!
