### ISSUE TITLE
[BUG]: incorrect documents list given to FAISS function

### ISSUE THREAD

**Issue by bhatt-priyadutt** [zenml-io/zenml#1862]
### System Information

latest version

### What happened?

Please check here, i think it should be as..

`return FAISS.from_documents(split_documents, embeddings)`

and not the below

https://github.com/zenml-io/zenml/blob/18824ef77df44f3dee4ba1e7f61d767db8ee58c2/examples/generative_chat/steps/index_generator.py#L84C1-L85C1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
Good catch! That said, this example will be removed soon as there's a lot of duplicated code with https://github.com/zenml-io/zenml-projects/tree/main/langchain-llamaindex-slackbot. It's handled correctly there: https://github.com/zenml-io/zenml-projects/blob/main/langchain-llamaindex-slackbot/src/steps/index_generator.py so I'll close this issue.
