### ISSUE TITLE
[BUG]: inconsistent pointers to helm chart ocis

### ISSUE THREAD

**Issue by cameronraysmith** [zenml-io/zenml#1865]
Attempting to download the helm chart oci we receive the following

```sh
> helm pull oci://public.ecr.aws/zenml/zenml-server --version 0.44.3 \
        --untar --untardir ./charts/
Error: unexpected status from HEAD request to https://public.ecr.aws/v2/zenml/zenml-server/manifests/0.44.3: 400 Bad Request
```

We also tried `oci://public.ecr.aws/zenml/zenml` as it appears differently on [artifacthub](https://github.com/zenml-io/zenml/blob/18824ef77df44f3dee4ba1e7f61d767db8ee58c2/src/zenml/zen_server/deploy/helm/README.md?plain=1#L24) versus the [docs](https://github.com/zenml-io/zenml/blob/18824ef77df44f3dee4ba1e7f61d767db8ee58c2/docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md?plain=1#L85) website.

Based on the workflow you’re using to publish the chart oci,
https://github.com/zenml-io/zenml/blob/18824ef77df44f3dee4ba1e7f61d767db8ee58c2/.github/workflows/publish_helm_chart.yml#L48
I guess it should be `zenml` and not `zenml-server`, but both produce the same error.

These are executed following login with

```sh
> aws ecr-public get-login-password \
     --region us-east-1 | helm registry login \
     --username AWS \
     --password-stdin public.ecr.aws
Login Succeeded
```

```sh
> helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.21.1"}
```

It’s not hard to workaround by [downloading from github](https://github.com/zenml-io/zenml/tree/18824ef77df44f3dee4ba1e7f61d767db8ee58c2/src/zenml/zen_server/deploy/helm), just outside the current docs.

**Comment by wjayesh** [comment]
Hi @cameronraysmith, thanks for pointing out the bug in the docs. You're right, it should be `zenml` and not `zenml-server`. As for the error, I'm not able to reproduce it unfortunately, using a different account and multiple roles. I'll do some more testing and ask someone from the community to try it out too.

**Comment by cameronraysmith** [comment]
This was an issue in `v3.13.0` of helm that was fixed in [v3.13.1]().

https://github.com/helm/helm/issues/12483
https://github.com/helm/helm/commit/0ac78941abfed981a47f263fa59931e9123f73a1

**Comment by cameronraysmith** [comment]
https://github.com/zenml-io/zenml/pull/1942 marks the resolution, but feel free to close it without merging if it's more convenient.

**Comment by wjayesh** [comment]
Thank you so much for the analysis and the PR @cameronraysmith!
