### ISSUE TITLE
[BUG]: TypeError: 'StepArtifact' object is not subscriptable

### ISSUE THREAD

**Issue by Muhammed-Rashid-07** [zenml-io/zenml#2040]
TypeError: 'StepArtifact' object is not subscriptable

### Contact Details [Optional]

rashid24601@gmail.com

### System Information

Name: zenml
Version: 0.45.6
Summary: ZenML: Write production-ready ML code.
Home-page: https://zenml.io
Author: ZenML GmbH
Author-email: info@zenml.io
License: Apache-2.0
Location: /home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages
Requires: alembic, azure-mgmt-resource, click, click-params, cloudpickle, distro, docker, gitpython, httplib2, pandas, passlib, psutil, pydantic, pymysql, pyparsing, python-dateutil, pyyaml, rich, sqlalchemy_utils, sqlmodel
Required-by: 

### What happened?

When I tried to subscript list in the pipeline or step it is not working.

eg: 
@pipeline(enable_cache=False, settings={"docker": docker_settings})
def text_data_report_test_pipeline():
    """Links all the steps together in a pipeline."""
    data = ingest_df()
    df = cleaning_data(data)
    reference_dataset, comparison_dataset = reference_current_splitter(data)
    reference_viral = reference_dataset['is_viral']
    comparison_dataset = comparison_dataset['is_viral']
    report, _ = text_data_report(
        reference_dataset=reference_dataset,
        comparison_dataset=comparison_dataset,
    )
    json_report, html_report = text_data_test(
        reference_dataset=reference_dataset,
        comparison_dataset=comparison_dataset,
    )

when I ran this pipeline it show 
───
TypeError: 'StepArtifact' object is not subscriptable

### Reproduction steps

1. When I tried to use this in my pipeline
2. when I tried to use this in steps
3. when I tried to use evidently for model tracking

### Relevant log output

```shell
Initiating a new run for the pipeline: text_data_report_test_pipeline.
Reusing registered version: (version: 1).
Executing a new run.
Caching is disabled by default for text_data_report_test_pipeline.
Using user: default
Using stack: youtube_stack1
  data_validator: evidently_data_validator
  artifact_store: default
  model_deployer: mlflow2
  model_registry: mlflow_registry
  orchestrator: default
  experiment_tracker: mlflow_tracker2
Caching disabled explicitly for ingest_df.
Step ingest_df has started.
Reading csv file successfully completed.
Ingesting data completed
Step ingest_df has finished in 1m10s.
Caching enabled explicitly for cleaning_data.
Step cleaning_data has started.
Step cleaning_data has finished in 34.467s.
Caching disabled explicitly for reference_current_splitter.
Step reference_current_splitter has started.
Step reference_current_splitter has finished in 12.511s.
Step evidently_report_step has started.
failed to get features for <class 'evidently.metrics.data_integrity.column_summary_metric.ColumnSummaryMetric'>: 'comments_disabled'
Traceback (most recent call last):
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/suite/base_suite.py", line 326, in create_additional_features
    required_features = metric.required_features(data_definition)
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/metrics/data_integrity/column_summary_metric.py", line 149, in required_features
    column_type = data_definition.get_column(self.column_name.name).column_type
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/utils/data_preprocessing.py", line 101, in get_column
    return self._columns[column_name]
KeyError: 'comments_disabled'
failed to get features for <class 'evidently.metrics.data_integrity.column_summary_metric.ColumnSummaryMetric'>: 'ratings_disabled'
Traceback (most recent call last):
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/suite/base_suite.py", line 326, in create_additional_features
    required_features = metric.required_features(data_definition)
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/metrics/data_integrity/column_summary_metric.py", line 149, in required_features
    column_type = data_definition.get_column(self.column_name.name).column_type
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/utils/data_preprocessing.py", line 101, in get_column
    return self._columns[column_name]
KeyError: 'ratings_disabled'
failed to get features for <class 'evidently.metrics.data_integrity.column_summary_metric.ColumnSummaryMetric'>: 'video_error_or_removed'
Traceback (most recent call last):
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/suite/base_suite.py", line 326, in create_additional_features
    required_features = metric.required_features(data_definition)
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/metrics/data_integrity/column_summary_metric.py", line 149, in required_features
    column_type = data_definition.get_column(self.column_name.name).column_type
  File "/home/rashid/miniconda3/envs/project-youtube/lib/python3.10/site-packages/evidently/utils/data_preprocessing.py", line 101, in get_column
    return self._columns[column_name]
KeyError: 'video_error_or_removed'
Killed
(project-youtube) rashid@LAPTOP-SJ2R2UP5:/mnt/e/youtube-virality$ conda deactivate
(base) rashid@LAPTOP-SJ2R2UP5:/mnt/e/youtube-virality$ conda activate project-youtube
(project-youtube) rashid@LAPTOP-SJ2R2UP5:/mnt/e/youtube-virality$ python run_pipeline.py
╭─────────────────────────────── Traceback (most recent c
│ /mnt/e/youtube-virality/run_pipeline.py:5 in <module>  
│                                                        
│    2 from zenml.client import Client                   
│    3 from dotenv import load_dotenv                    
│    4 from pipelines.training_pipeline import train_pipe
│ ❱  5 from pipelines.text_data_test_pipeline import text
│    6                                                   
│    7 if __name__ == "__main__":                        
│    8 │   load_dotenv()                                 
│                                                        
│ /mnt/e/youtube-virality/pipelines/text_data_test_pipeli
│                                                        
│   26 │   )                                             
│   27                                                   
│   28                                                   
│ ❱ 29 text_data_report_test_pipeline()                  
│   30                                                   
│                                                        
│ /home/rashid/miniconda3/envs/project-youtube/lib/python
│ peline.py:1496 in __call__                             
│                                                        
│   1493 │   │   │   # pipeline. Is this what we want?   
│   1494 │   │   │   return self.entrypoint(*args, **kwar
│   1495 │   │                                           
│ ❱ 1496 │   │   self.prepare(*args, **kwargs)           
│   1497 │   │   return self._run(**self._run_args)      
│   1498 │                                               
│   1499 │   def _call_entrypoint(self, *args: Any, **kwa
│                                                        
│ /home/rashid/miniconda3/envs/project-youtube/lib/python
│ peline.py:441 in prepare                               
│                                                        
│    438 │   │   │   # Enter the context manager, so we b
│    439 │   │   │   # means that all steps that get call
│    440 │   │   │   # is executed will be added as invoc
│ ❱  441 │   │   │   self._call_entrypoint(*args, **kwarg
│    442 │                                               
│    443 │   def register(self) -> "PipelineResponseModel
│    444 │   │   """Register the pipeline in the server. 
│                                                        
│ /home/rashid/miniconda3/envs/project-youtube/lib/python
│ peline.py:1524 in _call_entrypoint                     
│                                                        
│   1521 │   │   │   ) from e                            
│   1522 │   │                                           
│   1523 │   │   self._parameters = validated_args       
│ ❱ 1524 │   │   self.entrypoint(**validated_args)       
│   1525 │                                               
│   1526 │   def _prepare_if_possible(self) -> None:     
│   1527 │   │   """Prepares the pipeline if possible.   
│                                                        
│ /mnt/e/youtube-virality/pipelines/text_data_test_pipeli
│ text_data_report_test_pipeline                         
│                                                        
│   14 │   data = ingest_df()                            
│   15 │   df = cleaning_data(data)                      
│   16 │   reference_dataset, comparison_dataset = refere
│ ❱ 17 │   reference_viral = reference_dataset['is_viral'
│   18 │   comparison_dataset = comparison_dataset['is_vi
│   19 │   report, _ = text_data_report(                 
│   20 │   │   reference_dataset=reference_dataset,      
╰────────────────────────────────────────────────────────
TypeError: 'StepArtifact' object is not subscriptable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdelrhmanNile** [comment]
same error
did you find a solution?

**Comment by htahir1** [comment]
I think there needs to be more context on the original error by @Muhammed-Rashid-07 to resolve this.. need the step code

**Comment by AbdelrhmanNile** [comment]
@htahir1 
```
from zenml import step
from tensorflow.keras.datasets import mnist  # type: ignore
from tensorflow.keras.utils import to_categorical  # type: ignore

from typing_extensions import Tuple, Annotated, Any

import numpy as np


@step
def load_data() -> (
    Annotated[Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray], "data"]
):
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train = x_train.reshape((60000, 28, 28, 1))
    x_train = x_train.astype("float32") / 255.0
    x_test = x_test.reshape((10000, 28, 28, 1))
    x_test = x_test.astype("float32") / 255.0
    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)
    return x_train, y_train, x_test, y_test
```
now in my pipleine
```
from zenml import pipeline
from steps.dataloader import load_data
from steps.modelbuilder import build_model
from steps.trainer import train_model
from steps.eval import evaluate_model


@pipeline
def mnist_pipeline() -> None:
    x_train, y_train, x_test, y_test = load_data()
```

throws the following error

```
TypeError: cannot unpack non-iterable StepArtifact object
```

**Comment by htahir1** [comment]
I see. I think you are annotating the step wrongly here:

```python
@step
def load_data() -> (
    Annotated[Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray], "data"]
):
```

Your type annotation is saying "My step has *one* return type and thats a tuple of 4 things"

But rather it should say

"My step has "four" return types and each have their own annotations:

```python
@step
def load_data() -> (
    Tuple[Annotated[np.ndarray, "x_train"], Annotated[np.ndarray, "y_train"], Annotated[np.ndarray, "x_test"], Annotated[np.ndarray, "y_test"]
):
```

**Comment by Muhammed-Rashid-07** [comment]
I have solved this issue few months back, the problem was I did list subscription in pipeline. In pipeline it is not possible to do it subscription or any operation. If we have to add anything like that do it in steps and import them into the pipeline. I think that's how it works.

@htahir1  just curious, Why is it not possible to do that in pipeline? Can you explain the reason.

**Comment by htahir1** [comment]
@Muhammed-Rashid-07 The @pipeline function executes at composition time, and the execution of the pipeline potentially can happen later. This means that when you run a pipeline, zenml first "runs" your pipeline function code and evaluates which steps are connected to which others. After that zenml does not run that code again, so if you have anything dynamic that needs to go between steps, they should be in the step body, not the pipeline body.

**Comment by strickvl** [comment]
@Muhammed-Rashid-07 was this enough information for you to solve your problem / move on? If so, I'll close out this issue.

**Comment by YJ-1527** [comment]
I'm getting same error 
from zenml import pipeline
from steps.data_loading import load_dataset
from steps.data_preparation import data_creation
from steps.train_model import training_model
from steps.test_model import model_test
# from .config import Parameters



@pipeline
def train_pipeline():
    dataset_path = r"F:\VisualStudio\Training_ML_dlib_model\data\images"
    test_img_path = r"F:\VisualStudio\Training_ML_dlib_model\data\test_imgs\user_9_954.jpg" 
    lst_imgs_train, train_folder_path, lst_imgs_test, test_folder_path = load_dataset(dataset_path)
    train_xml,test_xml = data_creation(lst_imgs_train,train_folder_path,lst_imgs_test,test_folder_path)
    model_path = training_model(train_folder_path,train_xml,test_xml)
    model_test(test_img_path,model_path)
    
    
    from src.data_loading import Dataloading
from zenml import step
import logging




@step
def load_dataset(dataset_path):
    # dataset_path = r"F:\VisualStudio\Training_ML_dlib_model\data\images"
    data_load  = Dataloading(dataset_path)
    train_folder,test_folder = data_load.split_images()
    lst_imgs_train,train_folder_path = data_load.load_images(train_folder)
    lst_imgs_test,test_folder_path = data_load.load_images(test_folder)
    return lst_imgs_train, train_folder_path, lst_imgs_test, test_folder_path

**Comment by YJ-1527** [comment]
Hi, even I'm getting the same error "stepartifact object is not subscriptable" 

from src.data_loading import Dataloading
from zenml import step
import logging
from typing import Tuple




@step(enable_step_logs = True)
def load_dataset()-> Tuple[list,str,list,str]:
    print("Loading dataset.....")
    dataset_path = r"F:\VisualStudio\Training_ML_dlib_model\data\images"
    data_load  = Dataloading(dataset_path)
    train_folder,test_folder = data_load.split_images()
    lst_imgs_train,train_folder_path = data_load.load_images(train_folder)
    lst_imgs_test,test_folder_path = data_load.load_images(test_folder)
    # lst = [lst_imgs_train, train_folder_path, lst_imgs_test, test_folder_path]
    # print(lst)
    return lst_imgs_train, train_folder_path,lst_imgs_test,test_folder_path


from zenml import pipeline
from steps.data_loading import load_dataset
from steps.data_preparation import data_creation
from steps.train_model import training_model
from steps.test_model import model_test
# from .config import Parameters



@pipeline(enable_step_logs=True)
def train_pipeline(dataset_path,test_img_path):
   
    # load_dataset_output = load_dataset(dataset_path)
    output_load_dataset  = load_dataset()



Can anyone please help me out

**Comment by Nomanriaz786** [comment]
C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\feast\feature_view.py:48: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity '__dummy'.
  DUMMY_ENTITY = Entity(
Starting inference process...
Initiating a new run for the pipeline: crypto_inference_pipeline.
Caching is disabled by default for crypto_inference_pipeline.
Using user: default
Using stack: crypto_stack
  feature_store: feast_feature_store
  model_deployer: mlflow_deployer
  orchestrator: local_orchestrator
  experiment_tracker: mlflow_tracker
  artifact_store: local_store
Dashboard URL for Pipeline Run: http://localhost:8237/runs/4fe5b0cc-df50-41c9-a185-30fe9e9d1a09
Step ingest_inference_data has started.
Total fetched records for BTC/USDT at 1h: 100
Step ingest_inference_data has finished in 22.212s.
Step clean_inference_data has started.
Processing 100 rows of data
Adding trend indicators...
Adding momentum indicators...
Adding volume indicators...
Adding volatility indicators...
Preprocessed data shape: (51, 23)
Step clean_inference_data has finished in 8.457s.
Step predict has started.
Found model linear_regression_BTC_USDT_1h version 4
Successfully loaded model from models:/linear_regression_BTC_USDT_1h/4
Input data shape: (1, 50, 20)
Prediction failed: 'StepArtifact' object has no attribute 'predict'
Failed to run step predict after 1 retries. Exiting.
'StepArtifact' object has no attribute 'predict'
Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py", line 255, in launch
    self._run_step(
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py", line 376, in _run_step
    self._run_step_without_step_operator(
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py", line 461, in _run_step_without_step_operator
    runner.run(
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\zenml\orchestrators\step_runner.py", line 192, in run
    return_values = step_instance.call_entrypoint(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\venv\Lib\site-packages\zenml\steps\base_step.py", line 562, in call_entrypoint
    return self.entrypoint(**validated_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Documents\price prediction pipelines\steps\prediction.py", line 78, in predict
    predictions = model.predict(reshaped_data)
                  ^^^^^^^^^^^^^
AttributeError: 'StepArtifact' object has no attribute 'predict'
Pipeline run crypto_inference_pipeline-2025_03_29-09_31_13_764124 failed.
╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ C:\Users\User\OneDrive\Documents\price prediction pipelines\run_inference_pipeline.py:34 │
│ in <module>                                                                              │
│                                                                                          │
│   31                                                                                     │
│   32                                                                                     │
│   33 if __name__ == "__main__":                                                          │
│ ❱ 34 │   main()                                                                          │
│   35                                                                                     │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction pipelines\run_inference_pipeline.py:30 │
│ in main                                                                                  │
│                                                                                          │
│   27 def main():                                                                         │
│   28 │   """Execute the inference pipeline and display results"""                        │
│   29 │   print("Starting inference process...")                                          │
│ ❱ 30 │   result = run_inference()                                                        │
│   31                                                                                     │
│   32                                                                                     │
│   33 if __name__ == "__main__":                                                          │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction pipelines\run_inference_pipeline.py:25 │
│ in run_inference                                                                         │
│                                                                                          │
│   22 │   )                                                                               │
│   23 │                                                                                   │
│   24 │   # Run the inference pipeline                                                    │
│ ❱ 25 │   return inference_pipeline(config)                                               │
│   26                                                                                     │
│   27 def main():                                                                         │
│   28 │   """Execute the inference pipeline and display results"""                        │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\pipelines\pipeline_definition.py:1411 in __call__ │
│                                                                                          │
│   1408 │   │   │   return self.entrypoint(*args, **kwargs)                               │
│   1409 │   │                                                                             │
│   1410 │   │   self.prepare(*args, **kwargs)                                             │
│ ❱ 1411 │   │   return self._run()                                                        │
│   1412 │                                                                                 │
│   1413 │   def _call_entrypoint(self, *args: Any, **kwargs: Any) -> None:                │
│   1414 │   │   """Calls the pipeline entrypoint function with the given arguments.       │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\pipelines\pipeline_definition.py:831 in _run      │
│                                                                                          │
│    828 │   │   │   │   │   │   "`zenml login --local`."                                  │
│    829 │   │   │   │   │   )                                                             │
│    830 │   │   │                                                                         │
│ ❱  831 │   │   │   deploy_pipeline(                                                      │
│    832 │   │   │   │   deployment=deployment, stack=stack, placeholder_run=run           │
│    833 │   │   │   )                                                                     │
│    834 │   │   │   if run:                                                               │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\pipelines\run_utils.py:161 in deploy_pipeline     │
│                                                                                          │
│   158 │   │   │   # status to `Failed`                                                   │
│   159 │   │   │   publish_failed_pipeline_run(placeholder_run.id)                        │
│   160 │   │                                                                              │
│ ❱ 161 │   │   raise e                                                                    │
│   162 │   finally:                                                                       │
│   163 │   │   constants.SHOULD_PREVENT_PIPELINE_EXECUTION = previous_value               │
│   164                                                                                    │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\pipelines\run_utils.py:145 in deploy_pipeline     │
│                                                                                          │
│   142 │   constants.SHOULD_PREVENT_PIPELINE_EXECUTION = True                             │
│   143 │   try:                                                                           │
│   144 │   │   stack.prepare_pipeline_deployment(deployment=deployment)                   │
│ ❱ 145 │   │   stack.deploy_pipeline(                                                     │
│   146 │   │   │   deployment=deployment,                                                 │
│   147 │   │   │   placeholder_run=placeholder_run,                                       │
│   148 │   │   )                                                                          │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\stack\stack.py:825 in deploy_pipeline             │
│                                                                                          │
│   822 │   │   │   deployment: The pipeline deployment.                                   │
│   823 │   │   │   placeholder_run: An optional placeholder run for the deployment.       │
│   824 │   │   """                                                                        │
│ ❱ 825 │   │   self.orchestrator.run(                                                     │
│   826 │   │   │   deployment=deployment, stack=self, placeholder_run=placeholder_run     │
│   827 │   │   )                                                                          │
│   828                                                                                    │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\base_orchestrator.py:249 in run     │
│                                                                                          │
│   246 │   │   │   logger.debug("Skipping client-side caching.")                          │
│   247 │   │                                                                              │
│   248 │   │   try:                                                                       │
│ ❱ 249 │   │   │   if metadata_iterator := self.prepare_or_run_pipeline(                  │
│   250 │   │   │   │   deployment=deployment,                                             │
│   251 │   │   │   │   stack=stack,                                                       │
│   252 │   │   │   │   environment=environment,                                           │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\local\local_orchestrator.py:78 in   │
│ prepare_or_run_pipeline                                                                  │
│                                                                                          │
│    75 │   │   │   │   │   step_name,                                                     │
│    76 │   │   │   │   )                                                                  │
│    77 │   │   │                                                                          │
│ ❱  78 │   │   │   self.run_step(                                                         │
│    79 │   │   │   │   step=step,                                                         │
│    80 │   │   │   )                                                                      │
│    81                                                                                    │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\base_orchestrator.py:281 in         │
│ run_step                                                                                 │
│                                                                                          │
│   278 │   │   │   step=step,                                                             │
│   279 │   │   │   orchestrator_run_id=self.get_orchestrator_run_id(),                    │
│   280 │   │   )                                                                          │
│ ❱ 281 │   │   launcher.launch()                                                          │
│   282 │                                                                                  │
│   283 │   @staticmethod                                                                  │
│   284 │   def requires_resources_in_orchestration_environment(                           │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py:255 in launch      │
│                                                                                          │
│   252 │   │   │   │   │   │   │   │   │   return None                                    │
│   253 │   │   │   │   │   │   │   │                                                      │
│   254 │   │   │   │   │   │   │   │   force_write_logs = _bypass                         │
│ ❱ 255 │   │   │   │   │   │   │   self._run_step(                                        │
│   256 │   │   │   │   │   │   │   │   pipeline_run=pipeline_run,                         │
│   257 │   │   │   │   │   │   │   │   step_run=step_run,                                 │
│   258 │   │   │   │   │   │   │   │   last_retry=last_retry,                             │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py:376 in _run_step   │
│                                                                                          │
│   373 │   │   │   │   │   last_retry=last_retry,                                         │
│   374 │   │   │   │   )                                                                  │
│   375 │   │   │   else:                                                                  │
│ ❱ 376 │   │   │   │   self._run_step_without_step_operator(                              │
│   377 │   │   │   │   │   pipeline_run=pipeline_run,                                     │
│   378 │   │   │   │   │   step_run=step_run,                                             │
│   379 │   │   │   │   │   step_run_info=step_run_info,                                   │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\step_launcher.py:461 in             │
│ _run_step_without_step_operator                                                          │
│                                                                                          │
│   458 │   │   if last_retry:                                                             │
│   459 │   │   │   os.environ[ENV_ZENML_IGNORE_FAILURE_HOOK] = "false"                    │
│   460 │   │   runner = StepRunner(step=self._step, stack=self._stack)                    │
│ ❱ 461 │   │   runner.run(                                                                │
│   462 │   │   │   pipeline_run=pipeline_run,                                             │
│   463 │   │   │   step_run=step_run,                                                     │
│   464 │   │   │   input_artifacts=input_artifacts,                                       │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\orchestrators\step_runner.py:192 in run           │
│                                                                                          │
│   189 │   │   │                                                                          │
│   190 │   │   │   step_failed = False                                                    │
│   191 │   │   │   try:                                                                   │
│ ❱ 192 │   │   │   │   return_values = step_instance.call_entrypoint(                     │
│   193 │   │   │   │   │   **function_params                                              │
│   194 │   │   │   │   )                                                                  │
│   195 │   │   │   except BaseException as step_exception:  # noqa: E722                  │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction                                        │
│ pipelines\venv\Lib\site-packages\zenml\steps\base_step.py:562 in call_entrypoint         │
│                                                                                          │
│    559 │   │   │   │   "pydantic error above for more details."                          │
│    560 │   │   │   ) from e                                                              │
│    561 │   │                                                                             │
│ ❱  562 │   │   return self.entrypoint(**validated_args)                                  │
│    563 │                                                                                 │
│    564 │   @property                                                                     │
│    565 │   def name(self) -> str:                                                        │
│                                                                                          │
│ C:\Users\User\OneDrive\Documents\price prediction pipelines\steps\prediction.py:78 in    │
│ predict                                                                                  │
│                                                                                          │
│    75 │   │   │   │   # Reshape to (batch_size, sequence_length * features)              │
│    76 │   │   │   │   batch_size, seq_len, n_features = clean_data.shape                 │
│    77 │   │   │   │   reshaped_data = clean_data.reshape(batch_size, seq_len * n_feature │
│ ❱  78 │   │   │   │   predictions = model.predict(reshaped_data)                         │
│    79 │   │   │   else:                                                                  │
│    80 │   │   │   │   predictions = model.predict(clean_data)                            │
│    81                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StepArtifact' object has no attribute 'predict'

**Comment by bcdurak** [comment]
Hey @Nomanriaz786 , thank you for reporting the issue. Could you provide more info about your zenml installation (can be summarized through `zenml info`) and the pipeline you are trying to run?
