### ISSUE TITLE
ServiceAccount fails to create when adding annotation for IAM role [BUG]: 

### ISSUE THREAD

**Issue by Fmowers** [zenml-io/zenml#2233]
### Contact Details [Optional]

fmowers@icloud.com

### System Information

ZenML version > 52

### What happened?

When deploying zenml using the helm chart. I received an error while upgrading to the latest version. The error went as follows `failed to create resource: ServiceAccount "zenml" is invalid: metadata.labels: Invalid value`. I did not make any config changes relating to the service account and the current config was deployed successfully using v43. Upon further investigation, I found that the serviceaccount template is missing the `annotation:` key that it had previously. This is causing the intended annotation to be added as a label. The validation logic for labels and annotations must be different because it rejects value and throws an error. After manually editing the template myself the deployment completed as expected.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@stefannica @wjayesh can you take a look please

**Comment by wjayesh** [comment]
Thank you so much, @Fmowers for pointing this out. I've made a [PR](https://github.com/zenml-io/zenml/pull/2234) to fix this for future releases. I also see that this bug was introduced with the version 0.50.0 and will explore the possibility of making a patch and repushing the older tags (or at least a note in the documentation).

**Comment by wjayesh** [comment]
Helloo @Fmowers, we have now updated all releases starting from 0.50.0 to the latest with this fix and the helm chart hosted on ECR should also have this fix. Thanks, again! I'll close the issue now :)
