### ISSUE TITLE
A docs update for incorrect import in docs/book/user-guide/starter-guide/track-ml-models.md

### ISSUE THREAD

**Issue by yo-harsh** [zenml-io/zenml#2278]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

> ## Pre-requisites
> Please ensure you have done the following:
> 
> * [x]  I have read the **CONTRIBUTING.md** document.
> * [x]  If my change requires a change to docs, I have updated the documentation accordingly.
> * [x]  I have added tests to cover my changes.
> * [ ]  I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
> * [ ]  If my changes require changes to the dashboard, these changes are communicated/requested.
> 
> ## Types of changes
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> * [ ]  Other (add details above)

**Comment by htahir1** [comment]
Closed by #2279
