### ISSUE TITLE
[BUG]: service daemon is not running

### ISSUE THREAD

**Issue by Ga0512** [zenml-io/zenml#2369]
### Contact Details [Optional]

gabrielmurilocicotoste6@gmail.com

### System Information

RuntimeError: Failed to start service MLFlowDeploymentService[e55e97f5-1fc7-49ac-9158-5de4e1e1a81d] (type: model-serving, flavor: mlflow)  
  Administrative state: `active`
  Operational state: `inactive`
  Last status message: 'service daemon is not running'
For more information on the service status, please see the following log file:
C:\Users\edney\AppData\Roaming\zenml\local_stores\3e2793a0-8446-4b32-9980-89ace8642081\e55e97f5-1fc7-49ac-9158-5de4e1e1a81d\service.log

### What happened?

Hi!

I'm trying to deploy my model using MLFlowDeploymentService from zenml.integrations.mlflow.services but i'm getting this error message:

RuntimeError: Failed to start service MLFlowDeploymentService[e55e97f5-1fc7-49ac-9158-5de4e1e1a81d] (type: model-serving, flavor: mlflow)  
  Administrative state: `active`
  Operational state: `inactive`
  Last status message: 'service daemon is not running'
For more information on the service status, please see the following log file:
C:\Users\edney\AppData\Roaming\zenml\local_stores\3e2793a0-8446-4b32-9980-89ace8642081\e55e97f5-1fc7-49ac-9158-5de4e1e1a81d\service.log

*Nothing in service.log

### Relevant log output

RuntimeError: Failed to start service MLFlowDeploymentService[e55e97f5-1fc7-49ac-9158-5de4e1e1a81d] (type: model-serving, flavor: mlflow)  
  Administrative state: `active`
  Operational state: `inactive`
  Last status message: 'service daemon is not running'
For more information on the service status, please see the following log file:
C:\Users\edney\AppData\Roaming\zenml\local_stores\3e2793a0-8446-4b32-9980-89ace8642081\e55e97f5-1fc7-49ac-9158-5de4e1e1a81d\service.log

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@Ga0512 Try setting the env variable `ZENML_LOGGING_VERBOSITY=DEBUG` and see if you can get more insights.

Also can you tell us what python verison, zenml version, mlflow version, and OS you're on? Also some code to replicate would be nice.

Thanks!

**Comment by Ga0512** [comment]
> @Ga0512 Try setting the env variable `ZENML_LOGGING_VERBOSITY=DEBUG` and see if you can get more insights.
> 
> Also can you tell us what python verison, zenml version, mlflow version, and OS you're on? Also some code to replicate would be nice.
> 
> Thanks!

Hey!

Python 3.11.3
Zenml 0.54.0
Mlflow 2.92
Windowns 10

The file I run is this, in this case, I run python run_deployment.py --config deploy, this inside an environment variable:

```
from typing import cast

import click
from pipelines.deployment_pipeline import (
    continuous_deployment_pipeline,
    inference_pipeline,
)
from rich import print
from zenml.integrations.mlflow.mlflow_utils import get_tracking_uri
from zenml.integrations.mlflow.model_deployers.mlflow_model_deployer import (
    MLFlowModelDeployer,
)
from zenml.integrations.mlflow.services import MLFlowDeploymentService

DEPLOY = "deploy"
PREDICT = "predict"
DEPLOY_AND_PREDICT = "deploy_and_predict"


@click.command()
@click.option(
    "--config",
    "-c",
    type=click.Choice([DEPLOY, PREDICT, DEPLOY_AND_PREDICT]),
    default=DEPLOY_AND_PREDICT,
    help="Optionally you can choose to only run the deployment "
    "pipeline to train and deploy a model (`deploy`), or to "
    "only run a prediction against the deployed model "
    "(`predict`). By default both will be run "
    "(`deploy_and_predict`).",
)
@click.option(
    "--min-accuracy",
    default=0.92,
    help="Minimum accuracy required to deploy the model",
)
def main(config: str, min_accuracy: float):
    """Run the MLflow example pipeline."""
    # get the MLflow model deployer stack component
    mlflow_model_deployer_component = MLFlowModelDeployer.get_active_model_deployer()
    deploy = config == DEPLOY or config == DEPLOY_AND_PREDICT
    predict = config == PREDICT or config == DEPLOY_AND_PREDICT

    if deploy:
        # Initialize a continuous deployment pipeline run
        continuous_deployment_pipeline(
            data_path = './data/olist_customers_dataset.csv',
            min_accuracy=min_accuracy,
            workers=3,
            timeout=60,
        )

    if predict:
        # Initialize an inference pipeline run
        inference_pipeline(
            pipeline_name="continuous_deployment_pipeline",
            pipeline_step_name="mlflow_model_deployer_step",
        )

    print(
        "You can run:\n "
        f"[italic green]    mlflow ui --backend-store-uri '{get_tracking_uri()}"
        "[/italic green]\n ...to inspect your experiment runs within the MLflow"
        " UI.\nYou can find your runs tracked within the "
        "`mlflow_example_pipeline` experiment. There you'll also be able to "
        "compare two or more runs.\n\n"
    )

    # fetch existing services with same pipeline name, step name and model name
    existing_services = mlflow_model_deployer_component.find_model_server(
        pipeline_name="continuous_deployment_pipeline",
        pipeline_step_name="mlflow_model_deployer_step",
        model_name="model",
    )

    if existing_services:
        service = cast(MLFlowDeploymentService, existing_services[0])
        if service.is_running:
            print(
                f"The MLflow prediction server is running locally as a daemon "
                f"process service and accepts inference requests at:\n"
                f"    {service.prediction_url}\n"
                f"To stop the service, run "
                f"[italic green]`zenml model-deployer models delete "
                f"{str(service.uuid)}`[/italic green]."
            )
        elif service.is_failed:
            print(
                f"The MLflow prediction server is in a failed state:\n"
                f" Last state: '{service.status.state.value}'\n"
                f" Last error: '{service.status.last_error}'"
            )
    else:
        print(
            "No MLflow prediction server is currently running. The deployment "
            "pipeline must run first to train a model and deploy it. Execute "
            "the same command with the `--deploy` argument to deploy a model."
        )


if __name__ == "__main__":
    main()
```

The pipelines.deployment module:

```

**Comment by safoinme** [comment]
@Ga0512 Unfortunately MLflow deployment isn't supported yet for windows

**Comment by Luismbpr** [comment]
I have the same issue but I am running this on a Mac OS. Is there any solution to this?

**Comment by Ga0512** [comment]
> I have the same issue but I am running this on a Mac OS. Is there any solution to this?
> 
> Python version 3.9.18
> 
> Package Version
> 
> catboost 1.0.5 MarkupSafe 2.1.5 mlflow 2.10.2 mlserver 1.5.0 mlserver-mlflow 1.5.0 numpy 1.26.4 optuna 2.10.0 pydantic 1.10.14 scikit-learn 1.4.1.post1 streamlit 1.32.1 tqdm 4.66.2 zenml 0.55.5

Are you doing the Freecodecamp MLOps course? (https://www.youtube.com/watch?v=-dJPoLm_gtE) He used a Mac throughout the course and managed to overcome this problem.

**Comment by Luismbpr** [comment]
> Are you doing the Freecodecamp MLOps course? 

I am doing that course indeed and tried many times to solve it but I still cannot manage to do it. I might have not understood something he did but I think I did everything he did and yet cannot deploy it.

**Comment by strickvl** [comment]
Could you try replacing the `requirements.txt` file contents with this:

```
catboost==1.0.4
joblib>=1.1.0
lightgbm==4.1.0
optuna==2.10.0
streamlit==1.29.0
xgboost==2.0.3
markupsafe==1.1.1
zenml>=0.52.0
scikit-learn>=1.3.2
altair
```

Then reinstall the packages (`pip install -r requirements.txt` etc in a fresh env), then `zenml disconnect` and `zenml down` and then try `zenml up` again?

**Comment by Luismbpr** [comment]
> Could you try replacing the `requirements.txt` file contents with this:
> 
> ```
> catboost==1.0.4
> joblib>=1.1.0
> lightgbm==4.1.0
> optuna==2.10.0
> streamlit==1.29.0
> xgboost==2.0.3
> markupsafe==1.1.1
> zenml>=0.52.0
> scikit-learn>=1.3.2
> altair
> ```
> 
> Then reinstall the packages (`pip install -r requirements.txt` etc in a fresh env), then `zenml disconnect` and `zenml down` and then try `zenml up` again?

Hello. First of all thank you for replying.

1.1) I did try to install those versions (first by ```bash pip install -r requirements.txt```) and did not work.
1.2) Then tried installing one by one and also could not do it. Pip installer did not let me install those versions

2) I did the zenml disconnect, zenml down, zenml up many times and never got it to work.

3) Tried creating different stacks, experiment-trackers, model-deployers and set them up to be the ones working. Tried this many times

4) Something that seemed to work but not entirely sure was using those two pieces of code on the 
https://stackoverflow.com/questions/52671926/rails-may-have-been-in-progress-in-another-thread-when-fork-was-called

Was appending these two lines of code on the .zshrc file
```shell
% vim ~/.zshrc 
appending those two lines of code:
```Markdown
 ## for MLOPS deployment
export DISABLE_SPRING=true
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

% source ~/.zshrc
```
Then creating a new stack, experiment-tracker, model-deployer and setting them.

I am still not sure what was the piece that made it work. I have not finished the course (almost done now) but so far it seems to be working, or at least not displaying any errors.

**Comment by strickvl** [comment]
Correct. That's also something we do in our CI to allow things to work on
some Mac environments. I'll add something to our docs to that effect. It
seems like we should make that clear.

**Comment by Luismbpr** [comment]
> Correct. That's also something we do in our CI to allow things to work on some Mac environments. I'll add something to our docs to that effect. It seems like we should make that clear.

Thank you. That would be really helpful.

Just a question now that that seemed to be the solution.

```Shell
 ## for MLOPS deployment
export DISABLE_SPRING=true
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

Do we need to use both of these? or which one is the one that works?

**Comment by strickvl** [comment]
For Macs, I think `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` is the key one.

**Comment by Luismbpr** [comment]
> For Macs, I think `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` is the key one.

Good to know. Thank you for your help.
