### ISSUE TITLE
[BUG]: initialisation breaks if api.segment.io is blocked on network

### ISSUE THREAD

**Issue by archena** [zenml-io/zenml#247]
### What happened?

When running `zenml` init, I saw the following output:

```
$ zenml init
Initializing at /home/matt/projects/zenml-test
INFO:backoff:Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e14b28898>: Failed to establish a new connection: [Errno 111] Connection refused')))
ZenML repo initialized at /home/matt/projects/zenml-test
INFO:backoff:Backing off send_request(...) for 1.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e142ace10>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 1.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e142aceb8>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 4.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e142ac978>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 5.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e142cf0b8>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 24.4s (requests.exceptions.ConnectionError: 
... etc ...
```

**Cause**

My `/etc/hosts` file includes a blacklist of all sorts of advertising and tracking domains, which happens to include `api.segment.io`. After removing this line from `/etc/hosts`, ZenML works correctly.

**Expected behaviour**

While there's certainly a good argument to be made that this is a local problem due to my slightly obscure setup, it would still be good if `zenml init` could fail gracefully when this domain is unreachable.

### Reproduction steps

1. Add the line `api.segment.io` to `/etc/hosts`
2. Run `zenml init` in a new project.
3. Initialisation hangs while it tries to reach the Segment API
...

### ZenML Version

0.5.0rc2

### Python Version

3.9

### OS Type

Ubuntu (or other Linux Flavor)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Thanks @archena ! I thought we had a hard try catch here to never cause the segment call to interfere with the main thread: https://github.com/zenml-io/zenml/blob/main/src/zenml/utils/analytics_utils.py#L129. I wonder where its coming from, it cant be the method I referenced. I'll investigate

**Comment by archena** [comment]
Thanks @htahir1. Looking at the code here, and in `analytics-python`, I suspect the relevant exception doesn't actually make its way back to that catch. In the analytics library, calling `track` puts an event on a queue - https://github.com/segmentio/analytics-python/blob/master/segment/analytics/client.py#L122 - and it appears to get stuck in a backoff loop.

**Comment by htahir1** [comment]
Perhaps we have to configure the analytics library with the proper exception handling then i.e. having retries set to 1. Will find a way and make it part of 0.5.6
