### ISSUE TITLE
[BUG]: Critical Vulnerability related to file access

### ISSUE THREAD

**Issue by rook1337** [zenml-io/zenml#2488]
### System Information

zenml cloud

### What happened?

Hello team,
Please check here: https://huntr.com/bounties/f24b2216-6a4b-42a1-becb-9b47e6cf117f

Its a critical vulnerability, please check and validate as soon as possible

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
Fixed in 0.55.5 by https://github.com/zenml-io/zenml/pull/2490
