### ISSUE TITLE
[BUG]: Unable to open the quickstart colab notebook

### ISSUE THREAD

**Issue by soumya1984** [zenml-io/zenml#2504]
### Contact Details [Optional]

cse.soumya@gmail.com

### System Information

NA

### What happened?

Quickstart colab link not working 

### Reproduction steps

1. clicking on below link doen't work 
https://colab.research.google.com/github/zenml-io/zenml/blob/main/examples/quickstart/run.ipynb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
@soumya1984 thank you for the report. Can I ask where you found this link? It'd help us to fix it. Thanks!

**Comment by strickvl** [comment]
I have a feeling it was on [this page](https://github.com/zenml-io/zenml/tree/main/examples/quickstart). If you try https://colab.research.google.com/github/zenml-io/zenml/blob/main/examples/quickstart/quickstart.ipynb it should work. Apologies for the faulty link. I've fixed that here now: https://github.com/zenml-io/zenml/pull/2505

If there was somewhere else where you were pointed towards this faulty link, please do let me know!
