### ISSUE TITLE
[BUG]: Node Selector doesn"t work on job

### ISSUE THREAD

**Issue by didlawowo** [zenml-io/zenml#2530]
### Contact Details [Optional]

didelot.c@gmail.com

### System Information

helm install zenml 0.55.5

### What happened?

node selector not working on job db migration so in mixed architecture cluster, can fail cause not arm64 compliant

### Reproduction steps

1. deploy zen using argo
2. put not selector in chart
3.look at the migration job crash
...

### Relevant log output

```shell
exec /usr/local/bin/zenml: exec format error
Stream closed EOF for mlops/zenml-db-migration-4l4j4 (zenml-db-migration)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
Fixed with https://github.com/zenml-io/zenml/pull/2531 and will be in the next ZenML release.
