### ISSUE TITLE
[BUG]: Integration Materializers links not working (Documentation)

### ISSUE THREAD

**Issue by Dev-Khant** [zenml-io/zenml#2537]
### System Information

Issue with Documentation

### What happened?

When visiting https://docs.zenml.io/user-guide/advanced-guide/data-management/handle-custom-data-types, I tried opening links for `Integration materializers` and none are working except for the `Built-In Materializers`.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dev-Khant** [comment]
@strickvl Can I fix this up?

**Comment by strickvl** [comment]
Oh sorry, didn't see the message! It was a super quick fix in any case. Thank you for reporting it!

**Comment by Dev-Khant** [comment]
Glad I could help.

**Comment by Dev-Khant** [comment]
Also @strickvl This link is also not working https://github.com/zenml-io/zenml/blob/release/0.55.5/docs/book/user-guide/component-guide/integration-overview.md

<img width="911" alt="Screenshot 2024-03-19 at 2 33 24 PM" src="https://github.com/zenml-io/zenml/assets/57898986/70d58c17-bbc8-4a41-8dad-540808a30bb8">

**Comment by strickvl** [comment]
Thanks fixed here:
https://github.com/zenml-io/zenml/pull/2538/commits/9dab39977e873d2f312a8abbe7dd3d919dead460
