### ISSUE TITLE
[BUG]: File priviledge changing timing, potential TOCTOU

### ISSUE THREAD

**Issue by nevercodecorrect** [zenml-io/zenml#2566]
### System Information

default

### What happened?

The email delivery failed and I may post here.
When I played with zenml, I found a few potential file-based TOCTOU issue in https://github.com/zenml-io/zenml/blob/aa72f8b4a3d1de6db52ed19c5663a17416ca2841/src/zenml/zen_stores/sql_zen_store.py#L598
and https://github.com/zenml-io/zenml/blob/aa72f8b4a3d1de6db52ed19c5663a17416ca2841/src/zenml/zen_stores/rest_zen_store.py#L359

The file based TOCTOU is that an local attacker could steal the data or 
change the file between the check of the file and the actual use of the 
file as described in https://wiki.sei.cmu.edu/confluence/display/c/FIO45-C.+Avoid+TOCTOU+race+conditions+while+accessing+files

In the source code, a malicious local actor could open the file before 
the permission change and steal the sensitive information. This is a 
issue similar to https://github.com/advisories/GHSA-p867-fxfr-ph2w

A way to fix this vulnerability is create the file with permissions defined like changing<br>

with open(file_path, "w") as f:

to something like
fd = os.open(self.filename, flags=os.O_RDWR | os.O_CREAT, mode=stat.S_IRUSR | stat.S_IWUSR, ) 

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
Thank you for reporting this. We'll take a look into it.

**Comment by strickvl** [comment]
Closing this as it has been addressed.

**Comment by strickvl** [comment]
Thank you for reporting!
