### ISSUE TITLE
[BUG]: Make sure that graphviz is installed for that integration to work

### ISSUE THREAD

**Issue by htahir1** [zenml-io/zenml#266]
### Contact Details [Optional]

support@zenml.io

### What happened?

The [Graphviz integration](https://github.com/zenml-io/zenml/blob/main/src/zenml/integrations/graphviz/visualizers/pipeline_run_dag_visualizer.py) as showcased in the [dag_visualizer](https://github.com/zenml-io/zenml/tree/main/examples/dag_visualizer) example does not check if the graphviz library is actually installed or not in its `setup.sh`. Therefore, if the user does `zenml example run dag_visualizer` it would fail if graphviz isnt installed.

What should happen is that it should gracefully fail and say to the user that graphviz needs to be installed for this to work. We can do this within the [check_installation](https://github.com/zenml-io/zenml/blob/main/src/zenml/integrations/graphviz/__init__.py) function with a special override.

### Reproduction steps

1. pip install zenml
2. git init
3. zenml init
4. zenml example pull
5. zenml example run dag_visualizer

It would fail at this point if graphviz is not installed. 

### ZenML Version

0.5.5

### Python Version

3.7

### OS Type

Ubuntu (or other Linux Flavor)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kamalesh0406** [comment]
Has this issue been solved?

**Comment by AlexejPenner** [comment]
@kamalesh0406 no this is still open

**Comment by kamalesh0406** [comment]
Okay, I have a question regarding the feature you want to add. I tried to recreate the steps given above and when I run the final command zenml example run dag_visualizer, I get the following prompt:

```This example requires some additional setup.
Are you sure you want to install the following packages to the current environment?
['graphviz>=0.17'] [y/N]: y ```

Isn't this enough? Is the issue regarding how it should fail if the user types in N and proceeds further.

**Comment by AlexejPenner** [comment]
This installs the python package only. However the python package requires you to have graphviz installed on your machine for example with apt install. https://graphviz.org/download/

For this issue it should be verified that graphviz is actually installed on the machine as well.

**Comment by kamalesh0406** [comment]
Okay got you. I will try to remove graphviz from my system and recreate this error. Thanks!

**Comment by htahir1** [comment]
Closing in lieu of #284
