### ISSUE TITLE
[BUG]: Logs are not working

### ISSUE THREAD

**Issue by PinkDraconian** [zenml-io/zenml#2661]
### System Information

ZENML_LOCAL_VERSION: 0.56.4
ZENML_SERVER_VERSION: 0.56.4
ZENML_SERVER_DATABASE: mysql
ZENML_SERVER_DEPLOYMENT_TYPE: cloud
ZENML_CONFIG_DIR: /home/kali/.config/zenml
ZENML_LOCAL_STORE_DIR: /home/kali/.config/zenml/local_stores
ZENML_SERVER_URL: https://41cd22f5-zenml.cloudinfra.zenml.io
ZENML_ACTIVE_REPOSITORY_ROOT: None
PYTHON_VERSION: 3.11.5
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'linux', 'linux_distro': 'kali', 'linux_distro_like': 'debian', 'linux_distro_version': '2023.4'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: vanroeyrobbe@hotmail.com
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: d8d1ae9a-d059-4616-b99e-502756abc803
ANALYTICS_USER_ID: 17b76fc4-9111-4ab2-859b-7f8a57f3d887
ANALYTICS_SERVER_ID: b1731e52-5d65-4475-a3ef-19dff170db8b
INTEGRATIONS: ['bitbucket', 'github', 'hyperai', 'kaniko', 'pillow', 'pytorch', 'scipy', 'sklearn']
PACKAGES: {'ropgadget': '7.4', 'sqlalchemy': '1.4.41', 'sqlalchemy-utils': '0.38.3', 'aardwolf': '0.2.8', 'aioconsole': '0.7.0', 'alembic': '1.8.1', 'asyauth': '0.0.20', 'asysocks': '0.2.12', 'azure-common': '1.1.28', 'azure-core': 
'1.30.1', 'azure-mgmt-core': '1.4.0', 'azure-mgmt-resource': '23.0.1', 'bcrypt': '4.0.1', 'bloodhound': '1.7.2', 'capstone': '5.0.1', 'click': '8.1.3', 'click-params': '0.3.0', 'cloudpickle': '2.2.1', 'colored-traceback': '0.3.0', 
'comm': '0.2.2', 'docker': '6.1.3', 'httplib2': '0.19.1', 'huggingface': '0.0.1', 'intervaltree': '3.1.0', 'ipywidgets': '8.1.2', 'isodate': '0.6.1', 'jupyterlab-widgets': '3.0.10', 'markdown-it-py': '2.2.0', 'minikerberos': '0.4.4', 
'plumbum': '1.8.2', 'pwn': '1.0', 'pwntools': '4.12.0', 'pycryptodome': '3.20.0', 'pyelftools': '0.31', 'pyparsing': '2.4.7', 'rpyc': '6.0.0', 'sqlalchemy2-stubs': '0.0.2a38', 'sqlmodel': '0.0.8', 'unicorn': '2.0.1.post1', 'unix-ar': 
'0.2.1', 'validators': '0.18.2', 'widgetsnbextension': '4.0.10', 'zenml': '0.56.4', 'apscheduler': '3.10.4', 'automat': '20.2.0', 'babel': '2.11.0', 'bottleneck': '1.3.5', 'brotli': '1.1.0', 'deprecated': '1.2.14', 'flask': '2.2.2', 
'flask-babel': '1.0.0', 'flask-caching': '1.11.1', 'flask-compress': '1.14', 'flask-themes2': '1.0.1', 'gitpython': '3.1.42', 'heapdict': '1.0.1', 'jinja2': '3.1.2', 'js2py': '0.74', 'mako': '1.3.2', 'markdown': '3.4.1', 'markupsafe': 
'2.1.1', 'office365-rest-python-client': '2.5.5', 'protego': '0.1.16', 'pydispatcher': '2.0.5', 'pygithub': '2.3.0', 'pyjwt': '2.7.0', 'pymysql': '1.0.3', 'pynacl': '1.5.0', 'pyqt5-sip': '12.11.0', 'pysocks': '1.7.1', 'pywavelets': 
'1.4.1', 'pyyaml': '6.0.1', 'pygments': '2.15.1', 'qdarkstyle': '3.0.2', 'qtawesome': '1.2.2', 'qtpy': '2.2.0', 'rtree': '1.0.1', 'scrapy': '2.8.0', 'secretstorage': '3.3.1', 'send2trash': '1.8.0', 'sphinx': '5.0.2', 'tbb': '0.2', 
'twisted': '22.10.0', 'unidecode': '1.2.0', 'werkzeug': '2.2.3', 'xlsxwriter': '3.2.0', 'aiobotocore': '2.5.0', 'aiodns': '3.1.1', 'aiofiles': '22.1.0', 'aiohttp': '3.8.5', 'aiohttp-cors': '0.7.0', 'aioitertools': '0.7.1', 'aiosignal': 
'1.2.0', 'aiosqlite': '0.18.0', 'alabaster': '0.7.12', 'anaconda-anon-usage': '0.4.2', 'anaconda-catalogs': '0.2.0', 'anaconda-client': '1.12.1', 'anaconda-cloud-auth': '0.1.3', 'anaconda-navigator': '2.5.0', 'anaconda-project': 
'0.11.1', 'annotated-types': '0.6.0', 'anyio': '3.5.0', 'appdirs': '1.4.4', 'argon2-cffi': '21.3.0', 'argon2-cffi-bindings': '21.2.0', 'arrow': '1.2.3', 'ascii-colors': '0.2.2', 'astor': '0.8.1', 'astroid': '2.14.2', 'astropy': '5.1', 
'asttokens': '2.0.5', 'async-timeout': '4.0.2', 'atomicwrites': '1.4.0', 'attrs': '22.1.0', 'autocfg': '0.0.8', 'autopep8': '1.6.0', 'backcall': '0.2.0', 'backoff': '2.2.1', 'backports.functools-lru-cache': '1.6.4', 
'backports.tempfile': '1.0', 'backports.weakref': '1.0.post1', 'beartype': '0.15.0', 'beautifulsoup4': '4.12.3', 'bidict': '0.23.1', 'binaryornot': '0.4.4', 'bitmath': '1.3.3.1', 'black': '0.0', 'bleach': '4.1.0', 'bokeh': '3.2.1', 
'boltons': '21.0.0', 'boto3': '1.34.39', 'botocore': '1.34.39', 'bracex': '2.4', 'brotlipy': '0.7.0', 'cachelib': '0.12.0', 'cachetools': '5.3.2', 'certifi': '2023.7.22', 'cffi': '1.15.1', 'chardet': '4.0.0', 'charset-normalizer': 
'2.0.4', 'cheroot': '8.6.0', 'click-option-group': '0.5.6', 'clyent': '1.2.2', 'colorama': '0.4.6', 'colorcet': '3.0.1', 'colorlog': '6.8.2', 'conda': '23.7.4', 'conda-build': '3.26.1', 'conda-content-trust': '0.2.0', 'conda-index': 
'0.3.0', 'conda-libmamba-solver': '23.7.0', 'conda-pack': '0.6.0', 'conda-package-handling': '2.2.0', 'conda-package-streaming': '0.9.0', 'conda-repo-cli': '1.0.75', 'conda-token': '0.4.0', 'conda-verify': '3.4.2', 'constantly': 
'15.1.0', 'contourpy': '1.0.5', 'cookiecutter': '1.7.3', 'cryptography': '42.0.5', 'cssselect': '1.1.0', 'cycler': '0.11.0', 'cytoolz': '0.12.0', 'daal4py': '2023.1.1', 'dask': '2023.6.0', 'datasets': '2.12.0', 'datashader': '0.15.2', 
'datashape': '0.5.4', 'debugpy': '1.6.7', 'decorator': '5.1.1', 'defusedxml': '0.7.1', 'diff-match-patch': '20200713', 'dill': '0.3.6', 'diskcache': '5.6.3', 'distributed': '2023.6.0', 'distro': '1.9.0', 'dnspython': '2.6.1', 
'docstring-to-markdown': '0.11', 'docutils': '0.18.1', 'dpkt': '1.9.8', 'email-validator': '2.1.1', 'entrypoints': '0.4', 'et-xmlfile': '1.1.0', 'exceptiongroup': '1.2.0', 'executing': '0.8.3', 'face': '22.0.0', 'fastapi': '0.109.2', 
'fastapi-sso': '0.10.0', 'fastapi-utils': '0.2.1', 'fastjsonschema': '2.16.2', 'filelock': '3.9.0', 'filetype': '1.2.0', 'flake8': '6.0.0', 'flask-session': '0.6.0', 'fonttools': '4.25.0', 'frozenlist': '1.3.3', 'fsspec': '2024.3.1', 
'future': '0.18.3', 'gensim': '4.3.0', 'geographiclib': '2.0', 'geopy': '2.4.1', 'gitdb': '4.0.11', 'glob2': '0.7', 'glom': '22.1.0', 'gluoncv': '0.10.5.post0', 'gmpy2': '2.1.2', 'google-api-core': '2.17.0', 'google-api-python-client': 
'2.117.0', 'google-auth': '2.27.0', 'google-auth-httplib2': '0.2.0', 'googleapis-common-protos': '1.62.0', 'graphviz': '0.8.4', 'greenlet': '2.0.1', 'gunicorn': '21.2.0', 'h11': '0.14.0', 'h3': '3.7.6', 'h5py': '3.9.0', 'holoviews': 
'1.17.1', 'httpcore': '1.0.2', 'httptools': '0.6.1', 'httpx': '0.26.0', 'huggingface-hub': '0.22.2', 'hvplot': '0.8.4', 'hyperlink': '21.0.0', 'idna': '2.10', 'imagecodecs': '2023.1.23', 'imageio': '2.31.1', 'imagesize': '1.4.1', 
'imbalanced-learn': '0.10.1', 'importlib-metadata': '7.1.0', 'incremental': '21.3.0', 'inflection': '0.5.1', 'iniconfig': '1.1.1', 'intake': '0.6.8', 'ipinfo': '5.0.1', 'ipykernel': '6.25.0', 'ipython': '8.15.0', 'ipython-genutils': 
'0.2.0', 'isort': '5.9.3', 'itemadapter': '0.3.0', 'itemloaders': '1.0.4', 'itsdangerous': '2.0.1', 'jaraco.classes': '3.2.1', 'jaraco.functools': '4.0.0', 'jedi': '0.18.1', 'jeepney': '0.7.1', 'jellyfish': '1.0.1', 'jinja2-time': 
'0.2.0', 'jmespath': '1.0.1', 'joblib': '1.2.0', 'json5': '0.9.6', 'jsonpatch': '1.32', 'jsonpointer': '2.1', 'jsonschema': '4.17.3', 'jupyter': '1.0.0', 'jupyter-bokeh': '3.0.7', 'jupyter-client': '7.4.9', 'jupyter-console': '6.6.3', 
'jupyter-core': '5.3.0', 'jupyter-events': '0.6.3', 'jupyter-server': '1.23.4', 'jupyter-server-fileid': '0.9.0', 'jupyter-server-ydoc': '0.8.0', 'jupyter-ydoc': '0.2.4', 'jupyterlab': '3.6.3', 'jupyterlab-pygments': '0.1.2', 
'jupyterlab-server': '2.22.0', 'kaleido': '0.2.1', 'keyring': '23.13.1', 'kiwisolver': '1.4.4', 'lazy-loader': '0.2', 'lazy-object-proxy': '1.6.0', 'libarchive-c': '2.9', 'libmambapy': '1.5.1', 'linkify-it-py': '2.0.0', 'litellm': 
'1.35.1', 'llvmlite': '0.40.0', 'lmdb': '1.4.1', 'locket': '1.0.0', 'lollms': '9.3.0', 'lxml': '4.9.3', 'lz4': '4.3.2', 'matplotlib': '3.7.2', 'matplotlib-inline': '0.1.6', 'mccabe': '0.7.0', 'mdit-py-plugins': '0.3.0', 'mdurl': 
'0.1.0', 'mistune': '0.8.4', 'mkl-fft': '1.3.8', 'mkl-random': '1.2.4', 'mkl-service': '2.4.0', 'more-itertools': '8.12.0', 'mplcursors': '0.5.3', 'mpmath': '1.3.0', 'msal': '1.26.0', 'msgpack': '1.0.3', 'multidict': '6.0.2', 
'multipledispatch': '0.6.0', 'multiprocess': '0.70.14', 'munkres': '1.1.4', 'mxnet': '1.9.1', 'mxnet-mkl': '1.6.0', 'mypy-extensions': '1.0.0', 'navigator-updater': '0.4.0', 'nbclassic': '0.5.5', 'nbclient': '0.5.13', 'nbconvert': 
'6.5.4', 'nbformat': '5.9.2', 'nest-asyncio': '1.5.6', 'networkx': '3.1', 'nltk': '3.8.1', 'notebook': '6.5.4', 'notebook-shim': '0.2.2', 'numba': '0.57.1', 'numexpr': '2.8.4', 'numpy': '1.26.4', 'numpydoc': '1.5.0', 
'nvidia-cublas-cu12': '12.1.3.1', 'nvidia-cuda-cupti-cu12': '12.1.105', 'nvidia-cuda-nvrtc-cu12': '12.1.105', 'nvidia-cuda-runtime-cu12': '12.1.105', 'nvidia-cudnn-cu12': '8.9.2.26', 'nvidia-cufft-cu12': '11.0.2.54', 
'nvidia-curand-cu12': '10.3.2.106', 'nvidia-cusolver-cu12': '11.4.5.107', 'nvidia-cusparse-cu12': '12.1.0.106', 'nvidia-nccl-cu12': '2.20.5', 'nvidia-nvjitlink-cu12': '12.4.127', 'nvidia-nvtx-cu12': '12.1.105', 'oauthlib': '3.2.2', 
'openai': '1.17.0', 'opencv-python': '4.9.0.80', 'openpyxl': '3.0.10', 'opt-einsum': '3.3.0', 'orjson': '3.10.0', 'outcome': '1.3.0.post0', 'packaging': '23.2', 'paddlepaddle': '2.6.0', 'pandas': '2.2.1', 'pandocfilters': '1.5.0', 
'panel': '1.3.8', 'param': '2.0.2', 'paramiko': '3.4.0', 'parsel': '1.6.0', 'parso': '0.8.3', 'partd': '1.4.0', 'passlib': '1.7.4', 'pathlib': '1.0.1', 'pathspec': '0.10.3', 'pathway': '0.8.0', 'patsy': '0.5.3', 'peewee': '3.17.1', 
'pep8': '1.7.1', 'pexpect': '4.8.0', 'pickleshare': '0.7.5', 'pillow': '10.2.0', 'pip': '23.2.1', 'pipmaster': '0.1.1', 'pkce': '1.0.3', 'pkginfo': '1.9.6', 'platformdirs': '3.10.0', 'plotly': '5.9.0', 'pluggy': '1.4.0', 'ply': '3.11', 
'portalocker': '2.8.2', 'poyo': '0.5.0', 'prometheus-client': '0.14.1', 'prompt-toolkit': '3.0.36', 'protobuf': '4.25.2', 'psutil': '5.9.8', 'ptyprocess': '0.7.0', 'pure-eval': '0.2.2', 'pyopenssl': '23.2.0', 'py-cpuinfo': '8.0.0', 
'pyarrow': '11.0.0', 'pyasn1': '0.4.8', 'pyasn1-modules': '0.2.8', 'pycares': '4.4.0', 'pycodestyle': '2.10.0', 'pycosat': '0.6.4', 'pycparser': '2.21', 'pyct': '0.5.0', 'pycurl': '7.45.2', 'pydantic': '1.10.15', 'pydantic-core': 
'2.16.3', 'pydocstyle': '6.3.0', 'pyerfa': '2.0.0', 'pyfiglet': '0.8.post1', 'pyflakes': '3.0.1', 'pyjsparser': '2.7.1', 'pylint': '2.16.2', 'pylint-venv': '2.3.0', 'pyload-ng': '0.5.0b3.dev81', 'pyls-spyder': '0.4.0', 'pyodbc': 
'4.0.34', 'pypdf2': '3.0.1', 'pyrsistent': '0.18.0', 'pyserial': '3.5', 'pytest': '8.0.2', 'python-dateutil': '2.8.2', 'python-docx': '1.1.0', 'python-dotenv': '0.21.0', 'python-engineio': '4.9.0', 'python-json-logger': '2.0.7', 
'python-lsp-black': '1.2.1', 'python-lsp-jsonrpc': '1.0.0', 'python-lsp-server': '1.7.2', 'python-multipart': '0.0.9', 'python-pptx': '0.6.23', 'python-sat': '0.1.8.dev15', 'python-slugify': '5.0.2', 'python-snappy': '0.6.1', 
'python-socketio': '5.11.1', 'pytoolconfig': '1.2.5', 'pytz': '2023.3.post1', 'pyviz-comms': '2.3.0', 'pywal': '3.3.0', 'pyxdg': '0.27', 'pyzmq': '23.2.0', 'qstylizer': '0.2.2', 'qtconsole': '5.4.2', 'queuelib': '1.5.0', 'redis': 
'5.0.3', 'regex': '2022.7.9', 'requests': '2.31.0', 'requests-file': '1.5.1', 'requests-raw': '0.2.1', 'requests-toolbelt': '1.0.0', 'responses': '0.13.3', 'rfc3339-validator': '0.1.4', 'rfc3986-validator': '0.1.1', 'rich': '13.7.1', 
'rope': '1.7.0', 'rq': '1.16.1', 'rsa': '4.9', 'ruamel.yaml': '0.17.21', 'ruamel-yaml-conda': '0.17.21', 's3fs': '2023.4.0', 's3transfer': '0.10.0', 'safe-store': '0.7.1', 'safetensors': '0.4.3', 'scikit-image': '0.20.0', 
'scikit-learn': '1.2.2', 'scikit-learn-intelex': '20230426.111612', 'scipy': '1.12.0', 'seaborn': '0.12.2', 'secure': '0.3.0', 'selenium': '4.18.1', 'semgrep': '1.60.1', 'semver': '2.13.0', 'sentence-transformers': '2.7.0', 
'service-identity': '18.1.0', 'setuptools': '69.1.1', 'shapely': '2.0.2', 'simple-websocket': '1.0.0', 'sip': '6.6.2', 'six': '1.16.0', 'slixmpp': '1.8.5', 'smart-open': '5.2.1', 'smmap': '5.0.1', 'sniffio': '1.3.1', 'snowballstemmer': 
'2.2.0', 'sortedcontainers': '2.4.0', 'soupsieve': '2.4', 'sphinxcontrib-applehelp': '1.0.2', 'sphinxcontrib-devhelp': '1.0.2', 'sphinxcontrib-htmlhelp': '2.0.0', 'sphinxcontrib-jsmath': '1.0.1', 'sphinxcontrib-qthelp': '1.0.3', 
'sphinxcontrib-serializinghtml': '1.1.5', 'spyder': '5.4.3', 'spyder-kernels': '2.4.4', 'sqlglot': '10.6.1', 'stack-data': '0.2.0', 'starlette': '0.36.3', 'statsmodels': '0.14.0', 'sympy': '1.11.1', 'tables': '3.8.0', 'tabulate': 
'0.8.10', 'tblib': '1.7.0', 'tenacity': '8.2.2', 'termcolor': '1.1.0', 'terminado': '0.17.1', 'text-unidecode': '1.3', 'textdistance': '4.2.1', 'threadpoolctl': '2.2.0', 'three-merge': '0.1.1', 'tifffile': '2023.4.12', 'tiktoken': 
'0.6.0', 'tinycss2': '1.2.1', 'tldextract': '3.2.0', 'tokenizers': '0.19.1', 'toml': '0.10.2', 'tomli': '2.0.1', 'tomlkit': '0.11.1', 'toolz': '0.12.0', 'torch': '2.3.0', 'tornado': '6.3.2', 'tqdm': '4.66.2', 'traitlets': '5.7.1', 
'transformers': '4.40.1', 'trio': '0.24.0', 'trio-websocket': '0.11.1', 'triton': '2.3.0', 'typing-extensions': '4.9.0', 'tzdata': '2023.3', 'tzlocal': '5.2', 'uc-micro-py': '1.0.1', 'ujson': '5.4.0', 'uritemplate': '4.1.1', 'urllib3': 
'2.2.0', 'uvicorn': '0.22.0', 'uvloop': '0.19.0', 'w3lib': '1.21.0', 'watchdog': '2.1.6', 'watchfiles': '0.21.0', 'wcmatch': '8.5', 'wcwidth': '0.2.5', 'webencodings': '0.5.1', 'websocket-client': '0.58.0', 'websockets': '12.0', 'wget':
'3.2', 'whatthepatch': '1.0.2', 'wheel': '0.38.4', 'wrapt': '1.14.1', 'wsproto': '1.2.0', 'wurlitzer': '3.0.2', 'xarray': '2023.6.0', 'xxhash': '2.0.2', 'xyzservices': '2022.9.0', 'y-py': '0.5.9', 'yacs': '0.1.8', 'yapf': '0.31.0', 
'yarl': '1.8.1', 'ypy-websocket': '0.8.2', 'zict': '2.2.0', 'zipp': '3.11.0', 'zope.interface': '5.4.0', 'zstandard': '0.19.0'}

CURRENT STACK

Name: default
ID: 5c248437-af55-4d6c-9034-bbd4ae78bcbe
Workspace: default / 71475f7b-a199-4c4b-8767-5ef2f6f94142

ORCHESTRATOR: default

Name: default
ID: 21f467c1-1eb7-4d57-874e-a6337837d5ec
Type: orchestrator
Flavor: local
Configuration: {}
Workspace: default / 71475f7b-a199-4c4b-8767-5ef2f6f94142

ARTIFACT_STORE: default

Name: default
ID: c845496b-e12f-4d39-93c1-b426297a7de3
Type: artifact_store
Flavor: local
Configuration: {'path': ''}
Workspace: default / 71475f7b-a199-4c4b-8767-5ef2f6f94142

### What happened?

Using ZenML cloud, I followed the exact setup guide, but the logs for my run steps aren't working.

### Reproduction steps

1. Following the setup guide
2. Look at your run

![image](https://github.com/zenml-io/zenml/assets/44903767/85fbcea3-13ee-4a87-9695-92d5ece1f288)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strickvl** [comment]
Hi @PinkDraconian I see that you're using the default artifact store. Logs will only be displayed in the dashboard when you use a cloud artifact store (basically any of the non-local ones listed [here](https://docs.zenml.io/stacks-and-components/component-guide/artifact-stores)). But we should probably improve that message that you highlight in the dashboard to make that clearer. I'll add that to our backlog. Thanks for bringing this to our attention!
