### ISSUE TITLE
[BUG]: Switch to old version dashboard from 0.57.0 zenml-server

### ISSUE THREAD

**Issue by david101-hunter** [zenml-io/zenml#2667]
### System Information

zenml version 0.57.0

### What happened?

from release [0.57.0](https://github.com/zenml-io/zenml/releases/tag/0.57.0) I'm considering switch to old version dashboard

### Reproduction steps

I don't anything about it such as tutorials, or step,...

I have tried two ways like below:
- case 1: I edit docker-compose file
![image](https://github.com/zenml-io/zenml/assets/156736296/9cdb3188-8378-4d63-b607-02d863989753)
- case 2: i add .env file
![image](https://github.com/zenml-io/zenml/assets/156736296/6c642222-949b-4820-a152-9aafa2cd798c)
after that, I run `docker compose --env-file .env  up`

Both cases are not working

### Relevant log output

```shell
UI Version is always v0.17.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schustmi** [comment]
I think the environment variable should be `ZENML_SERVER_USE_LEGACY_DASHBOARD`, can you try that instead?

**Comment by david101-hunter** [comment]
I haven't tried it yet.

**Comment by david101-hunter** [comment]
awesome! I have changed it like you said with case 1, it work
