### ISSUE TITLE
[BUG]: slider shadow have too much z-index

### ISSUE THREAD

**Issue by Asfak00** [zenml-io/zenml#2809]
### Contact Details [Optional]

asfakahmed@gmail.com

### What happened?

![image](https://github.com/zenml-io/zenml/assets/108581106/2c56ac7c-2d60-4b10-bfac-07932bf0f753)

The slider side shadow have to much z-index. And it make overflowing with navbar. reduce the z-index of slider shadow or increment the navbar z-index to fix it.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by znegrin** [comment]
Thank you for noticing this @Asfak00, I just fixed it.

Have a nice day.

**Comment by Asfak00** [comment]
Welcome znegrin. It is natural for people to make mistakes.
