### ISSUE TITLE
[DOC]: Incorrect command for analytics / telemetry opt-out. 

### ISSUE THREAD

**Issue by JustGitting** [zenml-io/zenml#2911]
### System Information

N/A

### What happened?

On the Global Settings page in the Usage Analytics section (https://docs.zenml.io/reference/global-settings#usage-analytics). The following command is given to opt out of usage analytics (telemetry):

```
zenml config analytics opt-out
```

However, it produces the error:

```
Usage: zenml [OPTIONS] COMMAND [ARGS]...
Try 'zenml --help' for help.

Error: No such command 'config'.
```

The correct command is:

```
zenml analytics opt-out
```

Maybe the `zenml config` command was for an older zenml release.

### Reproduction steps

N/A

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@JustGitting Thanks for the report! Youre right! Fixed in this https://github.com/zenml-io/zenml/pull/2908/files
