### ISSUE TITLE
[BUG]:  outside of artifact store bounds

### ISSUE THREAD

**Issue by Aadik1ng** [zenml-io/zenml#2986]
### System Information

SYSTEM_INFO: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.19045', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 
'Multiprocessor Free'}

### What happened?
Initiating a new run for the pipeline: data_ingestion_pipeline.
Executing a new run.
Caching is disabled by default for data_ingestion_pipeline.
Using user: default
Using stack: stack_1
  orchestrator: default
  artifact_store: local_artifact_store
You can visualize your pipeline runs in the ZenML Dashboard. In order to try it locally, please run zenml up.

### Relevant log output

```shell
Initiating a new run for the pipeline: data_ingestion_pipeline.
Executing a new run.
Caching is disabled by default for data_ingestion_pipeline.
Using user: default
Using stack: stack_1
  orchestrator: default
  artifact_store: local_artifact_store
You can visualize your pipeline runs in the ZenML Dashboard. In order to try it locally, please run zenml up.
Failed to execute data ingestion pipeline: File `D:data\artifacts\data_ingestion_step\logs` is outside of artifact store bounds `data/artifacts`
```

CURRENT STACK

Name: stack_1
ID: d1765057-c27f-4e5e-ac3e-e7cee6a45797
User: default / a8bf9397-512c-4f9a-9266-f24b3ea10921
Workspace: default / 5e1c6e98-5302-47d4-bbc7-b97d24d1def3

ORCHESTRATOR: default

Name: default
ID: 33520fcf-456f-438d-b894-a765938a6b5e
Type: orchestrator
Flavor: local
Configuration: {}
Workspace: default / 5e1c6e98-5302-47d4-bbc7-b97d24d1def3

ARTIFACT_STORE: local_artifact_store

Name: local_artifact_store
ID: abae7772-933e-40fb-8893-0eb1bd855a9e
Type: artifact_store
Flavor: local
Configuration: {'path': 'data/artifacts'}
User: default / a8bf9397-512c-4f9a-9266-f24b3ea10921
Workspace: default / 5e1c6e98-5302-47d4-bbc7-b97d24d1def3

### Reproduction steps

@step
def data_ingestion_step(config_path: str) -> Annotated[Dict[str, str], "paths"]:
    try:
        # Load configuration
        config = load_config(config_path)
        pdf_path = config['balance_sheet_pdf']

        # Use ZenML's artifact store context to determine base paths
        context = get_step_context()
        base_dir = context.get_output_artifact_uri()

        # Construct directories within the artifact store
        # Construct directories within the artifact store
        image_dir = os.path.join(base_dir, config.get('image_dir', 'data/artifacts/images'))
        table_dir = os.path.join(base_dir, config.get('table_dir', 'data/artifacts/tables'))
        other_dir = os.path.join(base_dir, config.get('other_dir', 'data/artifacts/other_content'))

        os.makedirs(image_dir, exist_ok=True)
        os.makedirs(table_dir, exist_ok=True)
        os.makedirs(other_dir, exist_ok=True)

        # Set up logging within the artifact store
        log_file_path = os.path.join(base_dir, 'logs', 'data_ingestion.log')
        os.makedirs(os.path.dirname(log_file_path), exist_ok=True)
        logging.basicConfig(
            filename=log_file_path,
            filemode='a',
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        logger = logging.getLogger(__name__)

        logger.info(f"Image directory: {image_dir}")
        logger.info(f"Table directory: {table_dir}")
        logger.info(f"Other content directory: {other_dir}")

        # Extract data from PDF
        extract_from_pdf(pdf_path, image_dir, table_dir, other_dir)
        
        # Log extraction info
        log_extraction_info(pdf_path, image_dir, table_dir, other_dir)

        # Return paths as a dictionary
        return {
            "image_dir": image_dir,
            "table_dir": table_dir,
            "other_dir": other_dir
        }
    except Exception as e:
        logger.error(f"Error in data ingestion step: {e}")
        raise

@pipeline
def data_ingestion_pipeline(config_path: str):
    data_ingestion_step(config_path=config_path)

if __name__ == "__main__":
    config_path = 'config.yml'  # Adjust this path if needed
    try:
        # Run the pipeline
        data_ingestion_pipeline = data_ingestion_pipeline.with_options(enable_cache=False)
        data_ingestion_pipeline(config_path=config_path)
    except Exception as e:
        print(f"Failed to execute data ingestion pipeline: {e}")

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schustmi** [comment]
This seems like an issue with Windows paths. Can you just quickly verify whether the following code also fails for you on your local machine please:
```python
from zenml import pipeline, step

@step
def logging_step() -> None:
  print("Some log message")

@pipeline
def p():
  logging_step()

if __name__ == "__main__":
  p()
```

**Comment by Aadik1ng** [comment]
These are my environment variable

HOMEDRIVE: C:
HOMEPATH: \Users\aadit
LOCALAPPDATA: C:\Users\aadit\AppData\Local
LOGONSERVER: \\DESKTOP-C4QBLHV
NUMBER_OF_PROCESSORS: 16
ORIGINAL_XDG_CURRENT_DESKTOP: undefined
OS: Windows_NT
PATH:
      C:\Users\aadit\AppData\Local\zenml;
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL

ZENML_HOME: C:\Users\aadit\AppData\Local\zenml
ZES_ENABLE_SYSMAN: 1

**Comment by schustmi** [comment]
Are you using the default local artifact store? Or did you register a custom one?

**Comment by Aadik1ng** [comment]
I was using custom in my previous stack but everything is on default

**Comment by Aadik1ng** [comment]
(PS) D:\Dir> zenml artifact-store describe default
Artifact_Store 'default' of flavor 'local' with id 'd6305633-a8f6-45ea-87f6-ae469da61fcf' is owned by user '-'.
No configuration options are set for this component.
No labels are set for this component.
No connector is set for this component.
Dashboard URL: http://127.0.0.1:8237/stacks

so the default artifact-store was not set properly so i change it to this

(PS)D:\Dir> zenml artifact-store describe balance
Artifact_Store 'Balance' of flavor 'local' with id 'bc735317-765d-4e0a-99c7-dbf0728f4702' is owned by user 'default'.
  'Balance' ARTIFACT_STORE Component   
        Configuration (ACTIVE)
┏━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━┓
┃ COMPONENT_PROPERTY │ VALUE          ┃
┠────────────────────┼────────────────┨
┃ PATH               │ data/artifacts ┃
┗━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━┛
No labels are set for this component.
No connector is set for this component.
Dashboard URL: http://127.0.0.1:8237/stacks

**Comment by schustmi** [comment]
What do you mean by "the default artifact store was no set properly"? You ran into some issues when running pipelines with the default artifact store?

I think with your custom artifact store, it's somehow messing up the volumes. Did you explicitly register it with `D:\data\artifacts`?

**Comment by Aadik1ng** [comment]
when i was using default artifact store i was getting the same issue but the path were

>C:\Users\%username%\AppData\Roaming\zenml\..

so i change the artifact_store to custom one, updated its path to data/artifacts. I got the same issue but this time the paths were

>D:\data\artifacts\..

PS D:\RAG-on-Balance_Sheet> zenml artifact-store register balance --flavor=local
You are configuring a stack component that is using local resources while connected to a remote ZenML server. The stack component may not be usable from other hosts or by other users. You should consider using a non-local stack component alternative instead.
Successfully registered artifact_store `balance`.
Dashboard URL: http://localhost:8080/stacks
