### ISSUE TITLE
[BUG]: Unable to open "Pipelines" menu in ZenML UI after upgrading to 0.67.0 version

### ISSUE THREAD

**Issue by 4gt-104** [zenml-io/zenml#3057]
### Contact Details [Optional]

grigoryan.tigran119@gmail.com

### System Information

ZENML_LOCAL_VERSION: 0.67.0
ZENML_SERVER_VERSION: 0.67.0
ZENML_SERVER_DATABASE: mysql
ZENML_SERVER_DEPLOYMENT_TYPE: kubernetes
ZENML_CONFIG_DIR: /big/home/tigran-grigoryan/.config/zenml
ZENML_LOCAL_STORE_DIR: /big/home/tigran-grigoryan/.config/zenml/local_stores
ZENML_SERVER_URL: [REDACTED]
ZENML_ACTIVE_REPOSITORY_ROOT: None
PYTHON_VERSION: 3.8.19
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'linux', 'linux_distro': 'debian', 'linux_distro_like': '', 'linux_distro_version': '12'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: AI-K8s-Datasets
ACTIVE_USER: ml-engineer
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: a8a7a850-ec7a-46be-8fa5-5fa1a6676aa8
ANALYTICS_USER_ID: 2a3955fc-17f7-4b1f-bdfd-4624a7bf23c6
ANALYTICS_SERVER_ID: 3f15d76f-f385-4d8a-9d2c-3f8de2a5749d
INTEGRATIONS: ['airflow', 'bitbucket', 'gitlab', 'kaniko', 'kubernetes', 'pigeon', 's3']
PACKAGES: {'zipp': '3.19.2', 'zenml': '0.67.0', 'yarl': '1.13.1', 'wrapt': '1.16.0', 'widgetsnbextension': '4.0.11', 'websocket-client': '1.8.0', 'wcwidth': 
'0.2.13', 'urllib3': '1.26.20', 'typing-extensions': '4.12.2', 'traitlets': '5.14.3', 'stack-data': '0.6.3', 'sqlmodel': '0.0.18', 'sqlalchemy': '2.0.35', 
'sqlalchemy-utils': '0.41.2', 'smmap': '5.0.1', 'six': '1.16.0', 'setuptools': '56.0.0', 's3transfer': '0.10.2', 's3fs': '2024.9.0', 'rsa': '4.9', 'rich': 
'13.7.1', 'requests': '2.32.3', 'requests-toolbelt': '1.0.0', 'requests-oauthlib': '2.0.0', 'pyyaml': '6.0.2', 'python-gitlab': '4.12.2', 'python-dotenv': 
'1.0.1', 'python-dateutil': '2.9.0.post0', 'pymysql': '1.1.1', 'pygments': '2.18.0', 'pydantic': '2.8.2', 'pydantic-settings': '2.5.2', 'pydantic-core': 
'2.20.1', 'pyasn1': '0.6.1', 'pyasn1-modules': '0.4.1', 'pure-eval': '0.2.3', 'ptyprocess': '0.7.0', 'psutil': '6.0.0', 'prompt-toolkit': '3.0.47', 'pip': 
'23.0.1', 'pickleshare': '0.7.5', 'pexpect': '4.9.0', 'passlib': '1.7.4', 'parso': '0.8.4', 'packaging': '24.1', 'oauthlib': '3.2.2', 'multidict': '6.1.0', 
'mdurl': '0.1.2', 'matplotlib-inline': '0.1.7', 'markupsafe': '2.1.5', 'markdown-it-py': '3.0.0', 'mako': '1.3.5', 'kubernetes': '25.3.0', 
'jupyterlab-widgets': '3.0.11', 'jmespath': '1.0.1', 'jedi': '0.19.1', 'ipywidgets': '8.1.3', 'ipython': '8.12.3', 'importlib-resources': '6.4.0', 
'importlib-metadata': '7.0.0', 'idna': '3.7', 'greenlet': '3.0.3', 'google-auth': '2.35.0', 'gitpython': '3.1.43', 'gitdb': '4.0.11', 'fsspec': '2024.9.0', 
'frozenlist': '1.4.1', 'executing': '2.0.1', 'docker': '7.1.0', 'distro': '1.9.0', 'decorator': '5.1.1', 'configparser': '7.1.0', 'comm': '0.2.2', 
'cloudpickle': '2.2.1', 'click': '8.1.3', 'charset-normalizer': '3.3.2', 'certifi': '2024.7.4', 'cachetools': '5.5.0', 'botocore': '1.35.23', 'boto3': 
'1.35.23', 'bcrypt': '4.0.1', 'backcall': '0.2.0', 'aws-profile-manager': '0.7.3', 'attrs': '24.2.0', 'async-timeout': '4.0.3', 'asttokens': '2.4.1', 
'argparse': '1.4.0', 'annotated-types': '0.7.0', 'alembic': '1.8.1', 'aiosignal': '1.3.1', 'aioitertools': '0.12.0', 'aiohttp': '3.10.9', 'aiohappyeyeballs': 
'2.4.3', 'aiobotocore': '2.15.1'}

CURRENT STACK

Name: AI-K8s-Datasets
ID: 52265cc2-2300-49ab-9bc3-71e1aef48654
User: admin / 28f9753e-3ac6-4e7a-b731-e072f3c3dfe2
Workspace: default / a101b808-a3f0-4ef9-9b58-5785739bb391

ORCHESTRATOR: AI-K8s

Name: AI-K8s
ID: dab2659c-a78b-4168-ab0d-e2793a69edf5
Type: orchestrator
Flavor: kubernetes
Configuration: {'synchronous': True, 'timeout': 0, 'service_account_name': None, 'step_pod_service_account_name': None, 'privileged': False, 'pod_settings': 
None, 'orchestrator_pod_settings': None, 'incluster': False, 'kubernetes_context': None, 'kubernetes_namespace': 'flow-orchestrators', 'local': False, 
'skip_local_validations': False, 'parallel_step_startup_waiting_period': None}
User: admin / 28f9753e-3ac6-4e7a-b731-e072f3c3dfe2
Workspace: default / a101b808-a3f0-4ef9-9b58-5785739bb391

ARTIFACT_STORE: ZenML_Bucket

Name: ZenML_Bucket
ID: 28f698d2-895d-4f0e-89f5-0e8b7459273e
Type: artifact_store
Flavor: s3
Configuration: {'authentication_secret': 'ZenML_Bucket_Secret', 'path': 's3://zenml/k8s-zenml', 'key': '********', 'secret': '********', 'token': '********', 
'client_kwargs': {'endpoint_url': '[REDACTED]', 'region_name': 'us-east-1'}, 'config_kwargs': None, 's3_additional_kwargs': None}
User: admin / 28f9753e-3ac6-4e7a-b731-e072f3c3dfe2
Workspace: default / a101b808-a3f0-4ef9-9b58-5785739bb391

CONTAINER_REGISTRY: GitLab_Registry

Name: GitLab_Registry
ID: 15667fa4-58c5-4ef7-a0b4-a215f9d9ff8b
Type: container_registry
Flavor: default
Configuration: {'authentication_secret': None, 'uri': '[REDACTED]', 'default_repository': None}
User: admin / 28f9753e-3ac6-4e7a-b731-e072f3c3dfe2
Workspace: default / a101b808-a3f0-4ef9-9b58-5785739bb391

IMAGE_BUILDER: AI-K8s-Kaniko

Name: AI-K8s-Kaniko
ID: f3123b14-b3da-4ad8-a06e-675827fdfaf9
Type: image_builder
Flavor: kaniko
Configuration: {'kubernetes_context': 'ml-engineer@cluster.local', 'kubernetes_namespace': 'flow-orchestrators', 'executor_image': 
'gcr.io/kaniko-project/executor:v1.19.0-debug', 'pod_running_timeout': 300, 'env': [], 'env_from': [], 'volume_mounts': [{'name': 
'gitlab-image-registry-creds', 'mountPath': '/kaniko/.docker/config.json', 'subPath': '.dockerconfigjson'}], 'volumes': [{'name': 
'gitlab-image-registry-creds', 'secret': {'secretName': 'gitlab-image-registry-creds'}}], 'service_account_name': None, 'store_context_in_artifact_store': 
False, 'executor_args': ['--cache=true', '--cache-copy-layers']}
User: admin / 28f9753e-3ac6-4e7a-b731-e072f3c3dfe2
Workspace: default / a101b808-a3f0-4ef9-9b58-5785739bb391

### What happened?

After upgrading ZenML server to `0.67.0` using helm chart, UI fails to open pipelines menu with the following message:

<img width="554" alt="Screenshot 2024-10-06 at 18 48 21" src="https://github.com/user-attachments/assets/6eba7eb1-ef27-4050-8abc-9070fe4d69e2">

### Reproduction steps

1. Upgrade ZenML from `0.66.0` to `0.67.0`
2. Open ZenML UI
3. Click on `Pipelines` menu on the left sidebar

### Relevant log output

```shell
2024-10-06 18:48:08,372 - zenml.zen_server.utils - ERROR - API error (utils.py:365)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (3065, "Expression #1 of ORDER BY clause is not in SELECT list, references column 'anon_2.run_or_created' which is not in SELECT list; this is incompatible with DISTINCT")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/zenml/zen_server/utils.py", line 355, in decorated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/zenml/zen_server/routers/pipelines_endpoints.py", line 81, in list_pipelines
    return verify_permissions_and_list_entities(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/zenml/zen_server/rbac/endpoint_utils.py", line 143, in verify_permissions_and_list_entities
    page = list_method(filter_model, **list_method_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/zenml/zen_stores/sql_zen_store.py", line 4153, in list_pipelines
    return self.filter_and_paginate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/zenml/zen_stores/sql_zen_store.py", line 986, in filter_and_paginate
    result = session.scalar(
             ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2410, in scalar
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3065, "Expression #1 of ORDER BY clause is not in SELECT list, references column 'anon_2.run_or_created' which is not in SELECT list; this is incompatible with DISTINCT")
[SQL: SELECT count(*) AS count_1 
FROM (SELECT DISTINCT pipeline.id AS id, pipeline.created AS created, pipeline.updated AS updated, pipeline.name AS name, pipeline.description AS description, pipeline.workspace_id AS workspace_id, pipeline.user_id AS user_id 
FROM pipeline, (SELECT pipeline.id AS id, CASE WHEN (max(pipeline_run.created) IS NULL) THEN pipeline.created ELSE max(pipeline_run.created) END AS run_or_created 
FROM pipeline LEFT OUTER JOIN pipeline_run ON pipeline.id = pipeline_run.pipeline_id GROUP BY pipeline.id) AS anon_2 
WHERE pipeline.id = anon_2.id AND true = 1 ORDER BY anon_2.run_or_created DESC, pipeline.id) AS anon_1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO:     10.250.251.176:0 - "GET /api/v1/pipelines?page=1&sort_by=desc%3Alatest_run HTTP/1.1" 500 Internal Server Error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@4gt-104 We had a similar report here on [Slack](https://zenml.slack.com/archives/C01FWQ5D0TT/p1727746718256659). the thing that worked (via @schustmi) is:

 this seems to be related to a change in our logic for listing entities, and was not caught in any CI due to a different mysql configuration:

Your DB has the sql_mode set to `ONLY_FULL_GROUP_BY` which makes this query fail. I’ll see if I can modify the query to make it work also with this option, but if you need a solution for the current release, you can disable this setting by connecting to your DB and running
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`
or modifying the config file and restarting. 

Hope this helps for now - we'll get on a fix ASAP for the next release

**Comment by 4gt-104** [comment]
@htahir1 Thank you very much for quick response. I have changed database's sql_mode and the workaround seems to be working.

Should I close this issue?

**Comment by schustmi** [comment]
#3051 fixes this and should be in the next release, at which point you can also revert the change to the SQL mode if needed.
