### ISSUE TITLE
[FEATURE] Implement  non-tensorflow specific custom Preprocessing step

### ISSUE THREAD

**Issue by hamzamaiot** [zenml-io/zenml#39]
**Is your feature request related to a problem? Please describe.**
Not everyone would like to use Tensorflow Transform, due to any reason whether it be complex logic or a legacy codebase.

**Describe the solution you'd like**
A simple Pythonic interface that receives data in an understood format and then preprocesses in a certain format.

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickphat** [comment]
I would like to participating in implementing this. Can you please help me clarify further?

**Comment by htahir1** [comment]
@patrickphat We are currently revamping ZenML internally to make this a lot easier, so it will be a bit hard to start this at this point in time. However, please join on [Slack](https://zenml.io/slack-invite) and DM me, we can have a chat about a potential contribution!
