### ISSUE TITLE
[BUG]: Requires numpy 1.18.0 conflict with other packages

### ISSUE THREAD

**Issue by halvorot** [zenml-io/zenml#473]
### Contact Details [Optional]

halvorot@gmail.com

### What happened?

zenml requires numpy 1.18.0 and this conflicts with another library that I am using, is it possible to bump the version of numpy for zenml or is there a specific reason it needs 1.18.0?

The error I get is:
```
The conflict is caused by:
    sdv 0.13.1 depends on numpy<2 and >=1.20.0; python_version >= "3.7"
    zenml 0.1.1 depends on numpy==1.18.0
```

### Reproduction steps

1. pip install sdv==0.13.1
2. pip install zenml
3.
...

### ZenML Version

0.5.0rc2

### OS Type

Windows

### Relevant log output

```shell
The conflict is caused by:
    sdv 0.13.1 depends on numpy<2 and >=1.20.0; python_version >= "3.7"
    zenml 0.1.1 depends on numpy==1.18.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Hey @halvorot ! Thank you for the report!

In your reproduction steps, you cited an installation of ZenML 0.1.1 which we no longer support. Also you are mentioning 0.5.0rc0 as the version you use -> That is also fairly outdated. I would suggest you update to ZenML >= 0.6.3.

Having said that, with Python 3.8.10 and on Ubuntu 20.04 I was able to do 

```
pip install sdv==0.13.1
pip install zenml>=0.6.3
```

And then it works without any problem. Could you try this and let me know if it worked?

**Comment by halvorot** [comment]
Thank you for the quick response. You're right, for some reason when i ran pip install zenml it tried to install version 0.1.1, but now i tried again with pip install zenml>=0.6.3 and it worked. It was probably something with my environment before.
