### ISSUE TITLE
[BUG]: torch integration fails, pytorch integration succeeds

### ISSUE THREAD

**Issue by liv4unix** [zenml-io/zenml#510]
### What happened?

I think the PyTorch integration installation step in the "not_so_quickstart" documentation needs updated to reflect "pytorch" instead of "torch":

https://github.com/zenml-io/zenml/tree/main/examples/not_so_quickstart

***This fails***

# install ZenML PyTorch integration
zenml integration install -f torch
Unable to find integration 'torch'.

***This succeeds***

# install ZenML PyTorch integration
zenml integration install -f pytorch
⠸ Installing integrations.....

***Environment Info***

#Latest ZenML 0.7.1 Testing
pip install zenml
import zenml
print(zenml.__version__)
0.7.1

python --version
Python 3.8.8

### Reproduction steps

1. zenml integration install -f torch
2.
3.
...

### ZenML Version

0.7.1

### Python Version

3.8

### OS Type

Ubuntu (or other Linux Flavor)

### Relevant log output

```shell
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Indeed you're right. We'll apply a patch to update that example!

**Comment by htahir1** [comment]
We are deprecating not_so_quickstart in the next release, so closing the issue
