### ISSUE TITLE
[FEATURE]: The Github About section could include link to the website

### ISSUE THREAD

**Issue by tczhao** [zenml-io/zenml#521]
### Describe the feature you'd like

The Github About section could use a link to the zenml website.
Would make it slightly easier to navigate for the user

![image](https://user-images.githubusercontent.com/20961507/163734891-ff780f4e-9ca8-4f19-ae95-7949b1837750.png)

**Comment by htahir1** [comment]
Good idea. Done! Thanks for the contribution!
