### ISSUE TITLE
[FEATURE]: Add an SQLite implementation of the Local Secrets Manager

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#599]
### Contact Details [Optional]

support@zenml.io

### Describe the feature you'd like

ZenML currently offers a file-based local secrets manager (found at `zenml/src/zenml/secrets_managers/local/local_secrets_manager.py`).

It would be good to have an SQLite implementation of the same behaviours, where secrets were stored locally inside a database.

Generally ZenML likes to use [SQLModel](https://sqlmodel.tiangolo.com/) for its use of SQL databases and the dependency is already available.

### How do you solve your current problem with the current status-quo of ZenML?

The current local secrets manager is implemented as a local file-based store.

### Any other comments?

This relates to #ENG-716 (Jira).

**Comment by stefannica** [comment]
As we will deprecate secrets managers in favor of [the centralized zenml secrets store](https://docs.zenml.io/advanced-guide/practical-mlops/secrets-management#centralized-secrets-store), this is outdated. As of 0.34.0, we already support a SQL back-end for the secrets store.
