### ISSUE TITLE
[FEATURE]: Log a warning instead of raising an `AssertionError`

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#616]
### Contact Details [Optional]

support@zenml.io

### Describe the feature you'd like

In our `pipeline_run_lineage_visualizer` we currently have a bit of code that raises an `AssertionError` when actually we'd rather just log a warning using our CLI utils module.

We raise the error [here](https://github.com/zenml-io/zenml/blob/84258aaafcad95d97e510eeece44cef5287ec700/src/zenml/integrations/dash/visualizers/pipeline_run_lineage_visualizer.py#L138-L142):

```python
else:
    # TODO [ENG-895]: Refactor this to raise a warning instead.
    raise AssertionError(
        "Cannot set magic flag in non-notebook environments."
    )`
```

And we would like to use our CLI utils (found at `src/zenml/cli/utils.py` and which we always import as `cli_utils`) and our `warning` function to log that same message.

### Is your feature request related to a problem?

As described above, we currently raise an error instead of just logging a warning.

[ENG-895]: https://zenml.atlassian.net/browse/ENG-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ketangangal** [comment]
Solved

**Comment by htahir1** [comment]
#628 closes this
