### ISSUE TITLE
[FEATURE]: Catch the error if a secret already exist when registering with `AWSSecretsManager`

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#618]
### Contact Details [Optional]

support@zenml.io

### Describe the feature you'd like

We currently don't have a check to ensure that a `Secret` doesn't already exist when registering the secret with `AWSSecretsManager`, but we really should check this [here](https://github.com/zenml-io/zenml/blob/373faeee6fe5951e8deb4de88a9d57263117ccb8/src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py#L75-L76).

We should raise a `SecretExistsError` (from `zenml.exceptions`), however, if we do encounter this exception.

### Is your feature request related to a problem?

Just in case someone tries to register a secret with one already existing with that same name.

### How do you solve your current problem with the current status-quo of ZenML?

N/A

**Comment by hectorLop** [comment]
Working on it :smile:
