### ISSUE TITLE
[FEATURE]: Fix formatting for `zenml secret register --help`

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#619]
### Contact Details [Optional]

support@zenml.io

### Describe the feature you'd like

When someone uses the `zenml secret register --help` command, the formatting of the CLI help information comes out wrong with line breaks not really happening. It isn't possible to read the text printed to the terminal as executed within [the `register_secret` function](https://github.com/zenml-io/zenml/blob/373faeee6fe5951e8deb4de88a9d57263117ccb8/src/zenml/cli/secret.py#L107-L108).

Ideally the formatting should be fixed such that the output resembles the layout specified in the docstring.

### Any other comments?

This relates to #ENG-871.

**Comment by anencore94** [comment]
May I take this issue?
