### ISSUE TITLE
[FEATURE]: Allow secrets to be created by passing dicts or JSON values

### ISSUE THREAD

**Issue by strickvl** [zenml-io/zenml#620]
### Contact Details [Optional]

support@zenml.io

### Describe the feature you'd like

We currently allow for the registration of secrets via an interactive CLI process, or by passing one or more `--secret_key=secret_value` as command line arguments:

```
$ zenml secret create -i area51
Entering interactive mode:
Please enter a secret key: location
Please enter the secret value for the key [location]:
Do you want to add another key-value pair to this secret? [y/n]: y
Please enter a secret key: aliens
Please enter the secret value for the key [aliens]:
Do you want to add another key-value pair to this secret? [y/n]: n
The following secret will be registered.
┏━━━━━━━━━━━━┯━━━━━━━━━━━━━━┓
┃ SECRET_KEY │ SECRET_VALUE ┃
┠────────────┼──────────────┨
┃  location  │ ***          ┃
┠────────────┼──────────────┨
┃   aliens   │ ***          ┃
┗━━━━━━━━━━━━┷━━━━━━━━━━━━━━┛
⠙ Saving secret `area51`...
Secret 'area51' successfully created.
```

```
$ zenml secret create area51 --location=Nevada --aliens=many
The following secret will be registered.
┏━━━━━━━━━━━━┯━━━━━━━━━━━━━━┓
┃ SECRET_KEY │ SECRET_VALUE ┃
┠────────────┼──────────────┨
┃  location  │ ***          ┃
┠────────────┼──────────────┨
┃   aliens   │ ***          ┃
┗━━━━━━━━━━━━┷━━━━━━━━━━━━━━┛
⠙ Saving secret `area51`...
Secret 'area51' successfully created.
```

We would like to enable users to pass in a `dict` or perhaps a JSON/YAML object containing multiple key-value pairs. The dict/JSON/YAML object could either be supplied as a command line argument, or by loading values from a file, e.g.:

```
$ zenml secret create area51 --values='{"location": "Nevada", "aliens":"many"}'
The following secret will be registered.
┏━━━━━━━━━━━━┯━━━━━━━━━━━━━━┓
┃ SECRET_KEY │ SECRET_VALUE ┃
┠────────────┼──────────────┨
┃  location  │ ***          ┃
┠────────────┼──────────────┨
┃   aliens   │ ***          ┃
┗━━━━━━━━━━━━┷━━━━━━━━━━━━━━┛
⠙ Saving secret `area51`...
Secret 'area51' successfully created.
```

```
$ zenml secret create area51 --values-file=/path/to/file
The following secret will be registered.
┏━━━━━━━━━━━━┯━━━━━━━━━━━━━━┓
┃ SECRET_KEY │ SECRET_VALUE ┃
┠────────────┼──────────────┨
┃  location  │ ***          ┃
┠────────────┼──────────────┨
┃   aliens   │ ***          ┃
┗━━━━━━━━━━━━┷━━━━━━━━━━━━━━┛
⠙ Saving secret `area51`...
Secret 'area51' successfully created.
```

This issue might require some discussion prior to implementation.

[This](https://github.com/zenml-io/zenml/blob/main/src/zenml/cli/secret.py#L559-L635) is the part of the codebase where this applies.

### How do you solve your current problem with the current status-quo of ZenML?

Feature currently isn't possible.

**Comment by Tob-iee** [comment]
Hello @strickvl please i would like to work on this issue

**Comment by strickvl** [comment]
Sounds good, @Tob-iee. Is everything clear in terms of how you think you'd go about implementing it? I assume you'll reference the local secrets manager when you work on this?

Also, please do make sure you add some tests to cover these changes if you do go ahead with this!

The rest of our processes etc for contributions is [described here](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md).

**Comment by Tob-iee** [comment]
I was hoping to have a discussion about it prior to its implementation as stated in the description to help clarify things for me. Hope that will be possible.

**Comment by strickvl** [comment]
Yes of course. Maybe we could start with your understanding of the problem / what needs doing? Or is the description unclear and you'd want me to explain more?

**Comment by Tob-iee** [comment]
From what I can understand, we want to enable the function to take in a Dict/JSON datatype as its input parameter for the "secret_key" and "secret_value" as one rather than passing two separate str data types for each of them. But one question I have here is that would it still be an Interactive CLI after this implementation

**Comment by strickvl** [comment]
I think there would be no need for the interactive part once you are passing in a dict or JSON. You can see the final clause of the condition [here](https://github.com/zenml-io/zenml/blob/080b9f30b75dbf87b24bdfed488c405d44ac2d8c/src/zenml/cli/secret.py#L137] on line 137 only runs if no other values have been passed in.

I think, however, we should only allow one way of passing these in per function call. i.e. you shouldn't be able to pass in secret key and secret values to the CLI *as well as* passing in a JSON or dict. You basically have to choose one of them. (And we'd need some checks, error logging and tests as appropriate to guard against those cases/behaviours.)

**Comment by Tob-iee** [comment]
Okay, I understand better now, if I face any blocker I'll be sure to reach out. but just to be clear on something, the secrets in question here will be used by zenML CLI for access right?

**Comment by strickvl** [comment]
The secrets get used by our Secrets Manager stack component. You can read more about it [here](https://docs.zenml.io/advanced-guide/manage-your-secrets) and also check out the practical example [here](https://github.com/zenml-io/zenml/tree/main/examples/cloud_secrets_manager).

**Comment by Tob-iee** [comment]
Hello, @strickvl pleas can you check on the slack when you have time

**Comment by strickvl** [comment]
Hi I don't see any messages from you. You're posting in the ZenML slack?

**Comment by Tob-iee** [comment]
Yea, It's a DM on ZenML slack

**Comment by strickvl** [comment]
![ScreenShot 2022-06-17 at 12 35 07](https://user-images.githubusercontent.com/3348134/174282013-7a0cf565-0e92-485e-8285-35ca8cd763ad.png)

**Comment by testdepthanalytics** [comment]
@strickvl is this still open? looking for a good spot to start contributing

**Comment by strickvl** [comment]
Thanks for asking, @testdepthanalytics! I'm unsure of the status of this on the side of @Tob-iee. (Are you still working on it, @Tob-iee?) 

I'll also take a look to see if there are any other issues that we have available currently and add them to the issues board as appropriate.

**Comment by stefannica** [comment]
@Tob-iee @testdepthanalytics , if you're still interested in this issue, we changed the problem statement a bit to reflect the fact that we're phasing out secrets managers in favor of [the centralized secrets store](https://docs.zenml.io/advanced-guide/practical-mlops/secrets-management#centralized-secrets-store). The feature described here hasn't changed, it just refers now to a different CLI command.
