### ISSUE TITLE
Invalid documentation: 'zenml example list'

### ISSUE THREAD

**Issue by ronikurtberg** [zenml-io/zenml#646]
Hi,
As part of the [Examples](https://docs.zenml.io/zenml-example-cli) documentation, you have mentioned that the command to get the full list of examples is `zenml example list`, while actually the updated one is `zenml example list-example`.

**Comment by schustmi** [comment]
Hi @ronikurtberg, nice catch. The documentation is correct but I actually mistakenly renamed the command. It will be back to `zenml example list` in the next release.

**Comment by schustmi** [comment]
#647
