### ISSUE TITLE
[BUG]: Documentation URLs broken (Type of Stack Component page)

### ISSUE THREAD

**Issue by IanQS** [zenml-io/zenml#656]
### System Information

Click on the URLs under [Type of Stack Component](https://docs.zenml.io/advanced-guide/stacks-components-flavors) and it'll show that they are broken.

### What happened?

URLs broken

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
True!

**Comment by IanQS** [comment]
Thank you! I would have submitted a PR myself if I knew where all of them should be pointing to

**Comment by htahir1** [comment]
Fixed in #652
