### ISSUE TITLE
[BUG]: Windows OSError when adding s3 artifact-store

### ISSUE THREAD

**Issue by Val3nt-ML** [zenml-io/zenml#718]
### Contact Details [Optional]

val3ntin.laurent@gmail.com

### System Information

- ZenML version: 0.9.0                                                                                                                                                                              
- Install path: C:\Users\vlaurent\Anaconda3\envs\re-estimation-38\Lib\site-packages\zenml                                                                                                           
- Python version: 3.8.13                                                                                                                                                                            
- Platform information: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.19044', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 'Multiprocessor Free'}
- Environment: native                                                                                                                                                                               
- Integrations: ['dash', 'evidently', 'facets', 'lightgbm', 'mlflow', 's3', 'scipy', 'sklearn', 'xgboost']  

### What happened?

Hello Zen-ML Team,
As we discussed on Slack with @AlexejPenner and @htahir1, I'm encountering some issues when I defined a S3 bucket as the artifact-store of my stack on Windows, locally.
I've faced it with a simple pipeline composed of 3 steps :
- step 1 = create_df1 
- step2 = create_df2 
- step3=process_df (merge these df together)

My Zen-ML repository is the following `C:\\Users\\vlaurent\\My_Git_Repo\\real-estate-pricer\\src\\exploration`

My stack is composed of the following components:
- Orchestrator : default
- Metadata-store: default
- Artifact-store: custom s3 configured as the following : 

![image](https://user-images.githubusercontent.com/58519204/175071483-c58c4514-c8c7-4b0f-8bc5-cfb1e15dc64b.png)

I've tried the exact same code and stack on Linux and it works properly. I got an OSError issue as following. 
![image](https://user-images.githubusercontent.com/58519204/175071305-8d43bf48-98fa-47db-be4d-fe51eb9c5ee4.png)

It seems that ZenML tries to register the path of my bucket in the local repository, causing this issue. 

**PS**: I don't know if it's correlated but on Windows machine when I tried to execute a pipeline with `pipeline.run()` and execute this line directly in a `.py` file (executed in Python Console) I encountered the same type or issue.
Thanks in advance.
Valentin LAURENT

### Reproduction steps

1. Add a remote s3 bucket as artifact-store of your Zen-ML stack
2. Run any Zen-ML pipeline on Windows

### Relevant log output

```shell
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\vlaurent\My_Git_Repo\real-estate-pricer\src\exploration\test_zenml.py:56 in <module>    │
│                                                                                                  │
│   53                                                                                             │
│   54 if __name__ == "__main__":                                                                  │
│   55 │   my_pipe = second_pipeline(step1=create_df1(), step2=create_df2(), step3=process_df()    │
│ ❱ 56 │   my_pipe.run()                                                                           │
│   57                                                                                             │
│   58                                                                                             │
│                                         │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ onerror = <function rmtree.<locals>.onerror at 0x000001DDE0AC6280>                           │ │
│ │    path = 'C:\\Users\\vlaurent\\My_Git_Repo\\real-estate-pricer\\src\\exploration\\s3:\\dat… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\vlaurent\Anaconda3\envs\re-estimation-38\lib\shutil.py:596 in _rmtree_unsafe            │
│                                                                                                  │
│    593 # version vulnerable to race conditions                                                   │
│    594 def _rmtree_unsafe(path, onerror):                                                        │
│    595 │   try:                                                                                  │
│ ❱  596 │   │   with os.scandir(path) as scandir_it:                                              │
│    597 │   │   │   entries = list(scandir_it)                                                    │
│    598 │   except OSError:                                                                       │
│    599 │   │   onerror(os.scandir, path, sys.exc_info())                                         │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ onerror = <function rmtree.<locals>.onerror at 0x000001DDE0AC6280>                           │ │
│ │    path = 'C:\\Users\\vlaurent\\My_Git_Repo\\real-estate-pricer\\src\\exploration\\s3:\\dat… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte:
'C:\\Users\\vlaurent\\My_Git_Repo\\real-estate-pricer\\src\\exploration\\s3:\\data-warehouse\\zenml_artifact_store\\create_df1\\.system\\stateful_working_dir'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexejPenner** [comment]
Hey @Val3nt-ML I may have found your issue today. We were using pathlib.Path to manipulate the artifact-store paths which stripped one of the backslashes away from the s3-path. This lead to the materializer of the stepoutputs to try creating these directories locally on your machine. 

The PR to fix this can be found [here](https://github.com/zenml-io/zenml/pull/735)

It would be awesome if you could try pip-installing [this branch](https://github.com/zenml-io/zenml/tree/bugfix/windows-source-utils) to see if this error is solved for you.

**Comment by Val3nt-ML** [comment]
Ok thanks, I'll try it and keep you informed !

**Comment by Val3nt-ML** [comment]
I've just tested It, and It seems that I still have the same issue :( 

`OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'C:\\Users\\vlaurent\\My_Git_Repo\\Test_ZenML\\s3:\\data-warehouse\\zenml_artifact_store\\fetch_input\\.system\\stateful_working_dir'`
