### ISSUE TITLE
Broken Link to Functional API Guide on README page

### ISSUE THREAD

**Issue by dnth** [zenml-io/zenml#721]
The link to Functional API Guide is broken.

Clickinn on the link leads to https://docs.zenml.io/v/docs/guides/functional-api but it does not exist on the docs page.
The screenshot below shows the broken link in red circle.

![image](https://user-images.githubusercontent.com/6821286/175461623-586caa8e-10cc-4056-98fb-6ccecce00044.png)

**Comment by strickvl** [comment]
Feel free to bundle any of these broken links that you've found into a PR. I saw there were some fixed links in #722 but those are merged already.

We also have a ticket / task to have a more automated way of checking for dead or broken links which @htahir1 is working on, but nevertheless good to get these fixes in wherever you see them.

Thanks!

**Comment by dnth** [comment]
> Feel free to bundle any of these broken links that you've found into a PR. I saw there were some fixed links in #722 but those are merged already.
> 
> We also have a ticket / task to have a more automated way of checking for dead or broken links which @htahir1 is working on, but nevertheless good to get these fixes in wherever you see them.
> 
> Thanks!

For the links in https://github.com/zenml-io/zenml/pull/722 I could make an educated guess where they are suppose to land in the ZenML webpage. 

But for this particular link, I'm not very sure as I could not find anything related to Functional API on the webpage other than 

![image](https://user-images.githubusercontent.com/6821286/175496322-40117505-0515-4218-97fc-dc1a0055895a.png)

Is the broken link suppose to land on this page?

**Comment by strickvl** [comment]
Hmmm yeah that's not especially clear! That page offers both the class-based and functional ways to use `steps`. I think the arrow you have pointing to the 'Functional API' is exactly where the functional pieces are listed, but we could probably do better to explain at the top what the two different approaches are used for / suited for.

**Comment by dnth** [comment]
I think an explanation at the top will definitely help especially with new users who's unfamiliar with the API. 

The screenshot is taken from https://docs.zenml.io/developer-guide/class-based-api

I suppose the "class-based-api" in the link will be changed to something general that covers both class and functional API?
Should I wait for the link to be updated and then make another PR? And keep this issue open until then?

**Comment by strickvl** [comment]
The link can be changed via the `toc.md` file. You're welcome to bundle a suggested change for that together with the explanation. Otherwise I'll create an internal ticket for us to create that. Today we're mainly focused on getting things ready for our release early next week, so unlikely to be much movement on this from our side until next week.

**Comment by htahir1** [comment]
@dnth has this been fixed in a PR? Just wanted to surface it ? :-)

**Comment by dnth** [comment]
It's not yet fixed in any PR at the moment. But this issue will be addressed in the documentation restructuring.

**Comment by htahir1** [comment]
If fixed id suggest we choose

**Comment by dnth** [comment]
Just opened a PR to fix this.
