### ISSUE TITLE
[BUG]: ZenML server docker container does not work

### ISSUE THREAD

**Issue by atanikan** [zenml-io/zenml#754]
### System Information

ZenML version: 0.10.0
Install path: /home/atanikanti/zenmlenv/lib/python3.8/site-packages/zenml
Python version: 3.8.13
Platform information: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '22.04'}
Environment: native
Integrations: ['dash', 'evidently', 'facets', 'mlflow', 'plotly', 'scipy', 'sklearn']

### What happened?

I am following the documentation here https://docs.zenml.io/collaborate/zenml-server for the docker server, when I run

```
docker run -it -d -p 8080:8000 \
    -v $PWD/zenserver:/zenserver \
    -e ZENML_CONFIG_PATH=/zenserver \
    zenmldocker/zenml \
    uvicorn zenml.zen_server.zen_server_api:app --host 0.0.0.0
```

I see the following error

```shell
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "uvicorn": executable file not found in $PATH: unknown.
```

Also if I use `zenml server up` I notice a username and password prompt on the browser may I know where exactly can I set that. My ML Team is looking for a self-hosted collaborative MLOps tool with experimentation tracking built and we are evaluating zenml as a potential tool.

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
> Also if I use zenml server up I notice a username and password prompt on the browser may I know where exactly can I set that.

Regarding your user/password question, ZenML currently uses a rudimentary user account system to authorize access to the ZenML server, [as described in the docs](https://docs.zenml.io/collaborate/zenml-server#zenserver-user-management). In your case, you have to use the `default` username with an empty password to access the REST API in the browser.

**Comment by stefannica** [comment]
We're now publishing a `zenmldocker/zenml-server` specifically tailored for running the ZenML server and the docs have been updated to reflect this. This should have fixed your problem @atanikan , so I'm closing this issue. Please reopen it if that's not the case.
