### ISSUE TITLE
[BUG]: importing pipeline requirements via requirements.txt does not work if requirements.txt ends with a newline

### ISSUE THREAD

**Issue by signaleleven** [zenml-io/zenml#780]
### Contact Details [Optional]

me@sig11.space

### System Information

```
ZenML version: 0.10.0
Install path: /Users/signaleleven/Library/Caches/pypoetry/virtualenvs/image-simulator-python-mseJHGTJ-py3.9/lib/python3.9/site-packages/zenml
Python version: 3.9.13
Platform information: {'os': 'mac', 'mac_version': '10.16'}
Environment: native
Integrations: ['aws', 'dash', 'evidently', 'facets', 'mlflow', 'plotly', 's3', 'scipy', 'sklearn']
```

### What happened?

Specifying pipeline requirements via `requirements.txt` as documented [here](https://docs.zenml.io/v/docs/developer-guide/advanced-usage/docker) does not work:

the way `requirements.txt` is parsed here https://github.com/zenml-io/zenml/blob/main/src/zenml/pipelines/base_pipeline.py#L315 appears to always add an empty requirement (when requirements.txt has a newline at the end, which is added by default in many editors)

### Reproduction steps

```bash
$ cat requirements.txt
one
two
three
$
```
(empty new line at the end of the file)

Example of the issue in python repl:

```python
>>> from zenml.io import fileio
>>> with fileio.open("./requirements.txt") as f:
...   [requirement.strip() for requirement in f.read().split('\n')]
...
['one', 'two', 'three', '']
>>>
```

When decorating a pipeline like this (with a requirements.txt file with a newline at the end)
```
@pipeline(requirements_file="./requirements.txt")
```

I get an error when running pip while building the docker image to use in the pipeline (see below)

### Relevant log output

```shell
Step 3/7 : RUN pip install --no-cache '' 'boto3==1.21.21'  's3fs==2022.3.0' 'sagemaker==2.82.2' 'zenml==0.10.0'

---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
---> Running in 310c128b5f71
ERROR: Invalid requirement: ''
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexejPenner** [comment]
Thank you for raising this issue, I hope the [fix](https://github.com/zenml-io/zenml/pull/781) will make it into our next release today or tomorrow.

**Comment by signaleleven** [comment]
Awesome! Thank you!

**Comment by htahir1** [comment]
@signaleleven Please do check if its fixed. If yes, go ahead and close the issue :-)

**Comment by signaleleven** [comment]
Tested now, fails with 0.10.0, works with 0.11.0 :)
Thanks a lot!
