### ISSUE TITLE
[BUG]:  Container registry registration failing because of not specifying flavor

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenml#848]
### Contact Details [Optional]

vishalisrinivasan97@gmail.com

### System Information

ZenML version: 0.12.0
Install path: C:\Users\vishali\Anaconda3\Lib\site-packages\zenml
Python version: 3.8.8
Platform information: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.19041', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 'Multiprocessor Free'}
Environment: native
Integrations: ['kubeflow', 'kubernetes', 'scipy', 'seldon', 'sklearn', 'tensorflow']

### What happened?

When I am executing the below command:

!zenml container-registry register local_registry --uri=localhost:5000

I am facing the below error:
Running with active profile: 'default' (local)
Error: Please use the option to specify '--flavor'/'-f' of the container registry you want to register.

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Yes! As it says on the error, please try running it with the `-f` flag:

```
!zenml container-registry register local_registry --flavor=default --uri=localhost:5000
```
