### ISSUE TITLE
[BUG]:  Resuming provisioned resources for stack local_kbflow_stack

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenml#870]
### Contact Details [Optional]

vishalisrinivasan97@gmail.com

### System Information

ZenML version: 0.12.0
Install path: C:\Users\vsriniva\Anaconda3\Lib\site-packages\zenml
Python version: 3.8.8
Platform information: {'os': 'windows', 'windows_version_release': '10', 'windows_version': '10.0.19041', 'windows_version_service_pack': 'SP0', 'windows_version_os_type': 'Multiprocessor Free'}
Environment: native
Integrations: ['kubeflow', 'kubernetes', 'pytorch', 'scipy', 'seldon', 'sklearn', 'tensorflow']

### What happened?

I am facing the below issue while executing "!zenml stack up" in Jupyter Notebook. 
WARN[0000] No node filter specified                     
FATA[0000] Failed Cluster Configuration Validation:  failed to validate volume mount 'C:\Users\vsriniva\AppData\Roaming\zenml:C:\Users\vsriniva\AppData\Roaming\zenml': volume mount destination doesn't appear to be an absolute path: 'C' in 'C:\Users\vsriniva\AppData\Roaming\zenml:C:\Users\vsriniva\AppData\Roaming\zenml' 
Error: Unable to resume resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, name=kubeflow_orchest, uuid=a7eaf90b-7987-4514-8608-1813ec85e0b9, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-a7eaf90b, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False): No resources have been provisioned for this component.

### Reproduction steps

1. !zenml container-registry register local_reg --flavor=default --uri=localhost:5000
2. !zenml orchestrator register kubeflow_orchest --flavor=kubeflow
3. !zenml orchestrator register kubeflow_orchest --flavor=kubeflow
4. !zenml stack register local_kbflow_stack -m default -a default -o kubeflow_orchest -c local_reg
5. !zenml stack set local_kbflow_stack
6. !zenml stack up
![image](https://user-images.githubusercontent.com/60731083/187414106-61821a77-a859-4505-a59f-f214ce271cc5.png)
![image](https://user-images.githubusercontent.com/60731083/187414170-27880d8c-203c-48fd-ae13-cef272baea04.png)
![image](https://user-images.githubusercontent.com/60731083/187414245-1e247bca-a55f-4b49-8a86-4694ccc3fe74.png)

### Relevant log output

```shell
Running with active profile: 'default' (local)
Provisioning resources for active stack 'local_kbflow_stack'.
Provisioning resources for stack 'local_kbflow_stack'.
WARN[0000] No node filter specified                     
FATA[0000] Failed Cluster Configuration Validation:  failed to validate volume mount 'C:\Users\vsriniva\AppData\Roaming\zenml:C:\Users\vsriniva\AppData\Roaming\zenml': volume mount destination doesn't appear to be an absolute path: 'C' in 'C:\Users\vsriniva\AppData\Roaming\zenml:C:\Users\vsriniva\AppData\Roaming\zenml' 
Error: Unable to resume resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, name=kubeflow_orchest, uuid=a7eaf90b-7987-4514-8608-1813ec85e0b9, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-a7eaf90b, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False): No resources have been provisioned for this component.
Provisioning local Kubeflow Pipelines deployment...
Creating local K3D cluster 'zenml-kubeflow-a7eaf90b'.
Command '['k3d', 'cluster', 'create', 'zenml-kubeflow-a7eaf90b', '--image', 'rancher/k3s:v1.23.5-k3s1', '--registry-create', 'k3d-zenml-kubeflow-registry.localhost:5000', '--registry-config', 'C:\\Users\\vsriniva\\AppData\\Roaming\\zenml\\kubeflow\\a7eaf90b-7987-4514-8608-1813ec85e0b9\\k3d_registry.yaml', '--volume', 'C:\\Users\\vsriniva\\AppData\\Roaming\\zenml:C:\\Users\\vsriniva\\AppData\\Roaming\\zenml']' returned non-zero exit status 1.
Unable to spin up local Kubeflow Pipelines deployment.
If you wish to spin up this Kubeflow local orchestrator manually, please enter the following commands:

> k3d cluster create zenml-kubeflow-a7eaf90b --image rancher/k3s:v1.23.5-k3s1 --registry-create k3d-zenml-kubeflow-registry.localhost:5000 --registry-config C:\Users\vsriniva\AppData\Roaming\zenml\kubeflow\a7eaf90b-7987-4514-8608-1813ec85e0b9\k3d_registry.yaml --volume C:\Users\vsriniva\AppData\Roaming\zenml:C:\Users\vsriniva\AppData\Roaming\zenml

> kubectl --context k3d-zenml-kubeflow-a7eaf90b apply -k github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-a7eaf90b wait --timeout=60s --for condition=established crd/applications.app.k8s.io
> kubectl --context k3d-zenml-kubeflow-a7eaf90b apply -k github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-a7eaf90b --namespace kubeflow port-forward svc/ml-pipeline-ui 8080:80
INFO[0000] No clusters found                            
Deleted local k3d cluster 'zenml-kubeflow-a7eaf90b'.
Local kubeflow pipelines deployment deprovisioned.
Provisioned resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, name=kubeflow_orchest, uuid=a7eaf90b-7987-4514-8608-1813ec85e0b9, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-a7eaf90b, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False).
Resuming provisioned resources for stack local_kbflow_stack.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
This should be solved by installing and running everything (zenml, k3d, kubectl, the jupyter notebook) inside WSL. Running the notebook in Windows and k3d in WSL does not work properly, because k3d cannot properly mount Windows paths (e.g. `C:\Users\vsriniva\AppData\Roaming\zenml`) inside Linux containers.

**Comment by Coder-Vishali** [comment]
Thanks for the response Stefan! I will check with WSL then.
