### ISSUE TITLE
[BUG]: Error: Unable to resume resources for KubeflowOrchestrator

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenml#875]
### Contact Details [Optional]

vishalisrinivasan97@gmail.com

### System Information

ZenML version: 0.13.1
Install path: /home/<username>/.pyenv/versions/3.7.6/lib/python3.7/site-packages/zenml
Python version: 3.7.6
Platform information: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '18.04'}
Environment: native
Integrations: ['kubeflow', 'kubernetes', 'tensorboard', 'tensorflow']

### What happened?

I was trying to implement the below script:
https://github.com/zenml-io/zenml/blob/main/examples/kubeflow_pipelines_orchestration/ZenML%20Walkthrough%20Kubeflow%20Pipelines.ipynb

I am stuck while executing this command "!zenml stack up":
Facing the below error:
Error: Unable to resume resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, docker_parent_image=None, name=kubeflow_orchestrator, uuid=82e3ca95-50b5-405e-9229-351c82b4dcc7, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-82e3ca95, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False): No resources have been provisioned for this component.

### Reproduction steps

1. !zenml stack up
You can find the entire source code here:
https://github.com/zenml-io/zenml/blob/main/examples/kubeflow_pipelines_orchestration/ZenML%20Walkthrough%20Kubeflow%20Pipelines.ipynb

### Relevant log output

```shell
Running with active profile: 'default' (local)
Provisioning resources for active stack 'local_kubeflow_stack'.
Provisioning resources for stack 'local_kubeflow_stack'.
Provisioning local Kubeflow Pipelines deployment...
Creating local K3D cluster 'zenml-kubeflow-82e3ca95'.
WARN[0000] No node filter specified                     
INFO[0000] Prep: Network                                
INFO[0000] Created network 'k3d-zenml-kubeflow-82e3ca95' 
INFO[0000] Created image volume k3d-zenml-kubeflow-82e3ca95-images 
INFO[0000] Creating node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0004] Pulling image 'docker.io/library/registry:2' 
INFO[0012] Successfully created registry 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0012] Starting new tools node...                   
INFO[0013] Creating node 'k3d-zenml-kubeflow-82e3ca95-server-0' 
INFO[0014] Pulling image 'ghcr.io/k3d-io/k3d-tools:5.4.6' 
INFO[0018] Pulling image 'rancher/k3s:v1.23.5-k3s1'     
INFO[0019] Starting Node 'k3d-zenml-kubeflow-82e3ca95-tools' 
INFO[0052] Creating LoadBalancer 'k3d-zenml-kubeflow-82e3ca95-serverlb' 
INFO[0053] Pulling image 'ghcr.io/k3d-io/k3d-proxy:5.4.6' 
INFO[0063] Using the k3d-tools node to gather environment information 
INFO[0063] HostIP: using network gateway 172.18.0.1 address 
INFO[0063] Starting cluster 'zenml-kubeflow-82e3ca95'   
INFO[0063] Starting servers...                          
INFO[0063] Starting Node 'k3d-zenml-kubeflow-82e3ca95-server-0' 
INFO[0068] All agents already running.                  
INFO[0068] Starting helpers...                          
INFO[0068] Starting Node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0068] Starting Node 'k3d-zenml-kubeflow-82e3ca95-serverlb' 
INFO[0075] Injecting records for hostAliases (incl. host.k3d.internal) and for 3 network members into CoreDNS configmap... 
INFO[0079] Cluster 'zenml-kubeflow-82e3ca95' created successfully! 
INFO[0079] You can now use it like this:                
kubectl cluster-info
Finished K3D cluster creation.
Deploying Kubeflow Pipelines.
error: git cmd = '/usr/bin/git fetch --depth=1 origin 1.8.1': exit status 128
Command '['kubectl', '--context', 'k3d-zenml-kubeflow-82e3ca95', 'apply', '-k', 'github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.1&timeout=5m']' returned non-zero exit status 1.
Unable to spin up local Kubeflow Pipelines deployment.
If you wish to spin up this Kubeflow local orchestrator manually, please enter the following commands:

> k3d cluster create zenml-kubeflow-82e3ca95 --image rancher/k3s:v1.23.5-k3s1 --registry-create k3d-zenml-kubeflow-registry.localhost:5000 --registry-config /home/username/.config/zenml/kubeflow/82e3ca95-50b5-405e-9229-351c82b4dcc7/k3d_registry.yaml --volume /home/username/.config/zenml:/home/username/.config/zenml

> kubectl --context k3d-zenml-kubeflow-82e3ca95 apply -k github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-82e3ca95 wait --timeout=60s --for condition=established crd/applications.app.k8s.io
> kubectl --context k3d-zenml-kubeflow-82e3ca95 apply -k github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-82e3ca95 --namespace kubeflow port-forward svc/ml-pipeline-ui 8080:80
INFO[0000] Deleting cluster 'zenml-kubeflow-82e3ca95'   
INFO[0001] Deleting cluster network 'k3d-zenml-kubeflow-82e3ca95' 
INFO[0001] Deleting 2 attached volumes...               
WARN[0001] Failed to delete volume 'k3d-zenml-kubeflow-82e3ca95-images' of cluster 'zenml-kubeflow-82e3ca95': failed to find volume 'k3d-zenml-kubeflow-82e3ca95-images': Error: No such volume: k3d-zenml-kubeflow-82e3ca95-images -> Try to delete it manually 
INFO[0001] Removing cluster details from default kubeconfig... 
INFO[0001] Removing standalone kubeconfig file (if there is one)... 
INFO[0001] Successfully deleted cluster zenml-kubeflow-82e3ca95! 
Deleted local k3d cluster 'zenml-kubeflow-82e3ca95'.
Local kubeflow pipelines deployment deprovisioned.
Provisioned resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, docker_parent_image=None, name=kubeflow_orchestrator, uuid=82e3ca95-50b5-405e-9229-351c82b4dcc7, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-82e3ca95, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False).
Resuming provisioned resources for stack local_kubeflow_stack.
Error: Unable to resume resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, docker_parent_image=None, name=kubeflow_orchestrator, uuid=82e3ca95-50b5-405e-9229-351c82b4dcc7, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-82e3ca95, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False): No resources have been provisioned for this component.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefannica** [comment]
Hello @Coder-Vishali ,

There's an error message in your log output that might indicate why the deployment is failing:

```
error: git cmd = '/usr/bin/git fetch --depth=1 origin 1.8.1': exit status 128
```

It's tough to say exactly why this is failing, but here are some possible reasons:

* you don't have git installed on your machine
* you may have an older kubectl version installed. Try to install a more recent one.
* you may have run into temporary internet connection issues or may have a slow connection. Try running the `zenml stack up` command again. If it's still failing, you might want to try running the commands manually, as indicated in the log output, but use a higher timeout value for the `kubectl apply` commands.
* less likely to happen: if you're making a lot of calls to the GitHub API, you may be running into GitHub rate-limiting issues. See [the GitHub docs on rate-limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) for more information.

**Comment by Coder-Vishali** [comment]
Thanks for the pointers Stefan. I will debug on this further.

**Comment by Coder-Vishali** [comment]
Hey Stefan, 

When I try to rerun the command again. It says "Failed Cluster start"

Running with active profile: 'default' (local)
Provisioning resources for active stack 'local_kube_stack'.
Provisioning resources for stack 'local_kube_stack'.
Provisioning local Kubeflow Pipelines deployment...
Creating local K3D cluster 'zenml-kubeflow-c6d03f6a'.
WARN[0000] No node filter specified                     
INFO[0000] Prep: Network                                
INFO[0000] Created network 'k3d-zenml-kubeflow-c6d03f6a' 
INFO[0000] Created image volume k3d-zenml-kubeflow-c6d03f6a-images 
INFO[0000] Creating node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0000] Successfully created registry 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0000] Starting new tools node...                   
INFO[0000] Starting Node 'k3d-zenml-kubeflow-c6d03f6a-tools' 
INFO[0001] Creating node 'k3d-zenml-kubeflow-c6d03f6a-server-0' 
INFO[0001] Creating LoadBalancer 'k3d-zenml-kubeflow-c6d03f6a-serverlb' 
INFO[0001] Using the k3d-tools node to gather environment information 
INFO[0001] HostIP: using network gateway 172.24.0.1 address 
INFO[0001] Starting cluster 'zenml-kubeflow-c6d03f6a'   
INFO[0001] Starting servers...                          
INFO[0002] Starting Node 'k3d-zenml-kubeflow-c6d03f6a-server-0' 
INFO[0006] All agents already running.                  
INFO[0006] Starting helpers...                          
INFO[0006] Starting Node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0007] Starting Node 'k3d-zenml-kubeflow-c6d03f6a-serverlb' 
ERRO[0007] Failed Cluster Start: Failed to add one or more helper nodes: runtime failed to start node 'k3d-zenml-kubeflow-registry.localhost': docker failed to start container for node 'k3d-zenml-kubeflow-registry.localhost': Error response from daemon: driver failed programming external connectivity on endpoint k3d-zenml-kubeflow-registry.localhost (95a25a630be43991766cf9b4d8b8c2d6130dd454bf32e3350f94945fe0899ae7): Error starting userland proxy: listen tcp4 0.0.0.0:5000: bind: address already in use 
ERRO[0007] Failed to create cluster >>> Rolling Back    
INFO[0007] Deleting cluster 'zenml-kubeflow-c6d03f6a'   
INFO[0008] Deleting cluster network 'k3d-zenml-kubeflow-c6d03f6a' 
INFO[0008] Deleting 2 attached volumes...               
WARN[0008] Failed to delete volume 'k3d-zenml-kubeflow-c6d03f6a-images' of cluster 'zenml-kubeflow-c6d03f6a': failed to find volume 'k3d-zenml-kubeflow-c6d03f6a-images': Error: No such volume: k3d-zenml-kubeflow-c6d03f6a-images -> Try to delete it manually 
FATA[0008] Cluster creation FAILED, all changes have been rolled back! 
Command '['k3d', 'cluster', 'create', 'zenml-kubeflow-c6d03f6a', '--image', 'rancher/k3s:v1.23.5-k3s1', '--registry-create', 'k3d-zenml-kubeflow-registry.localhost:5000', '--registry-config', '/home/username/.config/zenml/kubeflow/c6d03f6a-424a-46db-bff6-b2c46692ea4e/k3d_registry.yaml', '--volume', '/home/username/.config/zenml:/home/laiml/.config/zenml']' returned non-zero exit status 1.
Unable to spin up local Kubeflow Pipelines deployment.
If you wish to spin up this Kubeflow local orchestrator manually, please enter the following commands:

> k3d cluster create zenml-kubeflow-c6d03f6a --image rancher/k3s:v1.23.5-k3s1 --registry-create k3d-zenml-kubeflow-registry.localhost:5000 --registry-config /home/username/.config/zenml/kubeflow/c6d03f6a-424a-46db-bff6-b2c46692ea4e/k3d_registry.yaml --volume /home/laiml/.config/zenml:/home/laiml/.config/zenml

> kubectl --context k3d-zenml-kubeflow-c6d03f6a apply -k github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-c6d03f6a wait --timeout=60s --for condition=established crd/applications.app.k8s.io
> kubectl --context k3d-zenml-kubeflow-c6d03f6a apply -k github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=1.8.1&timeout=5m
> kubectl --context k3d-zenml-kubeflow-c6d03f6a --namespace kubeflow port-forward svc/ml-pipeline-ui 8080:80
INFO[0000] No clusters found                            
Deleted local k3d cluster 'zenml-kubeflow-c6d03f6a'.
Local kubeflow pipelines deployment deprovisioned.
Provisioned resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, docker_parent_image=None, name=kubeflow_orches, uuid=c6d03f6a-424a-46db-bff6-b2c46692ea4e, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-c6d03f6a, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False).
Resuming provisioned resources for stack local_kube_stack.
Error: Unable to resume resources for KubeflowOrchestrator(type=orchestrator, flavor=kubeflow, docker_parent_image=None, name=kubeflow_orches, uuid=c6d03f6a-424a-46db-bff6-b2c46692ea4e, custom_docker_base_image_name=None, kubeflow_pipelines_ui_port=8080, kubeflow_hostname=None, kubernetes_context=k3d-zenml-kubeflow-c6d03f6a, synchronous=False, skip_local_validations=False, skip_cluster_provisioning=False, skip_ui_daemon_provisioning=False): No resources have been provisioned for this component.

**Comment by stefannica** [comment]
```driver failed programming external connectivity on endpoint k3d-zenml-kubeflow-registry.localhost (95a25a630be43991766cf9b4d8b8c2d6130dd454bf32e3350f94945fe0899ae7): Error starting userland proxy: listen tcp4 0.0.0.0:5000: bind: address already in use```

Something else on your machine is using port 5000. Probably a k3d registry left over from a previous run. I recommend that you use the `k3d cluster list`, `k3d cluster delete`, `k3d registry list` and `k3d registry delete` to remove any k3d clusters and container registries that may have been left over by previous incomplete runs.

**Comment by Coder-Vishali** [comment]
@stefannica, you were right. Port 5000 was in use. I stopped the service and rerun it. Now, cluster is getting created but I still see the error: error: git cmd = '/usr/bin/git fetch --depth=1 origin 1.8.1': exit status 128

I have checked the possible reasons for failure:
- Ensure git is installed (git version 2.17.1)
- Checked the kubectl version. It's the latest version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"
- Checked the internet connection. It is pretty good.
- Ensured that there is no lots of calls made to Github API.

Tried running the commands manually, as indicated in the log output. 
There are totally 5 commands to run manually. First two commands executed without any errors. I am stuck while executing the below (third) command:
kubectl --context k3d-zenml-kubeflow-c6d03f6a wait --timeout=60s --for condition=established crd/applications.app.k8s.io

Error:
**Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applications.app.k8s.io" not found**

**Comment by stefannica** [comment]
@Coder-Vishali I'm afraid there are some inconsistencies in your findings that I just can't explain without directly interacting with your setup. Do you think you could get someone with kubernetes experience to take a look at your Kubeflow installation ?

The only thing I can think of is that you may have not executed the commands correctly. Please note that the `&` character has a special meaning in Linux, so make sure you quote them out, e.g.:

kubectl --context k3d-zenml-kubeflow-82e3ca95 apply -k 'github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.1&timeout=5m'

**Comment by Coder-Vishali** [comment]
@stefannica, I have tried to uninstall the git and reinstalled it again. As you suggested I gave quotes for github link. I tried running the commands manually mentioned in the log output. I have reached till the last command.

While executing the last (below) command, I face issue saying unable to forward port because pod is not running.
!kubectl --context k3d-zenml-kubeflow-607609f8 --namespace kubeflow port-forward svc/ml-pipeline-ui 8080:80

error: unable to forward port because pod is not running. Current status=Pending

Do you have any idea how to resolve this?

**Comment by Coder-Vishali** [comment]
I suspect there is some kind of firewall issue. After connecting with different network the "zenml stack up" command was successfully executed.

Output:
Running with active profile: 'default' (local)
Provisioning resources for active stack 'local_kube_stack'.
Provisioning resources for stack 'local_kube_stack'.
Provisioning local Kubeflow Pipelines deployment...
Creating local K3D cluster 'zenml-kubeflow-607609f8'.
WARN[0000] No node filter specified                     
INFO[0000] Prep: Network                                
INFO[0000] Re-using existing network 'k3d-zenml-kubeflow-607609f8' (2fab10462e4233f0ca86f8a7fe6ad2c4d8284feeead540f52b3fa18530feefaf) 
INFO[0000] Created image volume k3d-zenml-kubeflow-607609f8-images 
INFO[0000] Creating node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0000] Successfully created registry 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0000] Starting new tools node...                   
INFO[0000] Starting Node 'k3d-zenml-kubeflow-607609f8-tools' 
INFO[0001] Creating node 'k3d-zenml-kubeflow-607609f8-server-0' 
INFO[0001] Creating LoadBalancer 'k3d-zenml-kubeflow-607609f8-serverlb' 
INFO[0001] Using the k3d-tools node to gather environment information 
INFO[0001] HostIP: using network gateway address 
INFO[0001] Starting cluster 'zenml-kubeflow-607609f8'   
INFO[0001] Starting servers...                          
INFO[0001] Starting Node 'k3d-zenml-kubeflow-607609f8-server-0' 
INFO[0006] All agents already running.                  
INFO[0006] Starting helpers...                          
INFO[0006] Starting Node 'k3d-zenml-kubeflow-registry.localhost' 
INFO[0006] Starting Node 'k3d-zenml-kubeflow-607609f8-serverlb' 
INFO[0014] Injecting records for hostAliases (incl. host.k3d.internal) and for 3 network members into CoreDNS configmap... 
INFO[0017] Cluster 'zenml-kubeflow-607609f8' created successfully! 
INFO[0018] You can now use it like this:                
kubectl cluster-info
Finished K3D cluster creation.
Deploying Kubeflow Pipelines.

Thank you for the support @stefannica. You can close the issue.
