### ISSUE TITLE
[FEATURE]: ClearML integration

### ISSUE THREAD

**Issue by Aleksandar1932** [zenml-io/zenml#896]
### Contact Details

aleksandar.ivanovski123@gmail.com

### Describe the feature you'd like

I would propose integration with [ClearML](https://clear.ml), mainly for the popularity of the platform and it's broad array of implemented MLOps practices, spanning from experiment tracking to production model serving.

### How do you solve your current problem with the current status-quo of ZenML?

I am using the ClearML SDK and manually invoking functions for certain tasks, i.e. metrics logging or model registering.

### Any other comments?

If the discussion proceeds and it is decided to proceed with this integration, I am willing to contribute to its development.

**Comment by htahir1** [comment]
Thank you for the ticket @Aleksandar1932  ! Feature requests now go to our roadmap where other community members can also vote for them! Could you perhaps make a ticket here: https://zenml.hellonext.co/b/feedback

Having said that I think a ClearML integration would be amazing as well - can you share the way you write the steps right now with the ClearML SDK?

**Comment by htahir1** [comment]
Feature request moved here: https://zenml.hellonext.co/p/integration-with-clearml
