### ISSUE TITLE
Change MLFlow Experiment name from pipeline name

### ISSUE THREAD

**Issue by mHash1m** [zenml-io/zenml#903]
It seems zenml sets experiment name to pipeline and even overrides `mlflow.set_experiment()`.

https://github.com/zenml-io/zenml/blob/116a72f8973002f49b7a63898403a0ef8cdd1c65/src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py#L325

Is there any way to change the experiment name and keep run names as pipeline names? I'm currently using the decorator `@enable_mlflow`

**Comment by htahir1** [comment]
With the new version of ZenML on the horizon, the mlflow experiment tracker is a bit more flexible. Lets wait for the release next week and try to tackle this issue then

**Comment by mHash1m** [comment]
Awesome!

**Comment by htahir1** [comment]
@mHash1m With the new version, you can now do it like you used too but with a new syntax: https://docs.zenml.io/component-gallery/experiment-trackers/mlflow#how-do-you-use-it. Closing this issue with that update!

**Comment by mHash1m** [comment]
Hi @htahir1, I just got to update to the latest version and try this out again, unfortunately I still couldn't make it work. Couldn't find any particular setting that would make any changes.
Following is how I'm currently setting up experiments in code:
```
@step(experiment_tracker="mlflow_tracker")
def run_h2o(input_data: pd.DataFrame, feats: list) -> Output(dummy=str):
    """
    Args:
        input_data: pd.DataFrame
    """
    try:
        client = MlflowClient()
        experiment_name = "ABC"
        try:
            experiment = mlflow.create_experiment(experiment_name)
        except:
            experiment = client.get_experiment_by_name(experiment_name)
        mlflow.set_experiment(experiment_name)
        mlflow.log_param("Input Dimensions", input_data.shape)
````
What I get as a result is an experiment with the name of my pipeline run that has all that logs, and an empty experiment that I had set within my code.
It is a similar behavior to what was happening in previous zenml versions.

**Comment by htahir1** [comment]
Sure! You can set the experiment name now with the settings flag 
!
Basically:


```import mlflow
from zenml.integrations.mlflow.flavors.mlflow_experiment_tracker_flavor import MLFlowExperimentTrackerSettings

mlflow_settings = MLFlowExperimentTrackerSettings(
    nested=True,
    experiment_name="whatevr",
    tags={"key": "value"}
)

@step(
    experiment_tracker="<MLFLOW_TRACKER_STACK_COMPONENT_NAME>",
    settings={
        "experiment_tracker.mlflow": mlflow_settings
    }
)
def step_one(
    data: np.ndarray,
) -> np.ndarray:
    ...
```
See https://docs.zenml.io/component-gallery/experiment-trackers/mlflow
and [https://apidocs.zenml.io/0.20.4/api_docs/integrations/#zenml.integrations.mlflow.flavors.mlflow_expe[…]racker_flavor.MLFlowExperimentTrackerSettings](https://apidocs.zenml.io/0.20.4/api_docs/integrations/#zenml.integrations.mlflow.flavors.mlflow_experiment_tracker_flavor.MLFlowExperimentTrackerSettings) for details

**Comment by mHash1m** [comment]
Ah, I missed that.
Thank you so much, its working now!
