### ISSUE TITLE
[BUG] Mac M1 environment unable to use zenml CLI

### ISSUE THREAD

**Issue by liguodongIOT** [zenml-io/zenml#93]
How should I solve this problem?

> zsh: illegal hardware instruction  zenml

**Comment by htahir1** [comment]
Could you please add the full traceback as well as the ZenML version and MAC OS version?

**Comment by liguodongIOT** [comment]
Thank you very much for your answer.

### **My installation steps：**

```
pip  install  -i  https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com  zenml
pip install pytorch-lightning==1.1.8

# add this to ~/.zshrc
eval "$(_ZENML_COMPLETE=source_zsh zenml)"

zenml version
```

### **My environment：**

**mac os version:** 11.1

![image](https://user-images.githubusercontent.com/13220186/126318688-c1c9b5e7-1492-431d-b207-1e369f903595.png)

**zenml version:** 0.3.8

**conda version:** 4.9.2

**python version:** 3.8

**Comment by htahir1** [comment]
Could try running this script:

```
from zenml.version import __version__
print(__version__)
```

 And let us know what you get?

**Comment by liguodongIOT** [comment]
Running this script is normal.

> python
```
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from zenml.version import __version__
>>> print(__version__)
0.3.8
```

**Comment by htahir1** [comment]
As it seems to be working installation wise, I feel like the CLI problem might be due to a zsh configuration rather than a ZenML installation one. Were you able to run `zenml init` on the CLI? Could you try alternatively using simple bash than zsh?

**Comment by liguodongIOT** [comment]
Run `zenml init` on the CLI, same error.

![image](https://user-images.githubusercontent.com/13220186/126578436-7fb095ad-ea07-4309-bf6f-df6b69fc7ad3.png)

When I use bash, I still get an error：

![image](https://user-images.githubusercontent.com/13220186/126578324-105b76fa-e698-4a50-b2f5-cc99fcd68b78.png)

**Comment by htahir1** [comment]
Thank you for the info. I feel like this an underlying problem with Tensorflow on Mac M1. See the following issues:

https://github.com/apple/tensorflow_macos/issues/143
https://github.com/ludwig-ai/ludwig/issues/1101
https://github.com/openeventdata/mordecai/issues/97

Is it possible for you to try the fixes mentioned here https://github.com/apple/tensorflow_macos/issues/143 and let us know if that works? Otherwise I'd ask to please wait until we get rid of the tensorflow dependency (circa ~1 month) for our big refactored release and it should then work!

**Comment by liguodongIOT** [comment]
Hi, there is a version conflict in installing zenml using tensorflow_macos virtual environment。

![image](https://user-images.githubusercontent.com/13220186/126623028-77651de4-3c21-4a6b-947d-f196ae2edb94.png)
![image](https://user-images.githubusercontent.com/13220186/126623152-7d5444cd-38ac-4920-ab5e-569227f0c5d4.png)

**Comment by htahir1** [comment]
This will be solved when we get rid of the Tensorflow dependency. Another suggestion: Can you try using our Docker Image instead to run ZenML: `https://hub.docker.com/u/zenmldocker`

**Comment by liguodongIOT** [comment]
Hi, I tried this way, but I still get an error:

![1627356284426](https://user-images.githubusercontent.com/13220186/127090486-0c565dee-14cc-4571-9285-aac1d35f17a5.jpg)

**Comment by htahir1** [comment]
This is strange - it seems like a segmentation fault in the C++ core of tensorflow now. It seems like they have just stopped supporting Mac altogether: https://github.com/tensorflow/tensorflow/issues/42387

Unfortunately at this point, I would suggest you wait for our updated release as it will get us away from the Tensorflow dependency. Sorry for the inconvenience here!

**Comment by htahir1** [comment]
Closing due to staleness, and hopefully solved in the new release.
