### ISSUE TITLE
[FEATURE] Provide integration with PyTorch-Ignite

### ISSUE THREAD

**Issue by vfdev-5** [zenml-io/zenml#94]
**Is your feature request related to a problem? Please describe.**

Provide an example with [PyTorch-Ignite](https://github.com/pytorch/ignite) here:  https://github.com/maiot-io/zenml/tree/main/examples

What do you think ?

**Comment by htahir1** [comment]
Sorry for the late reply - Happy to have an example. Is it possible to share more details about PyTorch-Ignite? The core ZenML team is not familiar with it. Would you be open to creating a PR? :-) We can help out!

**Comment by vfdev-5** [comment]
Here is a [tutorial](https://labs.quansight.org/blog/2020/09/pytorch-ignite/) to make your team more familiar with it :) 

> Would you be open to creating a PR? :-) We can help out!

Unfortunately, right now I have no bandwidth to create PR.

**Comment by htahir1** [comment]
Thank you - we're heads down working on our [ROADMAP](https://github.com/maiot-io/zenml/blob/main/ROADMAP.md) as of this moment so will find it hard to add this feature in the near future. Happy to incorporate it into our list of integrations somewhere down the line. I hope you understand that we have to balance community feedback and demand with our own limited time and resources! :-)

Again, more than happy to receive a PR if bandwidth opens up. For now, i'd be happy to add it to the roadmap and close out this issue if that solution is fair
