### ISSUE TITLE
[BUG]: Broken link to stack-components documentation on Zenserver

### ISSUE THREAD

**Issue by lopezco** [zenml-io/zenml#969]
### System Information

v0.20.3

### What happened?

![image](https://user-images.githubusercontent.com/6637618/195841634-52b5b20e-2682-45db-b9e3-b7b43d382f53.png)

`Documentation` link is broken. It redirects to: https://docs.zenml.io/starter-guide/stacks/stacks-components

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
Thank you for the report!

**Comment by htahir1** [comment]
I fixed this with this commit: https://github.com/zenml-io/zenml-dashboard/commit/82c36d10ff5a566619727832c7d05ed4cc5036b5
