### ISSUE TITLE
[BUG]: Mock data showing up spuriosly on deployed ZenML

### ISSUE THREAD

**Issue by lopezco** [zenml-io/zenml#970]
### System Information

- zenml==0.20.3
- Brave browser (v1.44.112 - Oct 12th, 2022)

### What happened?

I deployed Zenml server using the helm chart on an existing Kubernetes cluster.

I login as default user (name=Admin) and leave the browser tab open.

After a while, I come back and the user name on top is `Hamza Tahir` (@hamzamaiot ).  Like below

![image](https://user-images.githubusercontent.com/6637618/195847366-9f5065c8-84e4-4d21-b353-cb26d179f6af.png)

If I refresh the page, on the top right corner I get the correct name (Admin) but the settings info displays Hamza's (@hamzamaiot )

![image](https://user-images.githubusercontent.com/6637618/195847495-93c50f39-1e1e-4279-bf7e-9ff08ee12fc4.png)

If I refresh again everything is ok

![image](https://user-images.githubusercontent.com/6637618/195847593-15ce62c2-ad9a-4e73-9b12-c94003f30dbb.png)

Are Hamza's name and username hardcoded somewhere?

### Reproduction steps

1. Install zenserver using the helm chart
2. Loging as default user and give `Admin` as fullname
3. Add some users of my team (none of which is `Hamza`)
4. Open the user settings screen and leave it open for a while
5. Come back to the UI
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@lopezco Yes, the names are currently hard-coded as mock data and spuriously show up when there is some error in the back (e.g. some problem connecting to the API). We are removing the hard-coded mock data in the next releases, but I fear I do not have enough information to debug why this is happening for you. Can you open the network tab and see if the API calls being made from the dashboard are properly being sent?

**Comment by lopezco** [comment]
I think that the fact taht we have a self-signed cert is causing problems: 
![image](https://user-images.githubusercontent.com/6637618/195903326-05e0c67b-06c3-4885-81f6-23b31c83fc70.png)

![image](https://user-images.githubusercontent.com/6637618/195903202-ea980a54-3064-4583-8791-db05a1e1c576.png)

We will get that fixed and I'll test again.

**Comment by hamzamaiot** [comment]
You can also visit the API URL directly on the browser and "allow insecure
access" and then the dashboard should work in the same browser session

**Comment by lopezco** [comment]
@hamzamaiot, it worked.
We will fix the cert issue ASAP

On another subject, I realised that there is a 404 on `/api/v1/organizations`, but that is another issue

![image](https://user-images.githubusercontent.com/6637618/196155934-62f8fd52-51a1-4bfd-acc3-93a68022e1ea.png)
